.TH "F:/Fusion3D_work/src/progs/bird_prog.h" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/Fusion3D_work/src/progs/bird_prog.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include '3DEngine\&.h'\fP
.br
\fC#include 'components/physicsObjectComponent\&.h'\fP
.br
\fC#include 'rendering/camera\&.h'\fP
.br
\fC#include 'components/freeLook\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBPipe\fP ()"
.br
.ti -1c
.RI "virtual int \fBUpdate\fP (float delta)"
.br
.ti -1c
.RI "\fBBird\fP (float aspect, \fBVector2f\fP center, float sensitivity)"
.br
.ti -1c
.RI "virtual \fB~Bird\fP ()"
.br
.ti -1c
.RI "virtual int \fBProcessInput\fP (const \fBInput\fP &input, float delta)"
.br
.ti -1c
.RI "virtual int \fBInit\fP ()"
.br
.ti -1c
.RI "virtual int \fBRender\fP (const \fBShader\fP &shader, const \fBRenderingEngine\fP &renderingEngine, const \fBCamera\fP &camera)"
.br
.ti -1c
.RI "\fBBirdCubemap\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBDelayTimer\fP \fBm_timer\fP"
.br
.ti -1c
.RI "bool \fBonce\fP = false"
.br
.ti -1c
.RI "int \fBm_count\fP"
.br
.ti -1c
.RI "\fBPhysicsObjectComponent\fP * \fBm_body\fP"
.br
.ti -1c
.RI "bool \fBm_pause\fP"
.br
.ti -1c
.RI "float \fBm_time\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "Bird (float aspect, \fBVector2f\fP center, float sensitivity)"

.SS "BirdCubemap ()"

.SS "virtual int Init ()\fC [virtual]\fP"

.SS "Pipe ()"

.SS "virtual int ProcessInput (const \fBInput\fP & input, float delta)\fC [virtual]\fP"

.SS "virtual int Render (const \fBShader\fP & shader, const \fBRenderingEngine\fP & renderingEngine, const \fBCamera\fP & camera)\fC [virtual]\fP"

.SS "virtual int Update (float delta)\fC [virtual]\fP"

.SS "virtual ~\fBBird\fP ()\fC [virtual]\fP"

.SH "Variable Documentation"
.PP 
.SS "\fBPhysicsObjectComponent\fP* m_body"

.SS "int m_count"

.SS "bool m_pause"

.SS "float m_time"

.SS "\fBDelayTimer\fP m_timer"

.SS "bool once = false"

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
