.TH "F:/Fusion3D_work/src/rendering/camera.h" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/Fusion3D_work/src/rendering/camera.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./core/math3d\&.h'\fP
.br
\fC#include '\&.\&./core/entityComponent\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCamera\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCAMERA_H\fP   'Camera'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBCameraComponent\fP (const \fBMatrix4f\fP &projection)"
.br
.ti -1c
.RI "virtual void \fBAddToEngine\fP (\fBCoreEngine\fP *engine)"
.br
.ti -1c
.RI "\fBMatrix4f\fP \fBGetViewProjection\fP () const "
.br
.ti -1c
.RI "void \fBSetProjection\fP (const \fBMatrix4f\fP &projection)"
.br
.ti -1c
.RI "virtual void \fBSetParent\fP (\fBEntity\fP *parent)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBCamera\fP \fBm_camera\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CAMERA_H   'Camera'"

.SH "Function Documentation"
.PP 
.SS "virtual void AddToEngine (\fBCoreEngine\fP * engine)\fC [virtual]\fP"

.SS "CameraComponent (const \fBMatrix4f\fP & projection)"

.SS "\fBMatrix4f\fP GetViewProjection () const\fC [inline]\fP"

.SS "virtual void SetParent (\fBEntity\fP * parent)\fC [virtual]\fP"

.SS "void SetProjection (const \fBMatrix4f\fP & projection)\fC [inline]\fP"

.SH "Variable Documentation"
.PP 
.SS "\fBCamera\fP m_camera"

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
