.TH "chunk" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
chunk \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBuint32\fP \fBlength\fP"
.br
.ti -1c
.RI "\fBuint32\fP \fBtype\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBuint32\fP chunk::length"

.SS "\fBuint32\fP chunk::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
