.TH "Collider" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Collider \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <collider\&.h>\fP
.PP
Inherits \fBReferenceCounter\fP\&.
.PP
Inherited by \fBBoundingSphere\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBTYPE_SPHERE\fP, \fBTYPE_AABB\fP, \fBTYPE_SIZE\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCollider\fP (int type)"
.br
.ti -1c
.RI "\fBIntersectData\fP \fBIntersect\fP (const \fBCollider\fP &other) const "
.br
.ti -1c
.RI "virtual void \fBTransform\fP (const \fBVector3f\fP &translation)"
.br
.ti -1c
.RI "virtual \fBVector3f\fP \fBGetCenter\fP () const "
.br
.ti -1c
.RI "int \fBGetType\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBCollider\fP class is the base class for colliders that can be used in the physics engine\&. More specific colliders should inherit from this class 
.SH "Member Enumeration Documentation"
.PP 
.SS "anonymous enum"
This enumeration stores all the types of colliders that can be used\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fITYPE_SPHERE \fP\fP
.TP
\fB\fITYPE_AABB \fP\fP
.TP
\fB\fITYPE_SIZE \fP\fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Collider::Collider (int type)\fC [inline]\fP"
Creates a \fBCollider\fP in a usable state\&.
.PP
\fBParameters:\fP
.RS 4
\fItype\fP The type of collider this represents\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "virtual \fBVector3f\fP Collider::GetCenter () const\fC [inline]\fP, \fC [virtual]\fP"
Returns the center position of the collider\&. Should be overriden by subclasses\&. 
.PP
Reimplemented in \fBBoundingSphere\fP\&.
.SS "int Collider::GetType () const\fC [inline]\fP"
Basic getter 
.SS "\fBIntersectData\fP Collider::Intersect (const \fBCollider\fP & other) const"
Calculates information about if this collider is intersecting with another collider\&.
.PP
\fBParameters:\fP
.RS 4
\fIother\fP The collider that is being checked for intersection\&. 
.RE
.PP

.SS "virtual void Collider::Transform (const \fBVector3f\fP & translation)\fC [inline]\fP, \fC [virtual]\fP"
Moves the entire collider by translation distance\&. Should be overriden by subclasses\&.
.PP
\fBParameters:\fP
.RS 4
\fItranslation\fP Distance to move the collider 
.RE
.PP

.PP
Reimplemented in \fBBoundingSphere\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
