.TH "F:/Fusion3D_work/src/utils/colors.h" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/Fusion3D_work/src/utils/colors.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <windows\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCPRINT\fP(c1,  c2,  x)   \fBtextcolor\fP(c1); std::cout << x; \fBtextcolor\fP(c2)"
.br
.RI "\fIMACROS\&. \fP"
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBblack\fP, \fBdark_blue\fP, \fBdark_green\fP, \fBdark_cyan\fP, \fBdark_red\fP, \fBdark_magenta\fP, \fBdark_yellow\fP, \fBlight_gray\fP, \fBdark_gray\fP, \fBlight_blue\fP, \fBlight_green\fP, \fBlight_cyan\fP, \fBlight_red\fP, \fBlight_magenta\fP, \fBlight_yellow\fP, \fBwhite\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "WORD \fBconcatcolors\fP (WORD color1, WORD color2)"
.br
.RI "\fIFUNCTIONS\&. \fP"
.ti -1c
.RI "int \fBtextcolor\fP (WORD color)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CPRINT(c1, c2, x)   \fBtextcolor\fP(c1); std::cout << x; \fBtextcolor\fP(c2)"

.PP
MACROS\&. 
.SH "Enumeration Type Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIblack \fP\fP
.TP
\fB\fIdark_blue \fP\fP
.TP
\fB\fIdark_green \fP\fP
.TP
\fB\fIdark_cyan \fP\fP
.TP
\fB\fIdark_red \fP\fP
.TP
\fB\fIdark_magenta \fP\fP
.TP
\fB\fIdark_yellow \fP\fP
.TP
\fB\fIlight_gray \fP\fP
.TP
\fB\fIdark_gray \fP\fP
.TP
\fB\fIlight_blue \fP\fP
.TP
\fB\fIlight_green \fP\fP
.TP
\fB\fIlight_cyan \fP\fP
.TP
\fB\fIlight_red \fP\fP
.TP
\fB\fIlight_magenta \fP\fP
.TP
\fB\fIlight_yellow \fP\fP
.TP
\fB\fIwhite \fP\fP
.SH "Function Documentation"
.PP 
.SS "WORD concatcolors (WORD color1, WORD color2)"

.PP
FUNCTIONS\&. 
.SS "int textcolor (WORD color)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
