.TH "core" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core \- GLM Core
.PP
The core of GLM, which implements exactly and only the GLSL specification to the degree possible\&.  

.SS "Modules"

.in +1c
.ti -1c
.RI "\fBTypes\fP"
.br
.RI "\fIThe standard types defined by the specification\&. \fP"
.ti -1c
.RI "\fBPrecision types\fP"
.br
.RI "\fINon-GLSL types that are used to define precision-based types\&. \fP"
.ti -1c
.RI "\fBTemplate types\fP"
.br
.RI "\fIThe generic template types used as the basis for the core types\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
The core of GLM, which implements exactly and only the GLSL specification to the degree possible\&. 

The GLM core consists of \fBC++ types that mirror GLSL types\fP and C++ functions that mirror the GLSL functions\&. It also includes \fBa set of precision-based types\fP that can be used in the appropriate functions\&. The C++ types are all based on a basic set of \fBtemplate types\fP\&.
.PP
The best documentation for GLM Core is the current GLSL specification, \fCversion 4\&.2 (pdf file)\fP\&.
.PP
GLM core functionnalities require <\fBglm/glm\&.hpp\fP> to be included to be used\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
