.TH "core_precision" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core_precision \- Precision types
.PP
Non-GLSL types that are used to define precision-based types\&.  
Non-GLSL types that are used to define precision-based types\&. 

The GLSL language allows the user to define the precision of a particular variable\&. In OpenGL's GLSL, these precision qualifiers have no effect; they are there for compatibility with OpenGL ES's precision qualifiers, where they \fIdo\fP have an effect\&.
.PP
C++ has no language equivalent to precision qualifiers\&. So GLM provides the next-best thing: a number of typedefs of the \fBTemplate types\fP that use a particular precision\&.
.PP
None of these types make any guarantees about the actual precision used\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
