.TH "core_template" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core_template \- Template types
.PP
The generic template types used as the basis for the core types\&.  
The generic template types used as the basis for the core types\&. 

These types are all templates used to define the actual \fBTypes\fP\&. These templetes are implementation details of GLM types and should not be used explicitly\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
