.TH "F:/Fusion3D_work/src/components/decalRenderer.h" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/Fusion3D_work/src/components/decalRenderer.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./core/entityComponent\&.h'\fP
.br
\fC#include '\&.\&./rendering/mesh\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBDecalRenderer\fP (\fBMaterial\fP *material)"
.br
.ti -1c
.RI "virtual void \fBInit\fP ()"
.br
.ti -1c
.RI "virtual void \fBRender\fP (const \fBShader\fP &shader, const \fBRenderingEngine\fP &renderingEngine, const \fBCamera\fP &camera) const "
.br
.ti -1c
.RI "\fBEntityComponent\fP * \fBSetVisible\fP (bool visible)"
.br
.ti -1c
.RI "bool \fBIsVisible\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBMaterial\fP * \fBm_material\fP"
.br
.ti -1c
.RI "bool \fBm_visible\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "DecalRenderer (\fBMaterial\fP * material)"

.SS "virtual void Init ()\fC [virtual]\fP"

.SS "bool IsVisible ()"

.SS "virtual void Render (const \fBShader\fP & shader, const \fBRenderingEngine\fP & renderingEngine, const \fBCamera\fP & camera) const\fC [virtual]\fP"

.SS "\fBEntityComponent\fP* SetVisible (bool visible)"

.SH "Variable Documentation"
.PP 
.SS "\fBMaterial\fP* m_material"

.SS "bool m_visible"

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
