.TH "DelayTimer" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DelayTimer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <timing\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDelayTimer\fP ()"
.br
.ti -1c
.RI "\fBDelayTimer\fP (double delay)"
.br
.ti -1c
.RI "double \fBGetDelay\fP () const "
.br
.ti -1c
.RI "void \fBSetDelay\fP (double delay)"
.br
.ti -1c
.RI "int \fBHasElapsed\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DelayTimer::DelayTimer ()\fC [inline]\fP"

.SS "DelayTimer::DelayTimer (double delay)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "double DelayTimer::GetDelay () const\fC [inline]\fP"

.SS "int DelayTimer::HasElapsed ()\fC [inline]\fP"

.SS "void DelayTimer::SetDelay (double delay)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
