.TH "F:/Fusion3D_work/src/components/devMode.h" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/Fusion3D_work/src/components/devMode.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./core/coreEngine\&.h'\fP
.br
\fC#include '\&.\&./components/programComponent\&.h'\fP
.br
\fC#include '\&.\&./components/freeMove\&.h'\fP
.br
\fC#include '\&.\&./components/freeLook\&.h'\fP
.br
\fC#include <vector>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBDevMode\fP (const \fBWindow\fP &window, bool isDev=true)"
.br
.ti -1c
.RI "virtual \fB~DevMode\fP ()"
.br
.ti -1c
.RI "virtual void \fBInit\fP ()"
.br
.ti -1c
.RI "virtual void \fBProcessInput\fP (const \fBInput\fP &input, float delta)"
.br
.ti -1c
.RI "virtual void \fBUpdate\fP (float delta)"
.br
.ti -1c
.RI "virtual void \fBRender\fP (const \fBShader\fP &shader, const \fBRenderingEngine\fP &renderingEngine, const \fBCamera\fP &camera)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBCoreEngine\fP * \fBm_engine\fP"
.br
.ti -1c
.RI "\fBFreeMove\fP * \fBm_move\fP"
.br
.ti -1c
.RI "\fBFreeLook\fP * \fBm_look\fP"
.br
.ti -1c
.RI "const \fBWindow\fP * \fBm_window\fP"
.br
.ti -1c
.RI "double \fBspeed\fP"
.br
.ti -1c
.RI "bool \fBm_isUpdating\fP"
.br
.ti -1c
.RI "bool \fBm_isDev\fP"
.br
.ti -1c
.RI "bool \fBm_isCmd\fP"
.br
.ti -1c
.RI "bool \fBm_showCursor\fP"
.br
.ti -1c
.RI "std::vector< char > \fBm_keySequence\fP"
.br
.ti -1c
.RI "\fBCamera\fP \fBm_devCamera\fP"
.br
.ti -1c
.RI "const \fBCamera\fP * \fBm_lastCamera\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "DevMode (const \fBWindow\fP & window, bool isDev = \fCtrue\fP)"

.SS "virtual void Init ()\fC [virtual]\fP"

.SS "virtual void ProcessInput (const \fBInput\fP & input, float delta)\fC [virtual]\fP"

.SS "virtual void Render (const \fBShader\fP & shader, const \fBRenderingEngine\fP & renderingEngine, const \fBCamera\fP & camera)\fC [virtual]\fP"

.SS "int Update (float delta)\fC [virtual]\fP"

.SS "virtual ~\fBDevMode\fP ()\fC [virtual]\fP"

.SH "Variable Documentation"
.PP 
.SS "\fBCamera\fP m_devCamera"

.SS "\fBCoreEngine\fP* m_engine"

.SS "bool m_isCmd"

.SS "bool m_isDev"

.SS "bool m_isUpdating"

.SS "std::vector<char> m_keySequence"

.SS "const \fBCamera\fP* m_lastCamera"

.SS "\fBFreeLook\fP* m_look"

.SS "\fBFreeMove\fP* m_move"

.SS "bool m_showCursor"

.SS "const \fBWindow\fP* m_window"

.SS "double speed"

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
