.TH "EntityComponent" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EntityComponent \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <entityComponent\&.h>\fP
.PP
Inherited by \fBPhysicsObjectComponent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEntityComponent\fP ()"
.br
.ti -1c
.RI "virtual \fB~EntityComponent\fP ()"
.br
.ti -1c
.RI "virtual std::string \fB_GetClassName_\fP ()"
.br
.ti -1c
.RI "virtual void \fBInit\fP ()"
.br
.ti -1c
.RI "virtual void \fBProcessInput\fP (const \fBInput\fP &input, float delta)"
.br
.ti -1c
.RI "virtual void \fBUpdate\fP (float delta)"
.br
.ti -1c
.RI "virtual void \fBRender\fP (const \fBShader\fP &shader, const \fBRenderingEngine\fP &renderingEngine, const \fBCamera\fP &camera) const "
.br
.ti -1c
.RI "virtual void \fBPostRender\fP (const \fBShader\fP &shader, const \fBRenderingEngine\fP &renderingEngine, const \fBCamera\fP &camera) const "
.br
.ti -1c
.RI "virtual void \fBAddToEngine\fP (\fBCoreEngine\fP *engine)"
.br
.ti -1c
.RI "\fBTransform\fP * \fBGetTransform\fP ()"
.br
.ti -1c
.RI "const \fBTransform\fP & \fBGetTransform\fP () const "
.br
.ti -1c
.RI "virtual void \fBSetParent\fP (\fBEntity\fP *parent)"
.br
.ti -1c
.RI "\fBEntity\fP * \fBGetParent\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EntityComponent::EntityComponent ()\fC [inline]\fP"

.SS "virtual EntityComponent::~EntityComponent ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual std::string EntityComponent::_GetClassName_ ()\fC [inline]\fP, \fC [virtual]\fP"

.SS "virtual void EntityComponent::AddToEngine (\fBCoreEngine\fP * engine)\fC [inline]\fP, \fC [virtual]\fP"

.SS "\fBEntity\fP* EntityComponent::GetParent ()\fC [inline]\fP"

.SS "\fBTransform\fP* EntityComponent::GetTransform ()\fC [inline]\fP"

.SS "const \fBTransform\fP& EntityComponent::GetTransform () const\fC [inline]\fP"

.SS "virtual void EntityComponent::Init ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBPhysicsObjectComponent\fP\&.
.SS "virtual void EntityComponent::PostRender (const \fBShader\fP & shader, const \fBRenderingEngine\fP & renderingEngine, const \fBCamera\fP & camera) const\fC [inline]\fP, \fC [virtual]\fP"

.SS "virtual void EntityComponent::ProcessInput (const \fBInput\fP & input, float delta)\fC [inline]\fP, \fC [virtual]\fP"

.SS "virtual void EntityComponent::Render (const \fBShader\fP & shader, const \fBRenderingEngine\fP & renderingEngine, const \fBCamera\fP & camera) const\fC [inline]\fP, \fC [virtual]\fP"

.SS "virtual void EntityComponent::SetParent (\fBEntity\fP * parent)\fC [inline]\fP, \fC [virtual]\fP"

.SS "virtual void EntityComponent::Update (float delta)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBPhysicsObjectComponent\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
