.TH "F:/Fusion3D_work/src/staticLibs/glm/gtx Directory Reference" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/Fusion3D_work/src/staticLibs/glm/gtx Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBassociated_min_max\&.hpp\fP"
.br
.ti -1c
.RI "file \fBassociated_min_max\&.inl\fP"
.br
.ti -1c
.RI "file \fBbit\&.hpp\fP"
.br
.ti -1c
.RI "file \fBbit\&.inl\fP"
.br
.ti -1c
.RI "file \fBclosest_point\&.hpp\fP"
.br
.ti -1c
.RI "file \fBclosest_point\&.inl\fP"
.br
.ti -1c
.RI "file \fBcolor_space\&.hpp\fP"
.br
.ti -1c
.RI "file \fBcolor_space\&.inl\fP"
.br
.ti -1c
.RI "file \fBcolor_space_YCoCg\&.hpp\fP"
.br
.ti -1c
.RI "file \fBcolor_space_YCoCg\&.inl\fP"
.br
.ti -1c
.RI "file \fBcommon\&.hpp\fP"
.br
.ti -1c
.RI "file \fBcommon\&.inl\fP"
.br
.ti -1c
.RI "file \fBcompatibility\&.hpp\fP"
.br
.ti -1c
.RI "file \fBcompatibility\&.inl\fP"
.br
.ti -1c
.RI "file \fBcomponent_wise\&.hpp\fP"
.br
.ti -1c
.RI "file \fBcomponent_wise\&.inl\fP"
.br
.ti -1c
.RI "file \fBdual_quaternion\&.hpp\fP"
.br
.ti -1c
.RI "file \fBdual_quaternion\&.inl\fP"
.br
.ti -1c
.RI "file \fBeuler_angles\&.hpp\fP"
.br
.ti -1c
.RI "file \fBeuler_angles\&.inl\fP"
.br
.ti -1c
.RI "file \fBextend\&.hpp\fP"
.br
.ti -1c
.RI "file \fBextend\&.inl\fP"
.br
.ti -1c
.RI "file \fBextented_min_max\&.hpp\fP"
.br
.ti -1c
.RI "file \fBextented_min_max\&.inl\fP"
.br
.ti -1c
.RI "file \fBfast_exponential\&.hpp\fP"
.br
.ti -1c
.RI "file \fBfast_exponential\&.inl\fP"
.br
.ti -1c
.RI "file \fBfast_square_root\&.hpp\fP"
.br
.ti -1c
.RI "file \fBfast_square_root\&.inl\fP"
.br
.ti -1c
.RI "file \fBfast_trigonometry\&.hpp\fP"
.br
.ti -1c
.RI "file \fBfast_trigonometry\&.inl\fP"
.br
.ti -1c
.RI "file \fBgradient_paint\&.hpp\fP"
.br
.ti -1c
.RI "file \fBgradient_paint\&.inl\fP"
.br
.ti -1c
.RI "file \fBhanded_coordinate_space\&.hpp\fP"
.br
.ti -1c
.RI "file \fBhanded_coordinate_space\&.inl\fP"
.br
.ti -1c
.RI "file \fBhash\&.hpp\fP"
.br
.ti -1c
.RI "file \fBhash\&.inl\fP"
.br
.ti -1c
.RI "file \fBinteger\&.hpp\fP"
.br
.ti -1c
.RI "file \fBinteger\&.inl\fP"
.br
.ti -1c
.RI "file \fBintersect\&.hpp\fP"
.br
.ti -1c
.RI "file \fBintersect\&.inl\fP"
.br
.ti -1c
.RI "file \fBio\&.hpp\fP"
.br
.ti -1c
.RI "file \fBio\&.inl\fP"
.br
.ti -1c
.RI "file \fBlog_base\&.hpp\fP"
.br
.ti -1c
.RI "file \fBlog_base\&.inl\fP"
.br
.ti -1c
.RI "file \fBmatrix_cross_product\&.hpp\fP"
.br
.ti -1c
.RI "file \fBmatrix_cross_product\&.inl\fP"
.br
.ti -1c
.RI "file \fBmatrix_decompose\&.hpp\fP"
.br
.ti -1c
.RI "file \fBmatrix_decompose\&.inl\fP"
.br
.ti -1c
.RI "file \fBmatrix_interpolation\&.hpp\fP"
.br
.ti -1c
.RI "file \fBmatrix_interpolation\&.inl\fP"
.br
.ti -1c
.RI "file \fBmatrix_major_storage\&.hpp\fP"
.br
.ti -1c
.RI "file \fBmatrix_major_storage\&.inl\fP"
.br
.ti -1c
.RI "file \fBmatrix_operation\&.hpp\fP"
.br
.ti -1c
.RI "file \fBmatrix_operation\&.inl\fP"
.br
.ti -1c
.RI "file \fBmatrix_query\&.hpp\fP"
.br
.ti -1c
.RI "file \fBmatrix_query\&.inl\fP"
.br
.ti -1c
.RI "file \fBmatrix_transform_2d\&.hpp\fP"
.br
.ti -1c
.RI "file \fBmatrix_transform_2d\&.inl\fP"
.br
.ti -1c
.RI "file \fBmixed_product\&.hpp\fP"
.br
.ti -1c
.RI "file \fBmixed_product\&.inl\fP"
.br
.ti -1c
.RI "file \fBnorm\&.hpp\fP"
.br
.ti -1c
.RI "file \fBnorm\&.inl\fP"
.br
.ti -1c
.RI "file \fBnormal\&.hpp\fP"
.br
.ti -1c
.RI "file \fBnormal\&.inl\fP"
.br
.ti -1c
.RI "file \fBnormalize_dot\&.hpp\fP"
.br
.ti -1c
.RI "file \fBnormalize_dot\&.inl\fP"
.br
.ti -1c
.RI "file \fBnumber_precision\&.hpp\fP"
.br
.ti -1c
.RI "file \fBnumber_precision\&.inl\fP"
.br
.ti -1c
.RI "file \fBoptimum_pow\&.hpp\fP"
.br
.ti -1c
.RI "file \fBoptimum_pow\&.inl\fP"
.br
.ti -1c
.RI "file \fBorthonormalize\&.hpp\fP"
.br
.ti -1c
.RI "file \fBorthonormalize\&.inl\fP"
.br
.ti -1c
.RI "file \fBperpendicular\&.hpp\fP"
.br
.ti -1c
.RI "file \fBperpendicular\&.inl\fP"
.br
.ti -1c
.RI "file \fBpolar_coordinates\&.hpp\fP"
.br
.ti -1c
.RI "file \fBpolar_coordinates\&.inl\fP"
.br
.ti -1c
.RI "file \fBprojection\&.hpp\fP"
.br
.ti -1c
.RI "file \fBprojection\&.inl\fP"
.br
.ti -1c
.RI "file \fBquaternion\&.hpp\fP"
.br
.ti -1c
.RI "file \fBquaternion\&.inl\fP"
.br
.ti -1c
.RI "file \fBrange\&.hpp\fP"
.br
.ti -1c
.RI "file \fBraw_data\&.hpp\fP"
.br
.ti -1c
.RI "file \fBraw_data\&.inl\fP"
.br
.ti -1c
.RI "file \fBrotate_normalized_axis\&.hpp\fP"
.br
.ti -1c
.RI "file \fBrotate_normalized_axis\&.inl\fP"
.br
.ti -1c
.RI "file \fBrotate_vector\&.hpp\fP"
.br
.ti -1c
.RI "file \fBrotate_vector\&.inl\fP"
.br
.ti -1c
.RI "file \fBscalar_multiplication\&.hpp\fP"
.br
.RI "\fIEnables scalar multiplication for all types\&. \fP"
.ti -1c
.RI "file \fBscalar_relational\&.hpp\fP"
.br
.ti -1c
.RI "file \fBscalar_relational\&.inl\fP"
.br
.ti -1c
.RI "file \fBsimd_mat4\&.hpp\fP"
.br
.ti -1c
.RI "file \fBsimd_mat4\&.inl\fP"
.br
.ti -1c
.RI "file \fBsimd_quat\&.hpp\fP"
.br
.ti -1c
.RI "file \fBsimd_quat\&.inl\fP"
.br
.ti -1c
.RI "file \fBsimd_vec4\&.hpp\fP"
.br
.ti -1c
.RI "file \fBsimd_vec4\&.inl\fP"
.br
.ti -1c
.RI "file \fBspline\&.hpp\fP"
.br
.ti -1c
.RI "file \fBspline\&.inl\fP"
.br
.ti -1c
.RI "file \fBstd_based_type\&.hpp\fP"
.br
.ti -1c
.RI "file \fBstd_based_type\&.inl\fP"
.br
.ti -1c
.RI "file \fBstring_cast\&.hpp\fP"
.br
.ti -1c
.RI "file \fBstring_cast\&.inl\fP"
.br
.ti -1c
.RI "file \fBtransform\&.hpp\fP"
.br
.ti -1c
.RI "file \fBtransform\&.inl\fP"
.br
.ti -1c
.RI "file \fBtransform2\&.hpp\fP"
.br
.ti -1c
.RI "file \fBtransform2\&.inl\fP"
.br
.ti -1c
.RI "file \fBtype_aligned\&.hpp\fP"
.br
.ti -1c
.RI "file \fBtype_aligned\&.inl\fP"
.br
.ti -1c
.RI "file \fBvector_angle\&.hpp\fP"
.br
.ti -1c
.RI "file \fBvector_angle\&.inl\fP"
.br
.ti -1c
.RI "file \fBvector_query\&.hpp\fP"
.br
.ti -1c
.RI "file \fBvector_query\&.inl\fP"
.br
.ti -1c
.RI "file \fBwrap\&.hpp\fP"
.br
.ti -1c
.RI "file \fBwrap\&.inl\fP"
.br
.in -1c
