.TH "F:/Fusion3D_work/src/components/freeMove.h" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/Fusion3D_work/src/components/freeMove.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./core/math3d\&.h'\fP
.br
\fC#include '\&.\&./core/entityComponent\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFREEMOVE_H\fP   'Freemove'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBFreeMove\fP (float \fBspeed\fP=10\&.0f, int forwardKey=Input::KEY_W, int backKey=Input::KEY_S, int leftKey=Input::KEY_A, int rightKey=Input::KEY_D)"
.br
.ti -1c
.RI "virtual void \fBProcessInput\fP (const \fBInput\fP &input, float delta)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "float \fBm_speed\fP"
.br
.ti -1c
.RI "int \fBm_forwardKey\fP"
.br
.ti -1c
.RI "int \fBm_backKey\fP"
.br
.ti -1c
.RI "int \fBm_leftKey\fP"
.br
.ti -1c
.RI "int \fBm_rightKey\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define FREEMOVE_H   'Freemove'"

.SH "Function Documentation"
.PP 
.SS "FreeMove (float speed = \fC10\&.0f\fP, int forwardKey = \fC\fBInput::KEY_W\fP\fP, int backKey = \fC\fBInput::KEY_S\fP\fP, int leftKey = \fC\fBInput::KEY_A\fP\fP, int rightKey = \fC\fBInput::KEY_D\fP\fP)"

.SS "virtual void ProcessInput (const \fBInput\fP & input, float delta)\fC [virtual]\fP"

.SH "Variable Documentation"
.PP 
.SS "int m_backKey"

.SS "int m_forwardKey"

.SS "int m_leftKey"

.SS "int m_rightKey"

.SS "float m_speed"

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
