.TH "F:/Fusion3D_work/src/staticLibs/glm/fwd.hpp" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/Fusion3D_work/src/staticLibs/glm/fwd.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'detail/type_int\&.hpp'\fP
.br
\fC#include 'detail/type_float\&.hpp'\fP
.br
\fC#include 'detail/type_vec\&.hpp'\fP
.br
\fC#include 'detail/type_mat\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBglm::tquat< T, P >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef tquat< float, lowp > \fBglm::lowp_quat\fP"
.br
.ti -1c
.RI "typedef tquat< float, mediump > \fBglm::mediump_quat\fP"
.br
.ti -1c
.RI "typedef tquat< float, highp > \fBglm::highp_quat\fP"
.br
.ti -1c
.RI "typedef highp_quat \fBglm::quat\fP"
.br
.RI "\fI\fBQuaternion\fP of default single-precision floating-point numbers\&. \fP"
.ti -1c
.RI "typedef lowp_quat \fBglm::lowp_fquat\fP"
.br
.ti -1c
.RI "typedef mediump_quat \fBglm::mediump_fquat\fP"
.br
.ti -1c
.RI "typedef highp_quat \fBglm::highp_fquat\fP"
.br
.ti -1c
.RI "typedef quat \fBglm::fquat\fP"
.br
.ti -1c
.RI "typedef tquat< double, lowp > \fBglm::lowp_dquat\fP"
.br
.ti -1c
.RI "typedef tquat< double, mediump > \fBglm::mediump_dquat\fP"
.br
.ti -1c
.RI "typedef tquat< double, highp > \fBglm::highp_dquat\fP"
.br
.ti -1c
.RI "typedef highp_dquat \fBglm::dquat\fP"
.br
.ti -1c
.RI "typedef detail::int8 \fBglm::lowp_int8\fP"
.br
.ti -1c
.RI "typedef \fBdetail::int16\fP \fBglm::lowp_int16\fP"
.br
.ti -1c
.RI "typedef \fBdetail::int32\fP \fBglm::lowp_int32\fP"
.br
.ti -1c
.RI "typedef detail::int64 \fBglm::lowp_int64\fP"
.br
.ti -1c
.RI "typedef detail::int8 \fBglm::lowp_int8_t\fP"
.br
.ti -1c
.RI "typedef \fBdetail::int16\fP \fBglm::lowp_int16_t\fP"
.br
.ti -1c
.RI "typedef \fBdetail::int32\fP \fBglm::lowp_int32_t\fP"
.br
.ti -1c
.RI "typedef detail::int64 \fBglm::lowp_int64_t\fP"
.br
.ti -1c
.RI "typedef detail::int8 \fBglm::lowp_i8\fP"
.br
.ti -1c
.RI "typedef \fBdetail::int16\fP \fBglm::lowp_i16\fP"
.br
.ti -1c
.RI "typedef \fBdetail::int32\fP \fBglm::lowp_i32\fP"
.br
.ti -1c
.RI "typedef detail::int64 \fBglm::lowp_i64\fP"
.br
.ti -1c
.RI "typedef detail::int8 \fBglm::mediump_int8\fP"
.br
.ti -1c
.RI "typedef \fBdetail::int16\fP \fBglm::mediump_int16\fP"
.br
.ti -1c
.RI "typedef \fBdetail::int32\fP \fBglm::mediump_int32\fP"
.br
.ti -1c
.RI "typedef detail::int64 \fBglm::mediump_int64\fP"
.br
.ti -1c
.RI "typedef detail::int8 \fBglm::mediump_int8_t\fP"
.br
.ti -1c
.RI "typedef \fBdetail::int16\fP \fBglm::mediump_int16_t\fP"
.br
.ti -1c
.RI "typedef \fBdetail::int32\fP \fBglm::mediump_int32_t\fP"
.br
.ti -1c
.RI "typedef detail::int64 \fBglm::mediump_int64_t\fP"
.br
.ti -1c
.RI "typedef detail::int8 \fBglm::mediump_i8\fP"
.br
.ti -1c
.RI "typedef \fBdetail::int16\fP \fBglm::mediump_i16\fP"
.br
.ti -1c
.RI "typedef \fBdetail::int32\fP \fBglm::mediump_i32\fP"
.br
.ti -1c
.RI "typedef detail::int64 \fBglm::mediump_i64\fP"
.br
.ti -1c
.RI "typedef detail::int8 \fBglm::highp_int8\fP"
.br
.ti -1c
.RI "typedef \fBdetail::int16\fP \fBglm::highp_int16\fP"
.br
.ti -1c
.RI "typedef \fBdetail::int32\fP \fBglm::highp_int32\fP"
.br
.ti -1c
.RI "typedef detail::int64 \fBglm::highp_int64\fP"
.br
.ti -1c
.RI "typedef detail::int8 \fBglm::highp_int8_t\fP"
.br
.ti -1c
.RI "typedef \fBdetail::int16\fP \fBglm::highp_int16_t\fP"
.br
.ti -1c
.RI "typedef \fBdetail::int32\fP \fBglm::highp_int32_t\fP"
.br
.ti -1c
.RI "typedef detail::int64 \fBglm::highp_int64_t\fP"
.br
.ti -1c
.RI "typedef detail::int8 \fBglm::highp_i8\fP"
.br
.ti -1c
.RI "typedef \fBdetail::int16\fP \fBglm::highp_i16\fP"
.br
.ti -1c
.RI "typedef \fBdetail::int32\fP \fBglm::highp_i32\fP"
.br
.ti -1c
.RI "typedef detail::int64 \fBglm::highp_i64\fP"
.br
.ti -1c
.RI "typedef detail::int8 \fBglm::int8\fP"
.br
.ti -1c
.RI "typedef detail::int16 \fBglm::int16\fP"
.br
.ti -1c
.RI "typedef detail::int32 \fBglm::int32\fP"
.br
.ti -1c
.RI "typedef detail::int64 \fBglm::int64\fP"
.br
.ti -1c
.RI "typedef detail::int8 \fBglm::int8_t\fP"
.br
.ti -1c
.RI "typedef \fBdetail::int16\fP \fBglm::int16_t\fP"
.br
.ti -1c
.RI "typedef \fBdetail::int32\fP \fBglm::int32_t\fP"
.br
.ti -1c
.RI "typedef detail::int64 \fBglm::int64_t\fP"
.br
.ti -1c
.RI "typedef detail::int8 \fBglm::i8\fP"
.br
.ti -1c
.RI "typedef \fBdetail::int16\fP \fBglm::i16\fP"
.br
.ti -1c
.RI "typedef \fBdetail::int32\fP \fBglm::i32\fP"
.br
.ti -1c
.RI "typedef detail::int64 \fBglm::i64\fP"
.br
.ti -1c
.RI "typedef tvec1< i8, lowp > \fBglm::lowp_i8vec1\fP"
.br
.ti -1c
.RI "typedef tvec2< i8, lowp > \fBglm::lowp_i8vec2\fP"
.br
.ti -1c
.RI "typedef tvec3< i8, lowp > \fBglm::lowp_i8vec3\fP"
.br
.ti -1c
.RI "typedef tvec4< i8, lowp > \fBglm::lowp_i8vec4\fP"
.br
.ti -1c
.RI "typedef tvec1< i8, mediump > \fBglm::mediump_i8vec1\fP"
.br
.ti -1c
.RI "typedef tvec2< i8, mediump > \fBglm::mediump_i8vec2\fP"
.br
.ti -1c
.RI "typedef tvec3< i8, mediump > \fBglm::mediump_i8vec3\fP"
.br
.ti -1c
.RI "typedef tvec4< i8, mediump > \fBglm::mediump_i8vec4\fP"
.br
.ti -1c
.RI "typedef tvec1< i8, highp > \fBglm::highp_i8vec1\fP"
.br
.ti -1c
.RI "typedef tvec2< i8, highp > \fBglm::highp_i8vec2\fP"
.br
.ti -1c
.RI "typedef tvec3< i8, highp > \fBglm::highp_i8vec3\fP"
.br
.ti -1c
.RI "typedef tvec4< i8, highp > \fBglm::highp_i8vec4\fP"
.br
.ti -1c
.RI "typedef highp_i8vec1 \fBglm::i8vec1\fP"
.br
.ti -1c
.RI "typedef highp_i8vec2 \fBglm::i8vec2\fP"
.br
.ti -1c
.RI "typedef highp_i8vec3 \fBglm::i8vec3\fP"
.br
.ti -1c
.RI "typedef highp_i8vec4 \fBglm::i8vec4\fP"
.br
.ti -1c
.RI "typedef tvec1< i16, lowp > \fBglm::lowp_i16vec1\fP"
.br
.ti -1c
.RI "typedef tvec2< i16, lowp > \fBglm::lowp_i16vec2\fP"
.br
.ti -1c
.RI "typedef tvec3< i16, lowp > \fBglm::lowp_i16vec3\fP"
.br
.ti -1c
.RI "typedef tvec4< i16, lowp > \fBglm::lowp_i16vec4\fP"
.br
.ti -1c
.RI "typedef tvec1< i16, mediump > \fBglm::mediump_i16vec1\fP"
.br
.ti -1c
.RI "typedef tvec2< i16, mediump > \fBglm::mediump_i16vec2\fP"
.br
.ti -1c
.RI "typedef tvec3< i16, mediump > \fBglm::mediump_i16vec3\fP"
.br
.ti -1c
.RI "typedef tvec4< i16, mediump > \fBglm::mediump_i16vec4\fP"
.br
.ti -1c
.RI "typedef tvec1< i16, highp > \fBglm::highp_i16vec1\fP"
.br
.ti -1c
.RI "typedef tvec2< i16, highp > \fBglm::highp_i16vec2\fP"
.br
.ti -1c
.RI "typedef tvec3< i16, highp > \fBglm::highp_i16vec3\fP"
.br
.ti -1c
.RI "typedef tvec4< i16, highp > \fBglm::highp_i16vec4\fP"
.br
.ti -1c
.RI "typedef highp_i16vec1 \fBglm::i16vec1\fP"
.br
.ti -1c
.RI "typedef highp_i16vec2 \fBglm::i16vec2\fP"
.br
.ti -1c
.RI "typedef highp_i16vec3 \fBglm::i16vec3\fP"
.br
.ti -1c
.RI "typedef highp_i16vec4 \fBglm::i16vec4\fP"
.br
.ti -1c
.RI "typedef tvec1< i32, lowp > \fBglm::lowp_i32vec1\fP"
.br
.ti -1c
.RI "typedef tvec2< i32, lowp > \fBglm::lowp_i32vec2\fP"
.br
.ti -1c
.RI "typedef tvec3< i32, lowp > \fBglm::lowp_i32vec3\fP"
.br
.ti -1c
.RI "typedef tvec4< i32, lowp > \fBglm::lowp_i32vec4\fP"
.br
.ti -1c
.RI "typedef tvec1< i32, mediump > \fBglm::mediump_i32vec1\fP"
.br
.ti -1c
.RI "typedef tvec2< i32, mediump > \fBglm::mediump_i32vec2\fP"
.br
.ti -1c
.RI "typedef tvec3< i32, mediump > \fBglm::mediump_i32vec3\fP"
.br
.ti -1c
.RI "typedef tvec4< i32, mediump > \fBglm::mediump_i32vec4\fP"
.br
.ti -1c
.RI "typedef tvec1< i32, highp > \fBglm::highp_i32vec1\fP"
.br
.ti -1c
.RI "typedef tvec2< i32, highp > \fBglm::highp_i32vec2\fP"
.br
.ti -1c
.RI "typedef tvec3< i32, highp > \fBglm::highp_i32vec3\fP"
.br
.ti -1c
.RI "typedef tvec4< i32, highp > \fBglm::highp_i32vec4\fP"
.br
.ti -1c
.RI "typedef highp_i32vec1 \fBglm::i32vec1\fP"
.br
.ti -1c
.RI "typedef highp_i32vec2 \fBglm::i32vec2\fP"
.br
.ti -1c
.RI "typedef highp_i32vec3 \fBglm::i32vec3\fP"
.br
.ti -1c
.RI "typedef highp_i32vec4 \fBglm::i32vec4\fP"
.br
.ti -1c
.RI "typedef tvec1< i64, lowp > \fBglm::lowp_i64vec1\fP"
.br
.ti -1c
.RI "typedef tvec2< i64, lowp > \fBglm::lowp_i64vec2\fP"
.br
.ti -1c
.RI "typedef tvec3< i64, lowp > \fBglm::lowp_i64vec3\fP"
.br
.ti -1c
.RI "typedef tvec4< i64, lowp > \fBglm::lowp_i64vec4\fP"
.br
.ti -1c
.RI "typedef tvec1< i64, mediump > \fBglm::mediump_i64vec1\fP"
.br
.ti -1c
.RI "typedef tvec2< i64, mediump > \fBglm::mediump_i64vec2\fP"
.br
.ti -1c
.RI "typedef tvec3< i64, mediump > \fBglm::mediump_i64vec3\fP"
.br
.ti -1c
.RI "typedef tvec4< i64, mediump > \fBglm::mediump_i64vec4\fP"
.br
.ti -1c
.RI "typedef tvec1< i64, highp > \fBglm::highp_i64vec1\fP"
.br
.ti -1c
.RI "typedef tvec2< i64, highp > \fBglm::highp_i64vec2\fP"
.br
.ti -1c
.RI "typedef tvec3< i64, highp > \fBglm::highp_i64vec3\fP"
.br
.ti -1c
.RI "typedef tvec4< i64, highp > \fBglm::highp_i64vec4\fP"
.br
.ti -1c
.RI "typedef highp_i64vec1 \fBglm::i64vec1\fP"
.br
.ti -1c
.RI "typedef highp_i64vec2 \fBglm::i64vec2\fP"
.br
.ti -1c
.RI "typedef highp_i64vec3 \fBglm::i64vec3\fP"
.br
.ti -1c
.RI "typedef highp_i64vec4 \fBglm::i64vec4\fP"
.br
.ti -1c
.RI "typedef \fBdetail::uint8\fP \fBglm::lowp_uint8\fP"
.br
.ti -1c
.RI "typedef \fBdetail::uint16\fP \fBglm::lowp_uint16\fP"
.br
.ti -1c
.RI "typedef \fBdetail::uint32\fP \fBglm::lowp_uint32\fP"
.br
.ti -1c
.RI "typedef detail::uint64 \fBglm::lowp_uint64\fP"
.br
.ti -1c
.RI "typedef \fBdetail::uint8\fP \fBglm::lowp_uint8_t\fP"
.br
.ti -1c
.RI "typedef \fBdetail::uint16\fP \fBglm::lowp_uint16_t\fP"
.br
.ti -1c
.RI "typedef \fBdetail::uint32\fP \fBglm::lowp_uint32_t\fP"
.br
.ti -1c
.RI "typedef detail::uint64 \fBglm::lowp_uint64_t\fP"
.br
.ti -1c
.RI "typedef \fBdetail::uint8\fP \fBglm::lowp_u8\fP"
.br
.ti -1c
.RI "typedef \fBdetail::uint16\fP \fBglm::lowp_u16\fP"
.br
.ti -1c
.RI "typedef \fBdetail::uint32\fP \fBglm::lowp_u32\fP"
.br
.ti -1c
.RI "typedef detail::uint64 \fBglm::lowp_u64\fP"
.br
.ti -1c
.RI "typedef \fBdetail::uint8\fP \fBglm::mediump_uint8\fP"
.br
.ti -1c
.RI "typedef \fBdetail::uint16\fP \fBglm::mediump_uint16\fP"
.br
.ti -1c
.RI "typedef \fBdetail::uint32\fP \fBglm::mediump_uint32\fP"
.br
.ti -1c
.RI "typedef detail::uint64 \fBglm::mediump_uint64\fP"
.br
.ti -1c
.RI "typedef \fBdetail::uint8\fP \fBglm::mediump_uint8_t\fP"
.br
.ti -1c
.RI "typedef \fBdetail::uint16\fP \fBglm::mediump_uint16_t\fP"
.br
.ti -1c
.RI "typedef \fBdetail::uint32\fP \fBglm::mediump_uint32_t\fP"
.br
.ti -1c
.RI "typedef detail::uint64 \fBglm::mediump_uint64_t\fP"
.br
.ti -1c
.RI "typedef \fBdetail::uint8\fP \fBglm::mediump_u8\fP"
.br
.ti -1c
.RI "typedef \fBdetail::uint16\fP \fBglm::mediump_u16\fP"
.br
.ti -1c
.RI "typedef \fBdetail::uint32\fP \fBglm::mediump_u32\fP"
.br
.ti -1c
.RI "typedef detail::uint64 \fBglm::mediump_u64\fP"
.br
.ti -1c
.RI "typedef \fBdetail::uint8\fP \fBglm::highp_uint8\fP"
.br
.ti -1c
.RI "typedef \fBdetail::uint16\fP \fBglm::highp_uint16\fP"
.br
.ti -1c
.RI "typedef \fBdetail::uint32\fP \fBglm::highp_uint32\fP"
.br
.ti -1c
.RI "typedef detail::uint64 \fBglm::highp_uint64\fP"
.br
.ti -1c
.RI "typedef \fBdetail::uint8\fP \fBglm::highp_uint8_t\fP"
.br
.ti -1c
.RI "typedef \fBdetail::uint16\fP \fBglm::highp_uint16_t\fP"
.br
.ti -1c
.RI "typedef \fBdetail::uint32\fP \fBglm::highp_uint32_t\fP"
.br
.ti -1c
.RI "typedef detail::uint64 \fBglm::highp_uint64_t\fP"
.br
.ti -1c
.RI "typedef \fBdetail::uint8\fP \fBglm::highp_u8\fP"
.br
.ti -1c
.RI "typedef \fBdetail::uint16\fP \fBglm::highp_u16\fP"
.br
.ti -1c
.RI "typedef \fBdetail::uint32\fP \fBglm::highp_u32\fP"
.br
.ti -1c
.RI "typedef detail::uint64 \fBglm::highp_u64\fP"
.br
.ti -1c
.RI "typedef detail::uint8 \fBglm::uint8\fP"
.br
.ti -1c
.RI "typedef detail::uint16 \fBglm::uint16\fP"
.br
.ti -1c
.RI "typedef detail::uint32 \fBglm::uint32\fP"
.br
.ti -1c
.RI "typedef detail::uint64 \fBglm::uint64\fP"
.br
.ti -1c
.RI "typedef \fBdetail::uint8\fP \fBglm::uint8_t\fP"
.br
.ti -1c
.RI "typedef \fBdetail::uint16\fP \fBglm::uint16_t\fP"
.br
.ti -1c
.RI "typedef \fBdetail::uint32\fP \fBglm::uint32_t\fP"
.br
.ti -1c
.RI "typedef detail::uint64 \fBglm::uint64_t\fP"
.br
.ti -1c
.RI "typedef \fBdetail::uint8\fP \fBglm::u8\fP"
.br
.ti -1c
.RI "typedef \fBdetail::uint16\fP \fBglm::u16\fP"
.br
.ti -1c
.RI "typedef \fBdetail::uint32\fP \fBglm::u32\fP"
.br
.ti -1c
.RI "typedef detail::uint64 \fBglm::u64\fP"
.br
.ti -1c
.RI "typedef tvec1< u8, lowp > \fBglm::lowp_u8vec1\fP"
.br
.ti -1c
.RI "typedef tvec2< u8, lowp > \fBglm::lowp_u8vec2\fP"
.br
.ti -1c
.RI "typedef tvec3< u8, lowp > \fBglm::lowp_u8vec3\fP"
.br
.ti -1c
.RI "typedef tvec4< u8, lowp > \fBglm::lowp_u8vec4\fP"
.br
.ti -1c
.RI "typedef tvec1< u8, mediump > \fBglm::mediump_u8vec1\fP"
.br
.ti -1c
.RI "typedef tvec2< u8, mediump > \fBglm::mediump_u8vec2\fP"
.br
.ti -1c
.RI "typedef tvec3< u8, mediump > \fBglm::mediump_u8vec3\fP"
.br
.ti -1c
.RI "typedef tvec4< u8, mediump > \fBglm::mediump_u8vec4\fP"
.br
.ti -1c
.RI "typedef tvec1< u8, highp > \fBglm::highp_u8vec1\fP"
.br
.ti -1c
.RI "typedef tvec2< u8, highp > \fBglm::highp_u8vec2\fP"
.br
.ti -1c
.RI "typedef tvec3< u8, highp > \fBglm::highp_u8vec3\fP"
.br
.ti -1c
.RI "typedef tvec4< u8, highp > \fBglm::highp_u8vec4\fP"
.br
.ti -1c
.RI "typedef highp_u8vec1 \fBglm::u8vec1\fP"
.br
.ti -1c
.RI "typedef highp_u8vec2 \fBglm::u8vec2\fP"
.br
.ti -1c
.RI "typedef highp_u8vec3 \fBglm::u8vec3\fP"
.br
.ti -1c
.RI "typedef highp_u8vec4 \fBglm::u8vec4\fP"
.br
.ti -1c
.RI "typedef tvec1< u16, lowp > \fBglm::lowp_u16vec1\fP"
.br
.ti -1c
.RI "typedef tvec2< u16, lowp > \fBglm::lowp_u16vec2\fP"
.br
.ti -1c
.RI "typedef tvec3< u16, lowp > \fBglm::lowp_u16vec3\fP"
.br
.ti -1c
.RI "typedef tvec4< u16, lowp > \fBglm::lowp_u16vec4\fP"
.br
.ti -1c
.RI "typedef tvec1< u16, mediump > \fBglm::mediump_u16vec1\fP"
.br
.ti -1c
.RI "typedef tvec2< u16, mediump > \fBglm::mediump_u16vec2\fP"
.br
.ti -1c
.RI "typedef tvec3< u16, mediump > \fBglm::mediump_u16vec3\fP"
.br
.ti -1c
.RI "typedef tvec4< u16, mediump > \fBglm::mediump_u16vec4\fP"
.br
.ti -1c
.RI "typedef tvec1< u16, highp > \fBglm::highp_u16vec1\fP"
.br
.ti -1c
.RI "typedef tvec2< u16, highp > \fBglm::highp_u16vec2\fP"
.br
.ti -1c
.RI "typedef tvec3< u16, highp > \fBglm::highp_u16vec3\fP"
.br
.ti -1c
.RI "typedef tvec4< u16, highp > \fBglm::highp_u16vec4\fP"
.br
.ti -1c
.RI "typedef highp_u16vec1 \fBglm::u16vec1\fP"
.br
.ti -1c
.RI "typedef highp_u16vec2 \fBglm::u16vec2\fP"
.br
.ti -1c
.RI "typedef highp_u16vec3 \fBglm::u16vec3\fP"
.br
.ti -1c
.RI "typedef highp_u16vec4 \fBglm::u16vec4\fP"
.br
.ti -1c
.RI "typedef tvec1< u32, lowp > \fBglm::lowp_u32vec1\fP"
.br
.ti -1c
.RI "typedef tvec2< u32, lowp > \fBglm::lowp_u32vec2\fP"
.br
.ti -1c
.RI "typedef tvec3< u32, lowp > \fBglm::lowp_u32vec3\fP"
.br
.ti -1c
.RI "typedef tvec4< u32, lowp > \fBglm::lowp_u32vec4\fP"
.br
.ti -1c
.RI "typedef tvec1< u32, mediump > \fBglm::mediump_u32vec1\fP"
.br
.ti -1c
.RI "typedef tvec2< u32, mediump > \fBglm::mediump_u32vec2\fP"
.br
.ti -1c
.RI "typedef tvec3< u32, mediump > \fBglm::mediump_u32vec3\fP"
.br
.ti -1c
.RI "typedef tvec4< u32, mediump > \fBglm::mediump_u32vec4\fP"
.br
.ti -1c
.RI "typedef tvec1< u32, highp > \fBglm::highp_u32vec1\fP"
.br
.ti -1c
.RI "typedef tvec2< u32, highp > \fBglm::highp_u32vec2\fP"
.br
.ti -1c
.RI "typedef tvec3< u32, highp > \fBglm::highp_u32vec3\fP"
.br
.ti -1c
.RI "typedef tvec4< u32, highp > \fBglm::highp_u32vec4\fP"
.br
.ti -1c
.RI "typedef highp_u32vec1 \fBglm::u32vec1\fP"
.br
.ti -1c
.RI "typedef highp_u32vec2 \fBglm::u32vec2\fP"
.br
.ti -1c
.RI "typedef highp_u32vec3 \fBglm::u32vec3\fP"
.br
.ti -1c
.RI "typedef highp_u32vec4 \fBglm::u32vec4\fP"
.br
.ti -1c
.RI "typedef tvec1< u64, lowp > \fBglm::lowp_u64vec1\fP"
.br
.ti -1c
.RI "typedef tvec2< u64, lowp > \fBglm::lowp_u64vec2\fP"
.br
.ti -1c
.RI "typedef tvec3< u64, lowp > \fBglm::lowp_u64vec3\fP"
.br
.ti -1c
.RI "typedef tvec4< u64, lowp > \fBglm::lowp_u64vec4\fP"
.br
.ti -1c
.RI "typedef tvec1< u64, mediump > \fBglm::mediump_u64vec1\fP"
.br
.ti -1c
.RI "typedef tvec2< u64, mediump > \fBglm::mediump_u64vec2\fP"
.br
.ti -1c
.RI "typedef tvec3< u64, mediump > \fBglm::mediump_u64vec3\fP"
.br
.ti -1c
.RI "typedef tvec4< u64, mediump > \fBglm::mediump_u64vec4\fP"
.br
.ti -1c
.RI "typedef tvec1< u64, highp > \fBglm::highp_u64vec1\fP"
.br
.ti -1c
.RI "typedef tvec2< u64, highp > \fBglm::highp_u64vec2\fP"
.br
.ti -1c
.RI "typedef tvec3< u64, highp > \fBglm::highp_u64vec3\fP"
.br
.ti -1c
.RI "typedef tvec4< u64, highp > \fBglm::highp_u64vec4\fP"
.br
.ti -1c
.RI "typedef highp_u64vec1 \fBglm::u64vec1\fP"
.br
.ti -1c
.RI "typedef highp_u64vec2 \fBglm::u64vec2\fP"
.br
.ti -1c
.RI "typedef highp_u64vec3 \fBglm::u64vec3\fP"
.br
.ti -1c
.RI "typedef highp_u64vec4 \fBglm::u64vec4\fP"
.br
.ti -1c
.RI "typedef detail::float32 \fBglm::lowp_float32\fP"
.br
.ti -1c
.RI "typedef detail::float64 \fBglm::lowp_float64\fP"
.br
.ti -1c
.RI "typedef detail::float32 \fBglm::lowp_float32_t\fP"
.br
.ti -1c
.RI "typedef detail::float64 \fBglm::lowp_float64_t\fP"
.br
.ti -1c
.RI "typedef float32 \fBglm::lowp_f32\fP"
.br
.ti -1c
.RI "typedef float64 \fBglm::lowp_f64\fP"
.br
.ti -1c
.RI "typedef detail::float32 \fBglm::mediump_float32\fP"
.br
.ti -1c
.RI "typedef detail::float64 \fBglm::mediump_float64\fP"
.br
.ti -1c
.RI "typedef detail::float32 \fBglm::mediump_float32_t\fP"
.br
.ti -1c
.RI "typedef detail::float64 \fBglm::mediump_float64_t\fP"
.br
.ti -1c
.RI "typedef float32 \fBglm::mediump_f32\fP"
.br
.ti -1c
.RI "typedef float64 \fBglm::mediump_f64\fP"
.br
.ti -1c
.RI "typedef detail::float32 \fBglm::highp_float32\fP"
.br
.ti -1c
.RI "typedef detail::float64 \fBglm::highp_float64\fP"
.br
.ti -1c
.RI "typedef detail::float32 \fBglm::highp_float32_t\fP"
.br
.ti -1c
.RI "typedef detail::float64 \fBglm::highp_float64_t\fP"
.br
.ti -1c
.RI "typedef float32 \fBglm::highp_f32\fP"
.br
.ti -1c
.RI "typedef float64 \fBglm::highp_f64\fP"
.br
.ti -1c
.RI "typedef highp_float32 \fBglm::float32\fP"
.br
.ti -1c
.RI "typedef highp_float64 \fBglm::float64\fP"
.br
.ti -1c
.RI "typedef highp_float32_t \fBglm::float32_t\fP"
.br
.ti -1c
.RI "typedef highp_float64_t \fBglm::float64_t\fP"
.br
.ti -1c
.RI "typedef highp_float32_t \fBglm::f32\fP"
.br
.ti -1c
.RI "typedef highp_float64_t \fBglm::f64\fP"
.br
.ti -1c
.RI "typedef tvec1< float, lowp > \fBglm::lowp_vec1\fP"
.br
.ti -1c
.RI "typedef tvec2< float, lowp > \fBglm::lowp_vec2\fP"
.br
.ti -1c
.RI "typedef tvec3< float, lowp > \fBglm::lowp_vec3\fP"
.br
.ti -1c
.RI "typedef tvec4< float, lowp > \fBglm::lowp_vec4\fP"
.br
.ti -1c
.RI "typedef tvec1< float, lowp > \fBglm::lowp_fvec1\fP"
.br
.ti -1c
.RI "typedef tvec2< float, lowp > \fBglm::lowp_fvec2\fP"
.br
.ti -1c
.RI "typedef tvec3< float, lowp > \fBglm::lowp_fvec3\fP"
.br
.ti -1c
.RI "typedef tvec4< float, lowp > \fBglm::lowp_fvec4\fP"
.br
.ti -1c
.RI "typedef tvec1< float, mediump > \fBglm::mediump_vec1\fP"
.br
.ti -1c
.RI "typedef tvec2< float, mediump > \fBglm::mediump_vec2\fP"
.br
.ti -1c
.RI "typedef tvec3< float, mediump > \fBglm::mediump_vec3\fP"
.br
.ti -1c
.RI "typedef tvec4< float, mediump > \fBglm::mediump_vec4\fP"
.br
.ti -1c
.RI "typedef tvec1< float, mediump > \fBglm::mediump_fvec1\fP"
.br
.ti -1c
.RI "typedef tvec2< float, mediump > \fBglm::mediump_fvec2\fP"
.br
.ti -1c
.RI "typedef tvec3< float, mediump > \fBglm::mediump_fvec3\fP"
.br
.ti -1c
.RI "typedef tvec4< float, mediump > \fBglm::mediump_fvec4\fP"
.br
.ti -1c
.RI "typedef tvec1< float, highp > \fBglm::highp_vec1\fP"
.br
.ti -1c
.RI "typedef tvec2< float, highp > \fBglm::highp_vec2\fP"
.br
.ti -1c
.RI "typedef tvec3< float, highp > \fBglm::highp_vec3\fP"
.br
.ti -1c
.RI "typedef tvec4< float, highp > \fBglm::highp_vec4\fP"
.br
.ti -1c
.RI "typedef tvec1< float, highp > \fBglm::highp_fvec1\fP"
.br
.ti -1c
.RI "typedef tvec2< float, highp > \fBglm::highp_fvec2\fP"
.br
.ti -1c
.RI "typedef tvec3< float, highp > \fBglm::highp_fvec3\fP"
.br
.ti -1c
.RI "typedef tvec4< float, highp > \fBglm::highp_fvec4\fP"
.br
.ti -1c
.RI "typedef tvec1< f32, lowp > \fBglm::lowp_f32vec1\fP"
.br
.ti -1c
.RI "typedef tvec2< f32, lowp > \fBglm::lowp_f32vec2\fP"
.br
.ti -1c
.RI "typedef tvec3< f32, lowp > \fBglm::lowp_f32vec3\fP"
.br
.ti -1c
.RI "typedef tvec4< f32, lowp > \fBglm::lowp_f32vec4\fP"
.br
.ti -1c
.RI "typedef tvec1< f32, mediump > \fBglm::mediump_f32vec1\fP"
.br
.ti -1c
.RI "typedef tvec2< f32, mediump > \fBglm::mediump_f32vec2\fP"
.br
.ti -1c
.RI "typedef tvec3< f32, mediump > \fBglm::mediump_f32vec3\fP"
.br
.ti -1c
.RI "typedef tvec4< f32, mediump > \fBglm::mediump_f32vec4\fP"
.br
.ti -1c
.RI "typedef tvec1< f32, highp > \fBglm::highp_f32vec1\fP"
.br
.ti -1c
.RI "typedef tvec2< f32, highp > \fBglm::highp_f32vec2\fP"
.br
.ti -1c
.RI "typedef tvec3< f32, highp > \fBglm::highp_f32vec3\fP"
.br
.ti -1c
.RI "typedef tvec4< f32, highp > \fBglm::highp_f32vec4\fP"
.br
.ti -1c
.RI "typedef tvec1< f64, lowp > \fBglm::lowp_f64vec1\fP"
.br
.ti -1c
.RI "typedef tvec2< f64, lowp > \fBglm::lowp_f64vec2\fP"
.br
.ti -1c
.RI "typedef tvec3< f64, lowp > \fBglm::lowp_f64vec3\fP"
.br
.ti -1c
.RI "typedef tvec4< f64, lowp > \fBglm::lowp_f64vec4\fP"
.br
.ti -1c
.RI "typedef tvec1< f64, mediump > \fBglm::mediump_f64vec1\fP"
.br
.ti -1c
.RI "typedef tvec2< f64, mediump > \fBglm::mediump_f64vec2\fP"
.br
.ti -1c
.RI "typedef tvec3< f64, mediump > \fBglm::mediump_f64vec3\fP"
.br
.ti -1c
.RI "typedef tvec4< f64, mediump > \fBglm::mediump_f64vec4\fP"
.br
.ti -1c
.RI "typedef tvec1< f64, highp > \fBglm::highp_f64vec1\fP"
.br
.ti -1c
.RI "typedef tvec2< f64, highp > \fBglm::highp_f64vec2\fP"
.br
.ti -1c
.RI "typedef tvec3< f64, highp > \fBglm::highp_f64vec3\fP"
.br
.ti -1c
.RI "typedef tvec4< f64, highp > \fBglm::highp_f64vec4\fP"
.br
.ti -1c
.RI "typedef tmat2x2< f32, lowp > \fBglm::lowp_fmat2x2\fP"
.br
.ti -1c
.RI "typedef tmat2x3< f32, lowp > \fBglm::lowp_fmat2x3\fP"
.br
.ti -1c
.RI "typedef tmat2x4< f32, lowp > \fBglm::lowp_fmat2x4\fP"
.br
.ti -1c
.RI "typedef tmat3x2< f32, lowp > \fBglm::lowp_fmat3x2\fP"
.br
.ti -1c
.RI "typedef tmat3x3< f32, lowp > \fBglm::lowp_fmat3x3\fP"
.br
.ti -1c
.RI "typedef tmat3x4< f32, lowp > \fBglm::lowp_fmat3x4\fP"
.br
.ti -1c
.RI "typedef tmat4x2< f32, lowp > \fBglm::lowp_fmat4x2\fP"
.br
.ti -1c
.RI "typedef tmat4x3< f32, lowp > \fBglm::lowp_fmat4x3\fP"
.br
.ti -1c
.RI "typedef tmat4x4< f32, lowp > \fBglm::lowp_fmat4x4\fP"
.br
.ti -1c
.RI "typedef lowp_fmat2x2 \fBglm::lowp_fmat2\fP"
.br
.ti -1c
.RI "typedef lowp_fmat3x3 \fBglm::lowp_fmat3\fP"
.br
.ti -1c
.RI "typedef lowp_fmat4x4 \fBglm::lowp_fmat4\fP"
.br
.ti -1c
.RI "typedef tmat2x2< f32, mediump > \fBglm::mediump_fmat2x2\fP"
.br
.ti -1c
.RI "typedef tmat2x3< f32, mediump > \fBglm::mediump_fmat2x3\fP"
.br
.ti -1c
.RI "typedef tmat2x4< f32, mediump > \fBglm::mediump_fmat2x4\fP"
.br
.ti -1c
.RI "typedef tmat3x2< f32, mediump > \fBglm::mediump_fmat3x2\fP"
.br
.ti -1c
.RI "typedef tmat3x3< f32, mediump > \fBglm::mediump_fmat3x3\fP"
.br
.ti -1c
.RI "typedef tmat3x4< f32, mediump > \fBglm::mediump_fmat3x4\fP"
.br
.ti -1c
.RI "typedef tmat4x2< f32, mediump > \fBglm::mediump_fmat4x2\fP"
.br
.ti -1c
.RI "typedef tmat4x3< f32, mediump > \fBglm::mediump_fmat4x3\fP"
.br
.ti -1c
.RI "typedef tmat4x4< f32, mediump > \fBglm::mediump_fmat4x4\fP"
.br
.ti -1c
.RI "typedef mediump_fmat2x2 \fBglm::mediump_fmat2\fP"
.br
.ti -1c
.RI "typedef mediump_fmat3x3 \fBglm::mediump_fmat3\fP"
.br
.ti -1c
.RI "typedef mediump_fmat4x4 \fBglm::mediump_fmat4\fP"
.br
.ti -1c
.RI "typedef tmat2x2< f32, highp > \fBglm::highp_fmat2x2\fP"
.br
.ti -1c
.RI "typedef tmat2x3< f32, highp > \fBglm::highp_fmat2x3\fP"
.br
.ti -1c
.RI "typedef tmat2x4< f32, highp > \fBglm::highp_fmat2x4\fP"
.br
.ti -1c
.RI "typedef tmat3x2< f32, highp > \fBglm::highp_fmat3x2\fP"
.br
.ti -1c
.RI "typedef tmat3x3< f32, highp > \fBglm::highp_fmat3x3\fP"
.br
.ti -1c
.RI "typedef tmat3x4< f32, highp > \fBglm::highp_fmat3x4\fP"
.br
.ti -1c
.RI "typedef tmat4x2< f32, highp > \fBglm::highp_fmat4x2\fP"
.br
.ti -1c
.RI "typedef tmat4x3< f32, highp > \fBglm::highp_fmat4x3\fP"
.br
.ti -1c
.RI "typedef tmat4x4< f32, highp > \fBglm::highp_fmat4x4\fP"
.br
.ti -1c
.RI "typedef highp_fmat2x2 \fBglm::highp_fmat2\fP"
.br
.ti -1c
.RI "typedef highp_fmat3x3 \fBglm::highp_fmat3\fP"
.br
.ti -1c
.RI "typedef highp_fmat4x4 \fBglm::highp_fmat4\fP"
.br
.ti -1c
.RI "typedef tmat2x2< f32, lowp > \fBglm::lowp_f32mat2x2\fP"
.br
.ti -1c
.RI "typedef tmat2x3< f32, lowp > \fBglm::lowp_f32mat2x3\fP"
.br
.ti -1c
.RI "typedef tmat2x4< f32, lowp > \fBglm::lowp_f32mat2x4\fP"
.br
.ti -1c
.RI "typedef tmat3x2< f32, lowp > \fBglm::lowp_f32mat3x2\fP"
.br
.ti -1c
.RI "typedef tmat3x3< f32, lowp > \fBglm::lowp_f32mat3x3\fP"
.br
.ti -1c
.RI "typedef tmat3x4< f32, lowp > \fBglm::lowp_f32mat3x4\fP"
.br
.ti -1c
.RI "typedef tmat4x2< f32, lowp > \fBglm::lowp_f32mat4x2\fP"
.br
.ti -1c
.RI "typedef tmat4x3< f32, lowp > \fBglm::lowp_f32mat4x3\fP"
.br
.ti -1c
.RI "typedef tmat4x4< f32, lowp > \fBglm::lowp_f32mat4x4\fP"
.br
.ti -1c
.RI "typedef lowp_f32mat2x2 \fBglm::lowp_f32mat2\fP"
.br
.ti -1c
.RI "typedef lowp_f32mat3x3 \fBglm::lowp_f32mat3\fP"
.br
.ti -1c
.RI "typedef lowp_f32mat4x4 \fBglm::lowp_f32mat4\fP"
.br
.ti -1c
.RI "typedef tmat2x2< f32, mediump > \fBglm::mediump_f32mat2x2\fP"
.br
.ti -1c
.RI "typedef tmat2x3< f32, mediump > \fBglm::mediump_f32mat2x3\fP"
.br
.ti -1c
.RI "typedef tmat2x4< f32, mediump > \fBglm::mediump_f32mat2x4\fP"
.br
.ti -1c
.RI "typedef tmat3x2< f32, mediump > \fBglm::mediump_f32mat3x2\fP"
.br
.ti -1c
.RI "typedef tmat3x3< f32, mediump > \fBglm::mediump_f32mat3x3\fP"
.br
.ti -1c
.RI "typedef tmat3x4< f32, mediump > \fBglm::mediump_f32mat3x4\fP"
.br
.ti -1c
.RI "typedef tmat4x2< f32, mediump > \fBglm::mediump_f32mat4x2\fP"
.br
.ti -1c
.RI "typedef tmat4x3< f32, mediump > \fBglm::mediump_f32mat4x3\fP"
.br
.ti -1c
.RI "typedef tmat4x4< f32, mediump > \fBglm::mediump_f32mat4x4\fP"
.br
.ti -1c
.RI "typedef mediump_f32mat2x2 \fBglm::mediump_f32mat2\fP"
.br
.ti -1c
.RI "typedef mediump_f32mat3x3 \fBglm::mediump_f32mat3\fP"
.br
.ti -1c
.RI "typedef mediump_f32mat4x4 \fBglm::mediump_f32mat4\fP"
.br
.ti -1c
.RI "typedef tmat2x2< f32, highp > \fBglm::highp_f32mat2x2\fP"
.br
.ti -1c
.RI "typedef tmat2x3< f32, highp > \fBglm::highp_f32mat2x3\fP"
.br
.ti -1c
.RI "typedef tmat2x4< f32, highp > \fBglm::highp_f32mat2x4\fP"
.br
.ti -1c
.RI "typedef tmat3x2< f32, highp > \fBglm::highp_f32mat3x2\fP"
.br
.ti -1c
.RI "typedef tmat3x3< f32, highp > \fBglm::highp_f32mat3x3\fP"
.br
.ti -1c
.RI "typedef tmat3x4< f32, highp > \fBglm::highp_f32mat3x4\fP"
.br
.ti -1c
.RI "typedef tmat4x2< f32, highp > \fBglm::highp_f32mat4x2\fP"
.br
.ti -1c
.RI "typedef tmat4x3< f32, highp > \fBglm::highp_f32mat4x3\fP"
.br
.ti -1c
.RI "typedef tmat4x4< f32, highp > \fBglm::highp_f32mat4x4\fP"
.br
.ti -1c
.RI "typedef highp_f32mat2x2 \fBglm::highp_f32mat2\fP"
.br
.ti -1c
.RI "typedef highp_f32mat3x3 \fBglm::highp_f32mat3\fP"
.br
.ti -1c
.RI "typedef highp_f32mat4x4 \fBglm::highp_f32mat4\fP"
.br
.ti -1c
.RI "typedef tmat2x2< f64, lowp > \fBglm::lowp_f64mat2x2\fP"
.br
.ti -1c
.RI "typedef tmat2x3< f64, lowp > \fBglm::lowp_f64mat2x3\fP"
.br
.ti -1c
.RI "typedef tmat2x4< f64, lowp > \fBglm::lowp_f64mat2x4\fP"
.br
.ti -1c
.RI "typedef tmat3x2< f64, lowp > \fBglm::lowp_f64mat3x2\fP"
.br
.ti -1c
.RI "typedef tmat3x3< f64, lowp > \fBglm::lowp_f64mat3x3\fP"
.br
.ti -1c
.RI "typedef tmat3x4< f64, lowp > \fBglm::lowp_f64mat3x4\fP"
.br
.ti -1c
.RI "typedef tmat4x2< f64, lowp > \fBglm::lowp_f64mat4x2\fP"
.br
.ti -1c
.RI "typedef tmat4x3< f64, lowp > \fBglm::lowp_f64mat4x3\fP"
.br
.ti -1c
.RI "typedef tmat4x4< f64, lowp > \fBglm::lowp_f64mat4x4\fP"
.br
.ti -1c
.RI "typedef lowp_f64mat2x2 \fBglm::lowp_f64mat2\fP"
.br
.ti -1c
.RI "typedef lowp_f64mat3x3 \fBglm::lowp_f64mat3\fP"
.br
.ti -1c
.RI "typedef lowp_f64mat4x4 \fBglm::lowp_f64mat4\fP"
.br
.ti -1c
.RI "typedef tmat2x2< f64, mediump > \fBglm::mediump_f64mat2x2\fP"
.br
.ti -1c
.RI "typedef tmat2x3< f64, mediump > \fBglm::mediump_f64mat2x3\fP"
.br
.ti -1c
.RI "typedef tmat2x4< f64, mediump > \fBglm::mediump_f64mat2x4\fP"
.br
.ti -1c
.RI "typedef tmat3x2< f64, mediump > \fBglm::mediump_f64mat3x2\fP"
.br
.ti -1c
.RI "typedef tmat3x3< f64, mediump > \fBglm::mediump_f64mat3x3\fP"
.br
.ti -1c
.RI "typedef tmat3x4< f64, mediump > \fBglm::mediump_f64mat3x4\fP"
.br
.ti -1c
.RI "typedef tmat4x2< f64, mediump > \fBglm::mediump_f64mat4x2\fP"
.br
.ti -1c
.RI "typedef tmat4x3< f64, mediump > \fBglm::mediump_f64mat4x3\fP"
.br
.ti -1c
.RI "typedef tmat4x4< f64, mediump > \fBglm::mediump_f64mat4x4\fP"
.br
.ti -1c
.RI "typedef mediump_f64mat2x2 \fBglm::mediump_f64mat2\fP"
.br
.ti -1c
.RI "typedef mediump_f64mat3x3 \fBglm::mediump_f64mat3\fP"
.br
.ti -1c
.RI "typedef mediump_f64mat4x4 \fBglm::mediump_f64mat4\fP"
.br
.ti -1c
.RI "typedef tmat2x2< f64, highp > \fBglm::highp_f64mat2x2\fP"
.br
.ti -1c
.RI "typedef tmat2x3< f64, highp > \fBglm::highp_f64mat2x3\fP"
.br
.ti -1c
.RI "typedef tmat2x4< f64, highp > \fBglm::highp_f64mat2x4\fP"
.br
.ti -1c
.RI "typedef tmat3x2< f64, highp > \fBglm::highp_f64mat3x2\fP"
.br
.ti -1c
.RI "typedef tmat3x3< f64, highp > \fBglm::highp_f64mat3x3\fP"
.br
.ti -1c
.RI "typedef tmat3x4< f64, highp > \fBglm::highp_f64mat3x4\fP"
.br
.ti -1c
.RI "typedef tmat4x2< f64, highp > \fBglm::highp_f64mat4x2\fP"
.br
.ti -1c
.RI "typedef tmat4x3< f64, highp > \fBglm::highp_f64mat4x3\fP"
.br
.ti -1c
.RI "typedef tmat4x4< f64, highp > \fBglm::highp_f64mat4x4\fP"
.br
.ti -1c
.RI "typedef highp_f64mat2x2 \fBglm::highp_f64mat2\fP"
.br
.ti -1c
.RI "typedef highp_f64mat3x3 \fBglm::highp_f64mat3\fP"
.br
.ti -1c
.RI "typedef highp_f64mat4x4 \fBglm::highp_f64mat4\fP"
.br
.ti -1c
.RI "typedef tquat< f32, lowp > \fBglm::lowp_f32quat\fP"
.br
.ti -1c
.RI "typedef tquat< f64, lowp > \fBglm::lowp_f64quat\fP"
.br
.ti -1c
.RI "typedef tquat< f32, mediump > \fBglm::mediump_f32quat\fP"
.br
.ti -1c
.RI "typedef tquat< f64, mediump > \fBglm::mediump_f64quat\fP"
.br
.ti -1c
.RI "typedef tquat< f32, highp > \fBglm::highp_f32quat\fP"
.br
.ti -1c
.RI "typedef tquat< f64, highp > \fBglm::highp_f64quat\fP"
.br
.ti -1c
.RI "typedef highp_f32vec1 \fBglm::fvec1\fP"
.br
.ti -1c
.RI "typedef highp_f32vec2 \fBglm::fvec2\fP"
.br
.ti -1c
.RI "typedef highp_f32vec3 \fBglm::fvec3\fP"
.br
.ti -1c
.RI "typedef highp_f32vec4 \fBglm::fvec4\fP"
.br
.ti -1c
.RI "typedef highp_f32mat2x2 \fBglm::fmat2x2\fP"
.br
.ti -1c
.RI "typedef highp_f32mat2x3 \fBglm::fmat2x3\fP"
.br
.ti -1c
.RI "typedef highp_f32mat2x4 \fBglm::fmat2x4\fP"
.br
.ti -1c
.RI "typedef highp_f32mat3x2 \fBglm::fmat3x2\fP"
.br
.ti -1c
.RI "typedef highp_f32mat3x3 \fBglm::fmat3x3\fP"
.br
.ti -1c
.RI "typedef highp_f32mat3x4 \fBglm::fmat3x4\fP"
.br
.ti -1c
.RI "typedef highp_f32mat4x2 \fBglm::fmat4x2\fP"
.br
.ti -1c
.RI "typedef highp_f32mat4x3 \fBglm::fmat4x3\fP"
.br
.ti -1c
.RI "typedef highp_f32mat4x4 \fBglm::fmat4x4\fP"
.br
.ti -1c
.RI "typedef fmat2x2 \fBglm::fmat2\fP"
.br
.ti -1c
.RI "typedef fmat3x3 \fBglm::fmat3\fP"
.br
.ti -1c
.RI "typedef fmat4x4 \fBglm::fmat4\fP"
.br
.ti -1c
.RI "typedef highp_f32vec1 \fBglm::f32vec1\fP"
.br
.ti -1c
.RI "typedef highp_f32vec2 \fBglm::f32vec2\fP"
.br
.ti -1c
.RI "typedef highp_f32vec3 \fBglm::f32vec3\fP"
.br
.ti -1c
.RI "typedef highp_f32vec4 \fBglm::f32vec4\fP"
.br
.ti -1c
.RI "typedef highp_f32mat2x2 \fBglm::f32mat2x2\fP"
.br
.ti -1c
.RI "typedef highp_f32mat2x3 \fBglm::f32mat2x3\fP"
.br
.ti -1c
.RI "typedef highp_f32mat2x4 \fBglm::f32mat2x4\fP"
.br
.ti -1c
.RI "typedef highp_f32mat3x2 \fBglm::f32mat3x2\fP"
.br
.ti -1c
.RI "typedef highp_f32mat3x3 \fBglm::f32mat3x3\fP"
.br
.ti -1c
.RI "typedef highp_f32mat3x4 \fBglm::f32mat3x4\fP"
.br
.ti -1c
.RI "typedef highp_f32mat4x2 \fBglm::f32mat4x2\fP"
.br
.ti -1c
.RI "typedef highp_f32mat4x3 \fBglm::f32mat4x3\fP"
.br
.ti -1c
.RI "typedef highp_f32mat4x4 \fBglm::f32mat4x4\fP"
.br
.ti -1c
.RI "typedef f32mat2x2 \fBglm::f32mat2\fP"
.br
.ti -1c
.RI "typedef f32mat3x3 \fBglm::f32mat3\fP"
.br
.ti -1c
.RI "typedef f32mat4x4 \fBglm::f32mat4\fP"
.br
.ti -1c
.RI "typedef highp_f32quat \fBglm::f32quat\fP"
.br
.ti -1c
.RI "typedef highp_f64vec1 \fBglm::f64vec1\fP"
.br
.ti -1c
.RI "typedef highp_f64vec2 \fBglm::f64vec2\fP"
.br
.ti -1c
.RI "typedef highp_f64vec3 \fBglm::f64vec3\fP"
.br
.ti -1c
.RI "typedef highp_f64vec4 \fBglm::f64vec4\fP"
.br
.ti -1c
.RI "typedef highp_f64mat2x2 \fBglm::f64mat2x2\fP"
.br
.ti -1c
.RI "typedef highp_f64mat2x3 \fBglm::f64mat2x3\fP"
.br
.ti -1c
.RI "typedef highp_f64mat2x4 \fBglm::f64mat2x4\fP"
.br
.ti -1c
.RI "typedef highp_f64mat3x2 \fBglm::f64mat3x2\fP"
.br
.ti -1c
.RI "typedef highp_f64mat3x3 \fBglm::f64mat3x3\fP"
.br
.ti -1c
.RI "typedef highp_f64mat3x4 \fBglm::f64mat3x4\fP"
.br
.ti -1c
.RI "typedef highp_f64mat4x2 \fBglm::f64mat4x2\fP"
.br
.ti -1c
.RI "typedef highp_f64mat4x3 \fBglm::f64mat4x3\fP"
.br
.ti -1c
.RI "typedef highp_f64mat4x4 \fBglm::f64mat4x4\fP"
.br
.ti -1c
.RI "typedef f64mat2x2 \fBglm::f64mat2\fP"
.br
.ti -1c
.RI "typedef f64mat3x3 \fBglm::f64mat3\fP"
.br
.ti -1c
.RI "typedef f64mat4x4 \fBglm::f64mat4\fP"
.br
.ti -1c
.RI "typedef highp_f64quat \fBglm::f64quat\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
OpenGL Mathematics (glm\&.g-truc\&.net)
.PP
Copyright (c) 2005 - 2015 G-Truc Creation (www\&.g-truc\&.net) Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the 'Software'), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
.PP
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software\&.
.PP
Restrictions: By making use of the Software for military purposes, you choose to make a Bunny unhappy\&.
.PP
THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT\&. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE\&.
.PP
\fBGLM Core\fP
.PP
\fBDate:\fP
.RS 4
2013-03-30 / 2013-03-31 
.RE
.PP
\fBAuthor:\fP
.RS 4
Christophe Riccio 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
