.TH "glm::io::delimeter< CTy >" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::io::delimeter< CTy > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <io\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdelimeter\fP (CTy, CTy, CTy= ',')"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "CTy \fBvalue\fP [3]"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename CTy > GLM_FUNC_QUALIFIER \fBglm::io::delimeter\fP< CTy >::\fBdelimeter\fP (CTy a, CTy b, CTy c = \fC','\fP)\fC [explicit]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<typename CTy > CTy \fBglm::io::delimeter\fP< CTy >::value[3]"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
