.TH "glm::detail::prefix< float >" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::detail::prefix< float > \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static GLM_FUNC_QUALIFIER char const * \fBvalue\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static GLM_FUNC_QUALIFIER char const* \fBglm::detail::prefix\fP< float >::value ()\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
