.TH "glm::gtc" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::gtc \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_QUALIFIER tvec4< T, P > \fBgrad4\fP (T const &j, tvec4< T, P > const &ip)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<typename T , precision P> GLM_FUNC_QUALIFIER tvec4<T, P> glm::gtc::grad4 (T const & j, tvec4< T, P > const & ip)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
