.TH "glm::detail::u10u10u10u2" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::detail::u10u10u10u2 \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fBuint\fP \fBx\fP: 10"
.br
.ti -1c
.RI "   \fBuint\fP \fBy\fP: 10"
.br
.ti -1c
.RI "   \fBuint\fP \fBz\fP: 10"
.br
.ti -1c
.RI "   \fBuint\fP \fBw\fP: 2"
.br
.ti -1c
.RI "} \fBdata\fP"
.br
.ti -1c
.RI "\fBuint32\fP \fBpack\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct { \&.\&.\&. }   glm::detail::u10u10u10u2::data"

.SS "\fBuint32\fP glm::detail::u10u10u10u2::pack"

.SS "\fBuint\fP glm::detail::u10u10u10u2::w"

.SS "\fBuint\fP glm::detail::u10u10u10u2::x"

.SS "\fBuint\fP glm::detail::u10u10u10u2::y"

.SS "\fBuint\fP glm::detail::u10u10u10u2::z"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
