.TH "glm::io::basic_state_saver< CTy, CTr >" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::io::basic_state_saver< CTy, CTr > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <io\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbasic_state_saver\fP (std::basic_ios< CTy, CTr > &)"
.br
.ti -1c
.RI "\fB~basic_state_saver\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename CTy, typename CTr> GLM_FUNC_QUALIFIER \fBglm::io::basic_state_saver\fP< CTy, CTr >::\fBbasic_state_saver\fP (std::basic_ios< CTy, CTr > & a)\fC [explicit]\fP"

.SS "template<typename CTy , typename CTr > GLM_FUNC_QUALIFIER \fBglm::io::basic_state_saver\fP< CTy, CTr >::~\fBbasic_state_saver\fP ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
