.TH "glm::io::precision" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::io::precision \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <io\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBprecision\fP (unsigned)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned \fBvalue\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GLM_FUNC_QUALIFIER glm::io::precision::precision (unsigned a)\fC [explicit]\fP"

.SH "Member Data Documentation"
.PP 
.SS "unsigned glm::io::precision::value"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
