.TH "glm::detail::i10i10i10i2" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::detail::i10i10i10i2 \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   int \fBx\fP: 10"
.br
.ti -1c
.RI "   int \fBy\fP: 10"
.br
.ti -1c
.RI "   int \fBz\fP: 10"
.br
.ti -1c
.RI "   int \fBw\fP: 2"
.br
.ti -1c
.RI "} \fBdata\fP"
.br
.ti -1c
.RI "\fBuint32\fP \fBpack\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct { \&.\&.\&. }   glm::detail::i10i10i10i2::data"

.SS "\fBuint32\fP glm::detail::i10i10i10i2::pack"

.SS "int glm::detail::i10i10i10i2::w"

.SS "int glm::detail::i10i10i10i2::x"

.SS "int glm::detail::i10i10i10i2::y"

.SS "int glm::detail::i10i10i10i2::z"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
