.TH "glm::detail::compute_floorMultiple< false, true >" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::detail::compute_floorMultiple< false, true > \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename genType > static GLM_FUNC_QUALIFIER genType \fBcall\fP (genType Source, genType Multiple)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename genType > static GLM_FUNC_QUALIFIER genType \fBglm::detail::compute_floorMultiple\fP< false, true >::call (genType Source, genType Multiple)\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
