.TH "glm::io" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::io \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbasic_format_saver\fP"
.br
.ti -1c
.RI "class \fBbasic_state_saver\fP"
.br
.ti -1c
.RI "struct \fBdelimeter\fP"
.br
.ti -1c
.RI "class \fBformat_punct\fP"
.br
.ti -1c
.RI "struct \fBorder\fP"
.br
.ti -1c
.RI "struct \fBprecision\fP"
.br
.ti -1c
.RI "struct \fBwidth\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBbasic_state_saver\fP< char > \fBstate_saver\fP"
.br
.ti -1c
.RI "typedef \fBbasic_state_saver\fP< wchar_t > \fBwstate_saver\fP"
.br
.ti -1c
.RI "typedef \fBbasic_format_saver\fP< char > \fBformat_saver\fP"
.br
.ti -1c
.RI "typedef \fBbasic_format_saver\fP< wchar_t > \fBwformat_saver\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBorder_type\fP { \fBcolumn_major\fP, \fBrow_major\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename FTy , typename CTy , typename CTr > FTy const & \fBget_facet\fP (std::basic_ios< CTy, CTr > &)"
.br
.ti -1c
.RI "template<typename FTy , typename CTy , typename CTr > std::basic_ios< CTy, CTr > & \fBformatted\fP (std::basic_ios< CTy, CTr > &)"
.br
.ti -1c
.RI "template<typename FTy , typename CTy , typename CTr > std::basic_ios< CTy, CTr > & \fBunformattet\fP (std::basic_ios< CTy, CTr > &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr > std::basic_ostream< CTy, CTr > & \fBoperator<<\fP (std::basic_ostream< CTy, CTr > &, \fBprecision\fP const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr > std::basic_ostream< CTy, CTr > & \fBoperator<<\fP (std::basic_ostream< CTy, CTr > &, \fBwidth\fP const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr > std::basic_ostream< CTy, CTr > & \fBoperator<<\fP (std::basic_ostream< CTy, CTr > &, \fBdelimeter\fP< CTy > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr > std::basic_ostream< CTy, CTr > & \fBoperator<<\fP (std::basic_ostream< CTy, CTr > &, \fBorder\fP const &)"
.br
.ti -1c
.RI "template<typename FTy , typename CTy , typename CTr > GLM_FUNC_QUALIFIER FTy const & \fBget_facet\fP (std::basic_ios< CTy, CTr > &ios)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr > GLM_FUNC_QUALIFIER std::basic_ios< CTy, CTr > & \fBformatted\fP (std::basic_ios< CTy, CTr > &ios)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr > GLM_FUNC_QUALIFIER std::basic_ios< CTy, CTr > & \fBunformatted\fP (std::basic_ios< CTy, CTr > &ios)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr > GLM_FUNC_QUALIFIER std::basic_ostream< CTy, CTr > & \fBoperator<<\fP (std::basic_ostream< CTy, CTr > &os, \fBprecision\fP const &a)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr > GLM_FUNC_QUALIFIER std::basic_ostream< CTy, CTr > & \fBoperator<<\fP (std::basic_ostream< CTy, CTr > &os, \fBwidth\fP const &a)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr > GLM_FUNC_QUALIFIER std::basic_ostream< CTy, CTr > & \fBoperator<<\fP (std::basic_ostream< CTy, CTr > &os, \fBorder\fP const &a)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBbasic_format_saver\fP<char> \fBglm::io::format_saver\fP"

.SS "typedef \fBbasic_state_saver\fP<char> \fBglm::io::state_saver\fP"

.SS "typedef \fBbasic_format_saver\fP<wchar_t> \fBglm::io::wformat_saver\fP"

.SS "typedef \fBbasic_state_saver\fP<wchar_t> \fBglm::io::wstate_saver\fP"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBglm::io::order_type\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIcolumn_major \fP\fP
.TP
\fB\fIrow_major \fP\fP
.SH "Function Documentation"
.PP 
.SS "template<typename CTy , typename CTr > GLM_FUNC_QUALIFIER std::basic_ios<CTy,CTr>& glm::io::formatted (std::basic_ios< CTy, CTr > & ios)"

.SS "template<typename FTy , typename CTy , typename CTr > std::basic_ios<CTy,CTr>& glm::io::formatted (std::basic_ios< CTy, CTr > &)"

.SS "template<typename FTy , typename CTy , typename CTr > GLM_FUNC_QUALIFIER FTy const& glm::io::get_facet (std::basic_ios< CTy, CTr > & ios)"

.SS "template<typename FTy , typename CTy , typename CTr > FTy const& glm::io::get_facet (std::basic_ios< CTy, CTr > &)"

.SS "template<typename CTy , typename CTr > GLM_FUNC_QUALIFIER std::basic_ostream<CTy, CTr>& glm::io::operator<< (std::basic_ostream< CTy, CTr > & os, \fBprecision\fP const & a)"

.SS "template<typename CTy , typename CTr > GLM_FUNC_QUALIFIER std::basic_ostream<CTy, CTr>& glm::io::operator<< (std::basic_ostream< CTy, CTr > & os, \fBwidth\fP const & a)"

.SS "template<typename CTy , typename CTr > std::basic_ostream<CTy, CTr>& glm::io::operator<< (std::basic_ostream< CTy, CTr > &, \fBprecision\fP const &)"

.SS "template<typename CTy , typename CTr > std::basic_ostream<CTy, CTr>& glm::io::operator<< (std::basic_ostream< CTy, CTr > &, \fBorder\fP const &)"

.SS "template<typename CTy , typename CTr > std::basic_ostream<CTy, CTr>& glm::io::operator<< (std::basic_ostream< CTy, CTr > &, \fBwidth\fP const &)"

.SS "template<typename CTy , typename CTr > std::basic_ostream< CTy, CTr > & glm::io::operator<< (std::basic_ostream< CTy, CTr > & os, \fBdelimeter\fP< CTy > const & a)"

.SS "template<typename CTy , typename CTr > GLM_FUNC_QUALIFIER std::basic_ostream<CTy, CTr>& glm::io::operator<< (std::basic_ostream< CTy, CTr > & os, \fBorder\fP const & a)"

.SS "template<typename CTy , typename CTr > GLM_FUNC_QUALIFIER std::basic_ios<CTy,CTr>& glm::io::unformatted (std::basic_ios< CTy, CTr > & ios)"

.SS "template<typename FTy , typename CTy , typename CTr > std::basic_ios<CTy,CTr>& glm::io::unformattet (std::basic_ios< CTy, CTr > &)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
