.TH "glm::detail::compute_areCollinear< T, P, tvec4 >" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::detail::compute_areCollinear< T, P, tvec4 > \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static GLM_FUNC_QUALIFIER bool \fBcall\fP (tvec4< T, P > const &v0, tvec4< T, P > const &v1, T const &\fBepsilon\fP)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename T , precision P> static GLM_FUNC_QUALIFIER bool \fBglm::detail::compute_areCollinear\fP< T, P, tvec4 >::call (tvec4< T, P > const & v0, tvec4< T, P > const & v1, T const & epsilon)\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
