.TH "glm::io::format_punct< CTy >" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::io::format_punct< CTy > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <io\&.hpp>\fP
.PP
Inherits facet\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBformat_punct\fP (size_t a=0)"
.br
.ti -1c
.RI "\fBformat_punct\fP (\fBformat_punct\fP const &)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBformatted\fP"
.br
.ti -1c
.RI "unsigned \fBprecision\fP"
.br
.ti -1c
.RI "unsigned \fBwidth\fP"
.br
.ti -1c
.RI "char_type \fBseparator\fP"
.br
.ti -1c
.RI "char_type \fBdelim_left\fP"
.br
.ti -1c
.RI "char_type \fBdelim_right\fP"
.br
.ti -1c
.RI "char_type \fBspace\fP"
.br
.ti -1c
.RI "char_type \fBnewline\fP"
.br
.ti -1c
.RI "\fBorder_type\fP \fBorder\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static std::locale::id \fBid\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename CTy > GLM_FUNC_QUALIFIER \fBglm::io::format_punct\fP< CTy >::\fBformat_punct\fP (size_t a = \fC0\fP)\fC [explicit]\fP"

.SS "template<typename CTy > GLM_FUNC_QUALIFIER \fBglm::io::format_punct\fP< CTy >::\fBformat_punct\fP (\fBformat_punct\fP< CTy > const & a)\fC [explicit]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<typename CTy > char_type \fBglm::io::format_punct\fP< CTy >::delim_left"

.SS "template<typename CTy > char_type \fBglm::io::format_punct\fP< CTy >::delim_right"

.SS "template<typename CTy > bool \fBglm::io::format_punct\fP< CTy >::formatted"

.SS "template<typename CTy > std::locale::id \fBglm::io::format_punct\fP< CTy >::id\fC [static]\fP"

.SS "template<typename CTy > char_type \fBglm::io::format_punct\fP< CTy >::newline"

.SS "template<typename CTy > \fBorder_type\fP \fBglm::io::format_punct\fP< CTy >::\fBorder\fP"

.SS "template<typename CTy > unsigned \fBglm::io::format_punct\fP< CTy >::\fBprecision\fP"

.SS "template<typename CTy > char_type \fBglm::io::format_punct\fP< CTy >::separator"

.SS "template<typename CTy > char_type \fBglm::io::format_punct\fP< CTy >::space"

.SS "template<typename CTy > unsigned \fBglm::io::format_punct\fP< CTy >::\fBwidth\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
