.TH "glm::io::order" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::io::order \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <io\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBorder\fP (\fBorder_type\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBorder_type\fP \fBvalue\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GLM_FUNC_QUALIFIER glm::io::order::order (\fBorder_type\fP a)\fC [explicit]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBorder_type\fP glm::io::order::value"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
