.TH "glm::detail::compute_log2< T, P, vecType, false >" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::detail::compute_log2< T, P, vecType, false > \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static GLM_FUNC_QUALIFIER vecType< T, P > \fBcall\fP (vecType< T, P > const &vec)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<typename T , precision P, template< class, precision > class vecType> static GLM_FUNC_QUALIFIER vecType<T, P> glm::detail::compute_log2< T, P, vecType, false >::call (vecType< T, P > const & vec)\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
