.TH "glm::gtx" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
glm::gtx \- 
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBu8\fP \fBu8vec1\fP"
.br
.RI "\fI8bit unsigned integer scalar\&. (from GLM_GTX_number_precision extension) \fP"
.ti -1c
.RI "typedef \fBu16\fP \fBu16vec1\fP"
.br
.RI "\fI16bit unsigned integer scalar\&. (from GLM_GTX_number_precision extension) \fP"
.ti -1c
.RI "typedef \fBu32\fP \fBu32vec1\fP"
.br
.RI "\fI32bit unsigned integer scalar\&. (from GLM_GTX_number_precision extension) \fP"
.ti -1c
.RI "typedef \fBu64\fP \fBu64vec1\fP"
.br
.RI "\fI64bit unsigned integer scalar\&. (from GLM_GTX_number_precision extension) \fP"
.ti -1c
.RI "typedef \fBf32\fP \fBf32vec1\fP"
.br
.RI "\fISingle-precision floating-point scalar\&. (from GLM_GTX_number_precision extension) \fP"
.ti -1c
.RI "typedef \fBf64\fP \fBf64vec1\fP"
.br
.RI "\fISingle-precision floating-point scalar\&. (from GLM_GTX_number_precision extension) \fP"
.ti -1c
.RI "typedef \fBf32\fP \fBf32mat1\fP"
.br
.RI "\fISingle-precision floating-point scalar\&. (from GLM_GTX_number_precision extension) \fP"
.ti -1c
.RI "typedef \fBf32\fP \fBf32mat1x1\fP"
.br
.RI "\fISingle-precision floating-point scalar\&. (from GLM_GTX_number_precision extension) \fP"
.ti -1c
.RI "typedef \fBf64\fP \fBf64mat1\fP"
.br
.RI "\fIDouble-precision floating-point scalar\&. (from GLM_GTX_number_precision extension) \fP"
.ti -1c
.RI "typedef \fBf64\fP \fBf64mat1x1\fP"
.br
.RI "\fIDouble-precision floating-point scalar\&. (from GLM_GTX_number_precision extension) \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBpow2\fP (genType const &x)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBpow3\fP (genType const &x)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBpow4\fP (genType const &x)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
