.TH "gtc" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtc \- GTC Extensions (Stable)
.PP
Functions and types that the GLSL specification doesn't define, but useful to have for a C++ program\&.  

.SS "Modules"

.in +1c
.ti -1c
.RI "\fBGLM_GTC_bitfield\fP"
.br
.RI "\fIAllow to perform bit operations on integer values\&. \fP"
.ti -1c
.RI "\fBGLM_GTC_color_space\fP"
.br
.RI "\fIAllow to perform bit operations on integer values\&. \fP"
.ti -1c
.RI "\fBGLM_GTC_constants\fP"
.br
.RI "\fIProvide a list of constants and precomputed useful values\&. \fP"
.ti -1c
.RI "\fBGLM_GTC_epsilon\fP"
.br
.RI "\fIComparison functions for a user defined epsilon values\&. \fP"
.ti -1c
.RI "\fBGLM_GTC_integer\fP"
.br
.RI "\fIAllow to perform bit operations on integer values\&. \fP"
.ti -1c
.RI "\fBGLM_GTC_matrix_access\fP"
.br
.ti -1c
.RI "\fBGLM_GTC_matrix_integer\fP"
.br
.ti -1c
.RI "\fBGLM_GTC_matrix_inverse\fP"
.br
.ti -1c
.RI "\fBGLM_GTC_matrix_transform\fP"
.br
.RI "\fIDefines functions that generate common transformation matrices\&. \fP"
.ti -1c
.RI "\fBGLM_GTC_noise\fP"
.br
.ti -1c
.RI "\fBGLM_GTC_packing\fP"
.br
.RI "\fIThis extension provides a set of function to convert vertors to packed formats\&. \fP"
.ti -1c
.RI "\fBGLM_GTC_quaternion\fP"
.br
.RI "\fIDefines a templated quaternion type and several quaternion operations\&. \fP"
.ti -1c
.RI "\fBGLM_GTC_random\fP"
.br
.RI "\fIGenerate random number from various distribution methods\&. \fP"
.ti -1c
.RI "\fBGLM_GTC_reciprocal\fP"
.br
.RI "\fIDefine secant, cosecant and cotangent functions\&. \fP"
.ti -1c
.RI "\fBGLM_GTC_round\fP"
.br
.RI "\fIrounding value to specific boundings \fP"
.ti -1c
.RI "\fBGLM_GTC_type_precision\fP"
.br
.RI "\fIDefines specific C++-based precision types\&. \fP"
.ti -1c
.RI "\fBGLM_GTC_type_ptr\fP"
.br
.RI "\fIHandles the interaction between pointers and vector, matrix types\&. \fP"
.ti -1c
.RI "\fBGLM_GTC_ulp\fP"
.br
.RI "\fIAllow the measurement of the accuracy of a function against a reference implementation\&. This extension works on floating-point data and provide results in ULP\&. <\fBglm/gtc/ulp\&.hpp\fP> need to be included to use these features\&. \fP"
.ti -1c
.RI "\fBGLM_GTC_vec1\fP"
.br
.RI "\fIAdd vec1, ivec1, uvec1 and bvec1 types\&. <\fBglm/gtc/vec1\&.hpp\fP> need to be included to use these functionalities\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Functions and types that the GLSL specification doesn't define, but useful to have for a C++ program\&. 

GTC extensions aim to be stable\&.
.PP
Even if it's highly unrecommended, it's possible to include all the extensions at once by including <\fBglm/ext\&.hpp\fP>\&. Otherwise, each extension needs to be included a specific file\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
