.TH "gtc_reciprocal" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtc_reciprocal \- GLM_GTC_reciprocal
.PP
Define secant, cosecant and cotangent functions\&.  

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::sec\fP (genType const &angle)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::csc\fP (genType const &angle)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::cot\fP (genType const &angle)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::asec\fP (genType const &x)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::acsc\fP (genType const &x)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::acot\fP (genType const &x)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::sech\fP (genType const &angle)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::csch\fP (genType const &angle)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::coth\fP (genType const &angle)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::asech\fP (genType const &x)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::acsch\fP (genType const &x)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::acoth\fP (genType const &x)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Define secant, cosecant and cotangent functions\&. 

<\fBglm/gtc/reciprocal\&.hpp\fP> need to be included to use these features\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename genType > GLM_FUNC_DECL genType glm::acot (genType const & x)"
Inverse cotangent function\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_reciprocal\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::acoth (genType const & x)"
Inverse cotangent hyperbolic function\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_reciprocal\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::acsc (genType const & x)"
Inverse cosecant function\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_reciprocal\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::acsch (genType const & x)"
Inverse cosecant hyperbolic function\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_reciprocal\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::asec (genType const & x)"
Inverse secant function\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_reciprocal\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::asech (genType const & x)"
Inverse secant hyperbolic function\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_reciprocal\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::cot (genType const & angle)"
Cotangent function\&. adjacent / opposite or 1 / tan(x)
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_reciprocal\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::coth (genType const & angle)"
Cotangent hyperbolic function\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_reciprocal\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::csc (genType const & angle)"
Cosecant function\&. hypotenuse / opposite or 1 / sin(x)
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_reciprocal\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::csch (genType const & angle)"
Cosecant hyperbolic function\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_reciprocal\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::sec (genType const & angle)"
Secant function\&. hypotenuse / adjacent or 1 / cos(x)
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_reciprocal\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::sech (genType const & angle)"
Secant hyperbolic function\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_reciprocal\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
