.TH "gtc_round" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtc_round \- GLM_GTC_round
.PP
rounding value to specific boundings  

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genIUType > GLM_FUNC_DECL bool \fBglm::isPowerOfTwo\fP (genIUType Value)"
.br
.ti -1c
.RI "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType< bool, P > \fBglm::isPowerOfTwo\fP (vecType< T, P > const &value)"
.br
.ti -1c
.RI "template<typename genIUType > GLM_FUNC_DECL genIUType \fBglm::ceilPowerOfTwo\fP (genIUType Value)"
.br
.ti -1c
.RI "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType< T, P > \fBglm::ceilPowerOfTwo\fP (vecType< T, P > const &value)"
.br
.ti -1c
.RI "template<typename genIUType > GLM_FUNC_DECL genIUType \fBglm::floorPowerOfTwo\fP (genIUType Value)"
.br
.ti -1c
.RI "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType< T, P > \fBglm::floorPowerOfTwo\fP (vecType< T, P > const &value)"
.br
.ti -1c
.RI "template<typename genIUType > GLM_FUNC_DECL genIUType \fBglm::roundPowerOfTwo\fP (genIUType Value)"
.br
.ti -1c
.RI "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType< T, P > \fBglm::roundPowerOfTwo\fP (vecType< T, P > const &value)"
.br
.ti -1c
.RI "template<typename genIUType > GLM_FUNC_DECL bool \fBglm::isMultiple\fP (genIUType Value, genIUType Multiple)"
.br
.ti -1c
.RI "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType< bool, P > \fBglm::isMultiple\fP (vecType< T, P > const &Value, T Multiple)"
.br
.ti -1c
.RI "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType< bool, P > \fBglm::isMultiple\fP (vecType< T, P > const &Value, vecType< T, P > const &Multiple)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::ceilMultiple\fP (genType Source, genType Multiple)"
.br
.ti -1c
.RI "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType< T, P > \fBglm::ceilMultiple\fP (vecType< T, P > const &Source, vecType< T, P > const &Multiple)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::floorMultiple\fP (genType Source, genType Multiple)"
.br
.ti -1c
.RI "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType< T, P > \fBglm::floorMultiple\fP (vecType< T, P > const &Source, vecType< T, P > const &Multiple)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::roundMultiple\fP (genType Source, genType Multiple)"
.br
.ti -1c
.RI "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType< T, P > \fBglm::roundMultiple\fP (vecType< T, P > const &Source, vecType< T, P > const &Multiple)"
.br
.in -1c
.SH "Detailed Description"
.PP 
rounding value to specific boundings 

<\fBglm/gtc/round\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename genType > GLM_FUNC_DECL genType glm::ceilMultiple (genType Source, genType Multiple)"
Higher multiple number of Source\&.
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIgenType\fP Floating-point or integer scalar or vector types\&. 
.RE
.PP
\fBParameters:\fP
.RS 4
\fISource\fP 
.br
\fIMultiple\fP Must be a null or positive value
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_round\fP 
.RE
.PP

.SS "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType<T, P> glm::ceilMultiple (vecType< T, P > const & Source, vecType< T, P > const & Multiple)"
Higher multiple number of Source\&.
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIgenType\fP Floating-point or integer scalar or vector types\&. 
.RE
.PP
\fBParameters:\fP
.RS 4
\fISource\fP 
.br
\fIMultiple\fP Must be a null or positive value
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_round\fP 
.RE
.PP

.SS "template<typename genIUType > GLM_FUNC_DECL genIUType glm::ceilPowerOfTwo (genIUType Value)"
Return the power of two number which value is just higher the input value, round up to a power of two\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_round\fP 
.RE
.PP

.SS "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType<T, P> glm::ceilPowerOfTwo (vecType< T, P > const & value)"
Return the power of two number which value is just higher the input value, round up to a power of two\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_round\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::floorMultiple (genType Source, genType Multiple)"
Lower multiple number of Source\&.
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIgenType\fP Floating-point or integer scalar or vector types\&. 
.RE
.PP
\fBParameters:\fP
.RS 4
\fISource\fP 
.br
\fIMultiple\fP Must be a null or positive value
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_round\fP 
.RE
.PP

.SS "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType<T, P> glm::floorMultiple (vecType< T, P > const & Source, vecType< T, P > const & Multiple)"
Lower multiple number of Source\&.
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIgenType\fP Floating-point or integer scalar or vector types\&. 
.RE
.PP
\fBParameters:\fP
.RS 4
\fISource\fP 
.br
\fIMultiple\fP Must be a null or positive value
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_round\fP 
.RE
.PP

.SS "template<typename genIUType > GLM_FUNC_DECL genIUType glm::floorPowerOfTwo (genIUType Value)"
Return the power of two number which value is just lower the input value, round down to a power of two\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_round\fP 
.RE
.PP

.SS "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType<T, P> glm::floorPowerOfTwo (vecType< T, P > const & value)"
Return the power of two number which value is just lower the input value, round down to a power of two\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_round\fP 
.RE
.PP

.SS "template<typename genIUType > GLM_FUNC_DECL bool glm::isMultiple (genIUType Value, genIUType Multiple)"
Return true if the 'Value' is a multiple of 'Multiple'\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_round\fP 
.RE
.PP

.SS "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType<bool, P> glm::isMultiple (vecType< T, P > const & Value, T Multiple)"
Return true if the 'Value' is a multiple of 'Multiple'\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_round\fP 
.RE
.PP

.SS "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType<bool, P> glm::isMultiple (vecType< T, P > const & Value, vecType< T, P > const & Multiple)"
Return true if the 'Value' is a multiple of 'Multiple'\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_round\fP 
.RE
.PP

.SS "template<typename genIUType > GLM_FUNC_DECL bool glm::isPowerOfTwo (genIUType Value)"
Return true if the value is a power of two number\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_round\fP 
.RE
.PP

.SS "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType<bool, P> glm::isPowerOfTwo (vecType< T, P > const & value)"
Return true if the value is a power of two number\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_round\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::roundMultiple (genType Source, genType Multiple)"
Lower multiple number of Source\&.
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIgenType\fP Floating-point or integer scalar or vector types\&. 
.RE
.PP
\fBParameters:\fP
.RS 4
\fISource\fP 
.br
\fIMultiple\fP Must be a null or positive value
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_round\fP 
.RE
.PP

.SS "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType<T, P> glm::roundMultiple (vecType< T, P > const & Source, vecType< T, P > const & Multiple)"
Lower multiple number of Source\&.
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIgenType\fP Floating-point or integer scalar or vector types\&. 
.RE
.PP
\fBParameters:\fP
.RS 4
\fISource\fP 
.br
\fIMultiple\fP Must be a null or positive value
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_round\fP 
.RE
.PP

.SS "template<typename genIUType > GLM_FUNC_DECL genIUType glm::roundPowerOfTwo (genIUType Value)"
Return the power of two number which value is the closet to the input value\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_round\fP 
.RE
.PP

.SS "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType<T, P> glm::roundPowerOfTwo (vecType< T, P > const & value)"
Return the power of two number which value is the closet to the input value\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_round\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
