.TH "gtc_vec1" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtc_vec1 \- GLM_GTC_vec1
.PP
Add vec1, ivec1, uvec1 and bvec1 types\&. <\fBglm/gtc/vec1\&.hpp\fP> need to be included to use these functionalities\&.  
Add vec1, ivec1, uvec1 and bvec1 types\&. <\fBglm/gtc/vec1\&.hpp\fP> need to be included to use these functionalities\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
