.TH "gtc_matrix_integer" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtc_matrix_integer \- GLM_GTC_matrix_integer
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef tmat2x2< int, highp > \fBglm::highp_imat2\fP"
.br
.ti -1c
.RI "typedef tmat3x3< int, highp > \fBglm::highp_imat3\fP"
.br
.ti -1c
.RI "typedef tmat4x4< int, highp > \fBglm::highp_imat4\fP"
.br
.ti -1c
.RI "typedef tmat2x2< int, highp > \fBglm::highp_imat2x2\fP"
.br
.ti -1c
.RI "typedef tmat2x3< int, highp > \fBglm::highp_imat2x3\fP"
.br
.ti -1c
.RI "typedef tmat2x4< int, highp > \fBglm::highp_imat2x4\fP"
.br
.ti -1c
.RI "typedef tmat3x2< int, highp > \fBglm::highp_imat3x2\fP"
.br
.ti -1c
.RI "typedef tmat3x3< int, highp > \fBglm::highp_imat3x3\fP"
.br
.ti -1c
.RI "typedef tmat3x4< int, highp > \fBglm::highp_imat3x4\fP"
.br
.ti -1c
.RI "typedef tmat4x2< int, highp > \fBglm::highp_imat4x2\fP"
.br
.ti -1c
.RI "typedef tmat4x3< int, highp > \fBglm::highp_imat4x3\fP"
.br
.ti -1c
.RI "typedef tmat4x4< int, highp > \fBglm::highp_imat4x4\fP"
.br
.ti -1c
.RI "typedef tmat2x2< int, mediump > \fBglm::mediump_imat2\fP"
.br
.ti -1c
.RI "typedef tmat3x3< int, mediump > \fBglm::mediump_imat3\fP"
.br
.ti -1c
.RI "typedef tmat4x4< int, mediump > \fBglm::mediump_imat4\fP"
.br
.ti -1c
.RI "typedef tmat2x2< int, mediump > \fBglm::mediump_imat2x2\fP"
.br
.ti -1c
.RI "typedef tmat2x3< int, mediump > \fBglm::mediump_imat2x3\fP"
.br
.ti -1c
.RI "typedef tmat2x4< int, mediump > \fBglm::mediump_imat2x4\fP"
.br
.ti -1c
.RI "typedef tmat3x2< int, mediump > \fBglm::mediump_imat3x2\fP"
.br
.ti -1c
.RI "typedef tmat3x3< int, mediump > \fBglm::mediump_imat3x3\fP"
.br
.ti -1c
.RI "typedef tmat3x4< int, mediump > \fBglm::mediump_imat3x4\fP"
.br
.ti -1c
.RI "typedef tmat4x2< int, mediump > \fBglm::mediump_imat4x2\fP"
.br
.ti -1c
.RI "typedef tmat4x3< int, mediump > \fBglm::mediump_imat4x3\fP"
.br
.ti -1c
.RI "typedef tmat4x4< int, mediump > \fBglm::mediump_imat4x4\fP"
.br
.ti -1c
.RI "typedef tmat2x2< int, lowp > \fBglm::lowp_imat2\fP"
.br
.ti -1c
.RI "typedef tmat3x3< int, lowp > \fBglm::lowp_imat3\fP"
.br
.ti -1c
.RI "typedef tmat4x4< int, lowp > \fBglm::lowp_imat4\fP"
.br
.ti -1c
.RI "typedef tmat2x2< int, lowp > \fBglm::lowp_imat2x2\fP"
.br
.ti -1c
.RI "typedef tmat2x3< int, lowp > \fBglm::lowp_imat2x3\fP"
.br
.ti -1c
.RI "typedef tmat2x4< int, lowp > \fBglm::lowp_imat2x4\fP"
.br
.ti -1c
.RI "typedef tmat3x2< int, lowp > \fBglm::lowp_imat3x2\fP"
.br
.ti -1c
.RI "typedef tmat3x3< int, lowp > \fBglm::lowp_imat3x3\fP"
.br
.ti -1c
.RI "typedef tmat3x4< int, lowp > \fBglm::lowp_imat3x4\fP"
.br
.ti -1c
.RI "typedef tmat4x2< int, lowp > \fBglm::lowp_imat4x2\fP"
.br
.ti -1c
.RI "typedef tmat4x3< int, lowp > \fBglm::lowp_imat4x3\fP"
.br
.ti -1c
.RI "typedef tmat4x4< int, lowp > \fBglm::lowp_imat4x4\fP"
.br
.ti -1c
.RI "typedef tmat2x2< \fBuint\fP, highp > \fBglm::highp_umat2\fP"
.br
.ti -1c
.RI "typedef tmat3x3< \fBuint\fP, highp > \fBglm::highp_umat3\fP"
.br
.ti -1c
.RI "typedef tmat4x4< \fBuint\fP, highp > \fBglm::highp_umat4\fP"
.br
.ti -1c
.RI "typedef tmat2x2< \fBuint\fP, highp > \fBglm::highp_umat2x2\fP"
.br
.ti -1c
.RI "typedef tmat2x3< \fBuint\fP, highp > \fBglm::highp_umat2x3\fP"
.br
.ti -1c
.RI "typedef tmat2x4< \fBuint\fP, highp > \fBglm::highp_umat2x4\fP"
.br
.ti -1c
.RI "typedef tmat3x2< \fBuint\fP, highp > \fBglm::highp_umat3x2\fP"
.br
.ti -1c
.RI "typedef tmat3x3< \fBuint\fP, highp > \fBglm::highp_umat3x3\fP"
.br
.ti -1c
.RI "typedef tmat3x4< \fBuint\fP, highp > \fBglm::highp_umat3x4\fP"
.br
.ti -1c
.RI "typedef tmat4x2< \fBuint\fP, highp > \fBglm::highp_umat4x2\fP"
.br
.ti -1c
.RI "typedef tmat4x3< \fBuint\fP, highp > \fBglm::highp_umat4x3\fP"
.br
.ti -1c
.RI "typedef tmat4x4< \fBuint\fP, highp > \fBglm::highp_umat4x4\fP"
.br
.ti -1c
.RI "typedef tmat2x2< \fBuint\fP, mediump > \fBglm::mediump_umat2\fP"
.br
.ti -1c
.RI "typedef tmat3x3< \fBuint\fP, mediump > \fBglm::mediump_umat3\fP"
.br
.ti -1c
.RI "typedef tmat4x4< \fBuint\fP, mediump > \fBglm::mediump_umat4\fP"
.br
.ti -1c
.RI "typedef tmat2x2< \fBuint\fP, mediump > \fBglm::mediump_umat2x2\fP"
.br
.ti -1c
.RI "typedef tmat2x3< \fBuint\fP, mediump > \fBglm::mediump_umat2x3\fP"
.br
.ti -1c
.RI "typedef tmat2x4< \fBuint\fP, mediump > \fBglm::mediump_umat2x4\fP"
.br
.ti -1c
.RI "typedef tmat3x2< \fBuint\fP, mediump > \fBglm::mediump_umat3x2\fP"
.br
.ti -1c
.RI "typedef tmat3x3< \fBuint\fP, mediump > \fBglm::mediump_umat3x3\fP"
.br
.ti -1c
.RI "typedef tmat3x4< \fBuint\fP, mediump > \fBglm::mediump_umat3x4\fP"
.br
.ti -1c
.RI "typedef tmat4x2< \fBuint\fP, mediump > \fBglm::mediump_umat4x2\fP"
.br
.ti -1c
.RI "typedef tmat4x3< \fBuint\fP, mediump > \fBglm::mediump_umat4x3\fP"
.br
.ti -1c
.RI "typedef tmat4x4< \fBuint\fP, mediump > \fBglm::mediump_umat4x4\fP"
.br
.ti -1c
.RI "typedef tmat2x2< \fBuint\fP, lowp > \fBglm::lowp_umat2\fP"
.br
.ti -1c
.RI "typedef tmat3x3< \fBuint\fP, lowp > \fBglm::lowp_umat3\fP"
.br
.ti -1c
.RI "typedef tmat4x4< \fBuint\fP, lowp > \fBglm::lowp_umat4\fP"
.br
.ti -1c
.RI "typedef tmat2x2< \fBuint\fP, lowp > \fBglm::lowp_umat2x2\fP"
.br
.ti -1c
.RI "typedef tmat2x3< \fBuint\fP, lowp > \fBglm::lowp_umat2x3\fP"
.br
.ti -1c
.RI "typedef tmat2x4< \fBuint\fP, lowp > \fBglm::lowp_umat2x4\fP"
.br
.ti -1c
.RI "typedef tmat3x2< \fBuint\fP, lowp > \fBglm::lowp_umat3x2\fP"
.br
.ti -1c
.RI "typedef tmat3x3< \fBuint\fP, lowp > \fBglm::lowp_umat3x3\fP"
.br
.ti -1c
.RI "typedef tmat3x4< \fBuint\fP, lowp > \fBglm::lowp_umat3x4\fP"
.br
.ti -1c
.RI "typedef tmat4x2< \fBuint\fP, lowp > \fBglm::lowp_umat4x2\fP"
.br
.ti -1c
.RI "typedef tmat4x3< \fBuint\fP, lowp > \fBglm::lowp_umat4x3\fP"
.br
.ti -1c
.RI "typedef tmat4x4< \fBuint\fP, lowp > \fBglm::lowp_umat4x4\fP"
.br
.ti -1c
.RI "typedef mediump_imat2 \fBglm::imat2\fP"
.br
.ti -1c
.RI "typedef mediump_imat3 \fBglm::imat3\fP"
.br
.ti -1c
.RI "typedef mediump_imat4 \fBglm::imat4\fP"
.br
.ti -1c
.RI "typedef mediump_imat2x2 \fBglm::imat2x2\fP"
.br
.ti -1c
.RI "typedef mediump_imat2x3 \fBglm::imat2x3\fP"
.br
.ti -1c
.RI "typedef mediump_imat2x4 \fBglm::imat2x4\fP"
.br
.ti -1c
.RI "typedef mediump_imat3x2 \fBglm::imat3x2\fP"
.br
.ti -1c
.RI "typedef mediump_imat3x3 \fBglm::imat3x3\fP"
.br
.ti -1c
.RI "typedef mediump_imat3x4 \fBglm::imat3x4\fP"
.br
.ti -1c
.RI "typedef mediump_imat4x2 \fBglm::imat4x2\fP"
.br
.ti -1c
.RI "typedef mediump_imat4x3 \fBglm::imat4x3\fP"
.br
.ti -1c
.RI "typedef mediump_imat4x4 \fBglm::imat4x4\fP"
.br
.ti -1c
.RI "typedef mediump_umat2 \fBglm::umat2\fP"
.br
.ti -1c
.RI "typedef mediump_umat3 \fBglm::umat3\fP"
.br
.ti -1c
.RI "typedef mediump_umat4 \fBglm::umat4\fP"
.br
.ti -1c
.RI "typedef mediump_umat2x2 \fBglm::umat2x2\fP"
.br
.ti -1c
.RI "typedef mediump_umat2x3 \fBglm::umat2x3\fP"
.br
.ti -1c
.RI "typedef mediump_umat2x4 \fBglm::umat2x4\fP"
.br
.ti -1c
.RI "typedef mediump_umat3x2 \fBglm::umat3x2\fP"
.br
.ti -1c
.RI "typedef mediump_umat3x3 \fBglm::umat3x3\fP"
.br
.ti -1c
.RI "typedef mediump_umat3x4 \fBglm::umat3x4\fP"
.br
.ti -1c
.RI "typedef mediump_umat4x2 \fBglm::umat4x2\fP"
.br
.ti -1c
.RI "typedef mediump_umat4x3 \fBglm::umat4x3\fP"
.br
.ti -1c
.RI "typedef mediump_umat4x4 \fBglm::umat4x4\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines a number of matrices with integer types\&. <\fBglm/gtc/matrix_integer\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Typedef Documentation"
.PP 
.SS "typedef tmat2x2<int, highp> \fBglm::highp_imat2\fP"
High-precision signed integer 2x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat2x2<int, highp> \fBglm::highp_imat2x2\fP"
High-precision signed integer 2x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat2x3<int, highp> \fBglm::highp_imat2x3\fP"
High-precision signed integer 2x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat2x4<int, highp> \fBglm::highp_imat2x4\fP"
High-precision signed integer 2x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat3x3<int, highp> \fBglm::highp_imat3\fP"
High-precision signed integer 3x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat3x2<int, highp> \fBglm::highp_imat3x2\fP"
High-precision signed integer 3x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat3x3<int, highp> \fBglm::highp_imat3x3\fP"
High-precision signed integer 3x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat3x4<int, highp> \fBglm::highp_imat3x4\fP"
High-precision signed integer 3x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat4x4<int, highp> \fBglm::highp_imat4\fP"
High-precision signed integer 4x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat4x2<int, highp> \fBglm::highp_imat4x2\fP"
High-precision signed integer 4x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat4x3<int, highp> \fBglm::highp_imat4x3\fP"
High-precision signed integer 4x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat4x4<int, highp> \fBglm::highp_imat4x4\fP"
High-precision signed integer 4x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat2x2<\fBuint\fP, highp> \fBglm::highp_umat2\fP"
High-precision unsigned integer 2x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat2x2<\fBuint\fP, highp> \fBglm::highp_umat2x2\fP"
High-precision unsigned integer 2x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat2x3<\fBuint\fP, highp> \fBglm::highp_umat2x3\fP"
High-precision unsigned integer 2x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat2x4<\fBuint\fP, highp> \fBglm::highp_umat2x4\fP"
High-precision unsigned integer 2x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat3x3<\fBuint\fP, highp> \fBglm::highp_umat3\fP"
High-precision unsigned integer 3x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat3x2<\fBuint\fP, highp> \fBglm::highp_umat3x2\fP"
High-precision unsigned integer 3x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat3x3<\fBuint\fP, highp> \fBglm::highp_umat3x3\fP"
High-precision unsigned integer 3x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat3x4<\fBuint\fP, highp> \fBglm::highp_umat3x4\fP"
High-precision unsigned integer 3x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat4x4<\fBuint\fP, highp> \fBglm::highp_umat4\fP"
High-precision unsigned integer 4x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat4x2<\fBuint\fP, highp> \fBglm::highp_umat4x2\fP"
High-precision unsigned integer 4x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat4x3<\fBuint\fP, highp> \fBglm::highp_umat4x3\fP"
High-precision unsigned integer 4x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat4x4<\fBuint\fP, highp> \fBglm::highp_umat4x4\fP"
High-precision unsigned integer 4x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef mediump_imat2 \fBglm::imat2\fP"
Signed integer 2x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef mediump_imat2x2 \fBglm::imat2x2\fP"
Signed integer 2x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef mediump_imat2x3 \fBglm::imat2x3\fP"
Signed integer 2x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef mediump_imat2x4 \fBglm::imat2x4\fP"
Signed integer 2x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef mediump_imat3 \fBglm::imat3\fP"
Signed integer 3x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef mediump_imat3x2 \fBglm::imat3x2\fP"
Signed integer 3x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef mediump_imat3x3 \fBglm::imat3x3\fP"
Signed integer 3x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef mediump_imat3x4 \fBglm::imat3x4\fP"
Signed integer 3x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef mediump_imat4 \fBglm::imat4\fP"
Signed integer 4x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef mediump_imat4x2 \fBglm::imat4x2\fP"
Signed integer 4x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef mediump_imat4x3 \fBglm::imat4x3\fP"
Signed integer 4x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef mediump_imat4x4 \fBglm::imat4x4\fP"
Signed integer 4x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat2x2<int, lowp> \fBglm::lowp_imat2\fP"
Low-precision signed integer 2x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat2x2<int, lowp> \fBglm::lowp_imat2x2\fP"
Low-precision signed integer 2x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat2x3<int, lowp> \fBglm::lowp_imat2x3\fP"
Low-precision signed integer 2x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat2x4<int, lowp> \fBglm::lowp_imat2x4\fP"
Low-precision signed integer 2x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat3x3<int, lowp> \fBglm::lowp_imat3\fP"
Low-precision signed integer 3x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat3x2<int, lowp> \fBglm::lowp_imat3x2\fP"
Low-precision signed integer 3x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat3x3<int, lowp> \fBglm::lowp_imat3x3\fP"
Low-precision signed integer 3x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat3x4<int, lowp> \fBglm::lowp_imat3x4\fP"
Low-precision signed integer 3x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat4x4<int, lowp> \fBglm::lowp_imat4\fP"
Low-precision signed integer 4x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat4x2<int, lowp> \fBglm::lowp_imat4x2\fP"
Low-precision signed integer 4x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat4x3<int, lowp> \fBglm::lowp_imat4x3\fP"
Low-precision signed integer 4x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat4x4<int, lowp> \fBglm::lowp_imat4x4\fP"
Low-precision signed integer 4x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat2x2<\fBuint\fP, lowp> \fBglm::lowp_umat2\fP"
Low-precision unsigned integer 2x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat2x2<\fBuint\fP, lowp> \fBglm::lowp_umat2x2\fP"
Low-precision unsigned integer 2x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat2x3<\fBuint\fP, lowp> \fBglm::lowp_umat2x3\fP"
Low-precision unsigned integer 2x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat2x4<\fBuint\fP, lowp> \fBglm::lowp_umat2x4\fP"
Low-precision unsigned integer 2x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat3x3<\fBuint\fP, lowp> \fBglm::lowp_umat3\fP"
Low-precision unsigned integer 3x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat3x2<\fBuint\fP, lowp> \fBglm::lowp_umat3x2\fP"
Low-precision unsigned integer 3x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat3x3<\fBuint\fP, lowp> \fBglm::lowp_umat3x3\fP"
Low-precision unsigned integer 3x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat3x4<\fBuint\fP, lowp> \fBglm::lowp_umat3x4\fP"
Low-precision unsigned integer 3x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat4x4<\fBuint\fP, lowp> \fBglm::lowp_umat4\fP"
Low-precision unsigned integer 4x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat4x2<\fBuint\fP, lowp> \fBglm::lowp_umat4x2\fP"
Low-precision unsigned integer 4x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat4x3<\fBuint\fP, lowp> \fBglm::lowp_umat4x3\fP"
Low-precision unsigned integer 4x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat4x4<\fBuint\fP, lowp> \fBglm::lowp_umat4x4\fP"
Low-precision unsigned integer 4x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat2x2<int, mediump> \fBglm::mediump_imat2\fP"
Medium-precision signed integer 2x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat2x2<int, mediump> \fBglm::mediump_imat2x2\fP"
Medium-precision signed integer 2x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat2x3<int, mediump> \fBglm::mediump_imat2x3\fP"
Medium-precision signed integer 2x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat2x4<int, mediump> \fBglm::mediump_imat2x4\fP"
Medium-precision signed integer 2x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat3x3<int, mediump> \fBglm::mediump_imat3\fP"
Medium-precision signed integer 3x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat3x2<int, mediump> \fBglm::mediump_imat3x2\fP"
Medium-precision signed integer 3x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat3x3<int, mediump> \fBglm::mediump_imat3x3\fP"
Medium-precision signed integer 3x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat3x4<int, mediump> \fBglm::mediump_imat3x4\fP"
Medium-precision signed integer 3x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat4x4<int, mediump> \fBglm::mediump_imat4\fP"
Medium-precision signed integer 4x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat4x2<int, mediump> \fBglm::mediump_imat4x2\fP"
Medium-precision signed integer 4x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat4x3<int, mediump> \fBglm::mediump_imat4x3\fP"
Medium-precision signed integer 4x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat4x4<int, mediump> \fBglm::mediump_imat4x4\fP"
Medium-precision signed integer 4x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat2x2<\fBuint\fP, mediump> \fBglm::mediump_umat2\fP"
Medium-precision unsigned integer 2x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat2x2<\fBuint\fP, mediump> \fBglm::mediump_umat2x2\fP"
Medium-precision unsigned integer 2x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat2x3<\fBuint\fP, mediump> \fBglm::mediump_umat2x3\fP"
Medium-precision unsigned integer 2x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat2x4<\fBuint\fP, mediump> \fBglm::mediump_umat2x4\fP"
Medium-precision unsigned integer 2x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat3x3<\fBuint\fP, mediump> \fBglm::mediump_umat3\fP"
Medium-precision unsigned integer 3x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat3x2<\fBuint\fP, mediump> \fBglm::mediump_umat3x2\fP"
Medium-precision unsigned integer 3x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat3x3<\fBuint\fP, mediump> \fBglm::mediump_umat3x3\fP"
Medium-precision unsigned integer 3x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat3x4<\fBuint\fP, mediump> \fBglm::mediump_umat3x4\fP"
Medium-precision unsigned integer 3x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat4x4<\fBuint\fP, mediump> \fBglm::mediump_umat4\fP"
Medium-precision unsigned integer 4x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat4x2<\fBuint\fP, mediump> \fBglm::mediump_umat4x2\fP"
Medium-precision unsigned integer 4x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat4x3<\fBuint\fP, mediump> \fBglm::mediump_umat4x3\fP"
Medium-precision unsigned integer 4x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef tmat4x4<\fBuint\fP, mediump> \fBglm::mediump_umat4x4\fP"
Medium-precision unsigned integer 4x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef mediump_umat2 \fBglm::umat2\fP"
Unsigned integer 2x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef mediump_umat2x2 \fBglm::umat2x2\fP"
Unsigned integer 2x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef mediump_umat2x3 \fBglm::umat2x3\fP"
Unsigned integer 2x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef mediump_umat2x4 \fBglm::umat2x4\fP"
Unsigned integer 2x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef mediump_umat3 \fBglm::umat3\fP"
Unsigned integer 3x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef mediump_umat3x2 \fBglm::umat3x2\fP"
Unsigned integer 3x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef mediump_umat3x3 \fBglm::umat3x3\fP"
Unsigned integer 3x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef mediump_umat3x4 \fBglm::umat3x4\fP"
Unsigned integer 3x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef mediump_umat4 \fBglm::umat4\fP"
Unsigned integer 4x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef mediump_umat4x2 \fBglm::umat4x2\fP"
Unsigned integer 4x2 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef mediump_umat4x3 \fBglm::umat4x3\fP"
Unsigned integer 4x3 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SS "typedef mediump_umat4x4 \fBglm::umat4x4\fP"
Unsigned integer 4x4 matrix\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_integer\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
