.TH "gtc_random" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtc_random \- GLM_GTC_random
.PP
Generate random number from various distribution methods\&.  

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genTYpe > GLM_FUNC_DECL genTYpe \fBglm::linearRand\fP (genTYpe Min, genTYpe Max)"
.br
.ti -1c
.RI "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType< T, P > \fBglm::linearRand\fP (vecType< T, P > const &Min, vecType< T, P > const &Max)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::gaussRand\fP (genType Mean, genType Deviation)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL tvec2< T, defaultp > \fBglm::circularRand\fP (T Radius)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL tvec3< T, defaultp > \fBglm::sphericalRand\fP (T Radius)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL tvec2< T, defaultp > \fBglm::diskRand\fP (T Radius)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL tvec3< T, defaultp > \fBglm::ballRand\fP (T Radius)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Generate random number from various distribution methods\&. 

<\fBglm/gtc/random\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename T > GLM_FUNC_DECL tvec3<T, defaultp> glm::ballRand (T Radius)"
Generate a random 3D vector which coordinates are regulary distributed within the volume of a ball of a given radius
.PP
\fBParameters:\fP
.RS 4
\fIRadius\fP 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_random\fP 
.RE
.PP

.SS "template<typename T > GLM_FUNC_DECL tvec2<T, defaultp> glm::circularRand (T Radius)"
Generate a random 2D vector which coordinates are regulary distributed on a circle of a given radius
.PP
\fBParameters:\fP
.RS 4
\fIRadius\fP 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_random\fP 
.RE
.PP

.SS "template<typename T > GLM_FUNC_DECL tvec2<T, defaultp> glm::diskRand (T Radius)"
Generate a random 2D vector which coordinates are regulary distributed within the area of a disk of a given radius
.PP
\fBParameters:\fP
.RS 4
\fIRadius\fP 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_random\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::gaussRand (genType Mean, genType Deviation)"
Generate random numbers in the interval [Min, Max], according a gaussian distribution
.PP
\fBParameters:\fP
.RS 4
\fIMean\fP 
.br
\fIDeviation\fP 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_random\fP 
.RE
.PP

.SS "template<typename genTYpe > GLM_FUNC_DECL genTYpe glm::linearRand (genTYpe Min, genTYpe Max)"
Generate random numbers in the interval [Min, Max], according a linear distribution
.PP
\fBParameters:\fP
.RS 4
\fIMin\fP 
.br
\fIMax\fP 
.RE
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIgenType\fP Value type\&. Currently supported: half (not recommanded), float or double scalars and vectors\&. 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_random\fP 
.RE
.PP

.SS "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType<T, P> glm::linearRand (vecType< T, P > const & Min, vecType< T, P > const & Max)"

.SS "template<typename T > GLM_FUNC_DECL tvec3<T, defaultp> glm::sphericalRand (T Radius)"
Generate a random 3D vector which coordinates are regulary distributed on a sphere of a given radius
.PP
\fBParameters:\fP
.RS 4
\fIRadius\fP 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_random\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
