.TH "gtc_constants" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtc_constants \- GLM_GTC_constants
.PP
Provide a list of constants and precomputed useful values\&.  

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType \fBglm::epsilon\fP ()"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType \fBglm::zero\fP ()"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType \fBglm::one\fP ()"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType \fBglm::pi\fP ()"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType \fBglm::two_pi\fP ()"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType \fBglm::root_pi\fP ()"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType \fBglm::half_pi\fP ()"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType \fBglm::three_over_two_pi\fP ()"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType \fBglm::quarter_pi\fP ()"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType \fBglm::one_over_pi\fP ()"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType \fBglm::one_over_two_pi\fP ()"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType \fBglm::two_over_pi\fP ()"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType \fBglm::four_over_pi\fP ()"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType \fBglm::two_over_root_pi\fP ()"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType \fBglm::one_over_root_two\fP ()"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType \fBglm::root_half_pi\fP ()"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType \fBglm::root_two_pi\fP ()"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType \fBglm::root_ln_four\fP ()"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType \fBglm::e\fP ()"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType \fBglm::euler\fP ()"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType \fBglm::root_two\fP ()"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType \fBglm::root_three\fP ()"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType \fBglm::root_five\fP ()"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType \fBglm::ln_two\fP ()"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType \fBglm::ln_ten\fP ()"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType \fBglm::ln_ln_two\fP ()"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType \fBglm::third\fP ()"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType \fBglm::two_thirds\fP ()"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType \fBglm::golden_ratio\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Provide a list of constants and precomputed useful values\&. 

<\fBglm/gtc/constants\&.hpp\fP> need to be included to use these features\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::e ()"
Return e constant\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_constants\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::epsilon ()"
Return the epsilon constant for floating point types\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_constants\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::euler ()"
Return Euler's constant\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_constants\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::four_over_pi ()"
Return 4 / pi\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_constants\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::golden_ratio ()"
Return the golden ratio constant\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_constants\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::half_pi ()"
Return pi / 2\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_constants\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::ln_ln_two ()"
Return ln(ln(2))\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_constants\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::ln_ten ()"
Return ln(10)\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_constants\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::ln_two ()"
Return ln(2)\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_constants\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::one ()"
Return 1\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_constants\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::one_over_pi ()"
Return 1 / pi\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_constants\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::one_over_root_two ()"
Return 1 / sqrt(2)\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_constants\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::one_over_two_pi ()"
Return 1 / (pi * 2)\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_constants\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::pi ()"
Return the pi constant\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_constants\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::quarter_pi ()"
Return pi / 4\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_constants\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::root_five ()"
Return sqrt(5)\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_constants\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::root_half_pi ()"
Return sqrt(pi / 2)\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_constants\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::root_ln_four ()"
Return sqrt(ln(4))\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_constants\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::root_pi ()"
Return square root of pi\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_constants\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::root_three ()"
Return sqrt(3)\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_constants\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::root_two ()"
Return sqrt(2)\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_constants\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::root_two_pi ()"
Return sqrt(2 * pi)\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_constants\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::third ()"
Return 1 / 3\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_constants\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::three_over_two_pi ()"
Return pi / 2 * 3\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_constants\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::two_over_pi ()"
Return 2 / pi\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_constants\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::two_over_root_pi ()"
Return 2 / sqrt(pi)\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_constants\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::two_pi ()"
Return pi * 2\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_constants\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::two_thirds ()"
Return 2 / 3\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_constants\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL GLM_CONSTEXPR genType glm::zero ()"
Return 0\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_constants\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
