.TH "gtc_matrix_transform" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtc_matrix_transform \- GLM_GTC_matrix_transform
.PP
Defines functions that generate common transformation matrices\&.  

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL tmat4x4< T, P > \fBglm::translate\fP (tmat4x4< T, P > const &m, tvec3< T, P > const &v)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL tmat4x4< T, P > \fBglm::rotate\fP (tmat4x4< T, P > const &m, T angle, tvec3< T, P > const &axis)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL tmat4x4< T, P > \fBglm::scale\fP (tmat4x4< T, P > const &m, tvec3< T, P > const &v)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL tmat4x4< T, defaultp > \fBglm::ortho\fP (T left, T right, T bottom, T top, T zNear, T zFar)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL tmat4x4< T, defaultp > \fBglm::ortho\fP (T left, T right, T bottom, T top)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL tmat4x4< T, defaultp > \fBglm::frustum\fP (T left, T right, T bottom, T top, T near, T far)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL tmat4x4< T, defaultp > \fBglm::perspective\fP (T fovy, T aspect, T near, T far)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL tmat4x4< T, defaultp > \fBglm::perspectiveRH\fP (T fovy, T aspect, T near, T far)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL tmat4x4< T, defaultp > \fBglm::perspectiveLH\fP (T fovy, T aspect, T near, T far)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL tmat4x4< T, defaultp > \fBglm::perspectiveFov\fP (T fov, T width, T height, T near, T far)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL tmat4x4< T, defaultp > \fBglm::perspectiveFovRH\fP (T fov, T width, T height, T near, T far)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL tmat4x4< T, defaultp > \fBglm::perspectiveFovLH\fP (T fov, T width, T height, T near, T far)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL tmat4x4< T, defaultp > \fBglm::infinitePerspective\fP (T fovy, T aspect, T near)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL tmat4x4< T, defaultp > \fBglm::tweakedInfinitePerspective\fP (T fovy, T aspect, T near)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL tmat4x4< T, defaultp > \fBglm::tweakedInfinitePerspective\fP (T fovy, T aspect, T near, T ep)"
.br
.ti -1c
.RI "template<typename T , typename U , precision P> GLM_FUNC_DECL tvec3< T, P > \fBglm::project\fP (tvec3< T, P > const &obj, tmat4x4< T, P > const &model, tmat4x4< T, P > const &proj, tvec4< U, P > const &viewport)"
.br
.ti -1c
.RI "template<typename T , typename U , precision P> GLM_FUNC_DECL tvec3< T, P > \fBglm::unProject\fP (tvec3< T, P > const &win, tmat4x4< T, P > const &model, tmat4x4< T, P > const &proj, tvec4< U, P > const &viewport)"
.br
.ti -1c
.RI "template<typename T , precision P, typename U > GLM_FUNC_DECL tmat4x4< T, P > \fBglm::pickMatrix\fP (tvec2< T, P > const &center, tvec2< T, P > const &delta, tvec4< U, P > const &viewport)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL tmat4x4< T, P > \fBglm::lookAt\fP (tvec3< T, P > const &eye, tvec3< T, P > const &center, tvec3< T, P > const &up)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL tmat4x4< T, P > \fBglm::lookAtRH\fP (tvec3< T, P > const &eye, tvec3< T, P > const &center, tvec3< T, P > const &up)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL tmat4x4< T, P > \fBglm::lookAtLH\fP (tvec3< T, P > const &eye, tvec3< T, P > const &center, tvec3< T, P > const &up)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines functions that generate common transformation matrices\&. 

The matrices generated by this extension use standard OpenGL fixed-function conventions\&. For example, the lookAt function generates a transform from world space into the specific eye space that the projective matrix functions (perspective, ortho, etc) are designed to expect\&. The OpenGL compatibility specifications defines the particular layout of this eye space\&.
.PP
<\fBglm/gtc/matrix_transform\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename T > GLM_FUNC_DECL tmat4x4<T, defaultp> glm::frustum (T left, T right, T bottom, T top, T near, T far)"
Creates a frustum matrix\&.
.PP
\fBParameters:\fP
.RS 4
\fIleft\fP 
.br
\fIright\fP 
.br
\fIbottom\fP 
.br
\fItop\fP 
.br
\fInear\fP 
.br
\fIfar\fP 
.RE
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP Value type used to build the matrix\&. Currently supported: half (not recommanded), float or double\&. 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_transform\fP 
.RE
.PP

.SS "template<typename T > GLM_FUNC_DECL tmat4x4<T, defaultp> glm::infinitePerspective (T fovy, T aspect, T near)"
Creates a matrix for a symmetric perspective-view frustum with far plane at infinite\&.
.PP
\fBParameters:\fP
.RS 4
\fIfovy\fP Specifies the field of view angle, in degrees, in the y direction\&. Expressed in radians\&. 
.br
\fIaspect\fP Specifies the aspect ratio that determines the field of view in the x direction\&. The aspect ratio is the ratio of x (width) to y (height)\&. 
.br
\fInear\fP Specifies the distance from the viewer to the near clipping plane (always positive)\&. 
.RE
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP Value type used to build the matrix\&. Currently supported: half (not recommanded), float or double\&. 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_transform\fP 
.RE
.PP

.SS "template<typename T , precision P> GLM_FUNC_DECL tmat4x4<T, P> glm::lookAt (tvec3< T, P > const & eye, tvec3< T, P > const & center, tvec3< T, P > const & up)"
Build a look at view matrix based on the default handedness\&.
.PP
\fBParameters:\fP
.RS 4
\fIeye\fP Position of the camera 
.br
\fIcenter\fP Position where the camera is looking at 
.br
\fIup\fP Normalized up vector, how the camera is oriented\&. Typically (0, 0, 1) 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_transform\fP 
.PP
- frustum(T const & left, T const & right, T const & bottom, T const & top, T const & nearVal, T const & farVal) frustum(T const & left, T const & right, T const & bottom, T const & top, T const & nearVal, T const & farVal) 
.RE
.PP

.SS "template<typename T , precision P> GLM_FUNC_DECL tmat4x4<T, P> glm::lookAtLH (tvec3< T, P > const & eye, tvec3< T, P > const & center, tvec3< T, P > const & up)"
Build a left handed look at view matrix\&.
.PP
\fBParameters:\fP
.RS 4
\fIeye\fP Position of the camera 
.br
\fIcenter\fP Position where the camera is looking at 
.br
\fIup\fP Normalized up vector, how the camera is oriented\&. Typically (0, 0, 1) 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_transform\fP 
.PP
- frustum(T const & left, T const & right, T const & bottom, T const & top, T const & nearVal, T const & farVal) frustum(T const & left, T const & right, T const & bottom, T const & top, T const & nearVal, T const & farVal) 
.RE
.PP

.SS "template<typename T , precision P> GLM_FUNC_DECL tmat4x4<T, P> glm::lookAtRH (tvec3< T, P > const & eye, tvec3< T, P > const & center, tvec3< T, P > const & up)"
Build a right handed look at view matrix\&.
.PP
\fBParameters:\fP
.RS 4
\fIeye\fP Position of the camera 
.br
\fIcenter\fP Position where the camera is looking at 
.br
\fIup\fP Normalized up vector, how the camera is oriented\&. Typically (0, 0, 1) 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_transform\fP 
.PP
- frustum(T const & left, T const & right, T const & bottom, T const & top, T const & nearVal, T const & farVal) frustum(T const & left, T const & right, T const & bottom, T const & top, T const & nearVal, T const & farVal) 
.RE
.PP

.SS "template<typename T > GLM_FUNC_DECL tmat4x4<T, defaultp> glm::ortho (T left, T right, T bottom, T top, T zNear, T zFar)"
Creates a matrix for an orthographic parallel viewing volume\&.
.PP
\fBParameters:\fP
.RS 4
\fIleft\fP 
.br
\fIright\fP 
.br
\fIbottom\fP 
.br
\fItop\fP 
.br
\fIzNear\fP 
.br
\fIzFar\fP 
.RE
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP Value type used to build the matrix\&. Currently supported: half (not recommanded), float or double\&. 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_transform\fP 
.PP
- glm::ortho(T const & left, T const & right, T const & bottom, T const & top) 
.RE
.PP

.SS "template<typename T > GLM_FUNC_DECL tmat4x4<T, defaultp> glm::ortho (T left, T right, T bottom, T top)"
Creates a matrix for projecting two-dimensional coordinates onto the screen\&.
.PP
\fBParameters:\fP
.RS 4
\fIleft\fP 
.br
\fIright\fP 
.br
\fIbottom\fP 
.br
\fItop\fP 
.RE
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP Value type used to build the matrix\&. Currently supported: half (not recommanded), float or double\&. 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_transform\fP 
.PP
- glm::ortho(T const & left, T const & right, T const & bottom, T const & top, T const & zNear, T const & zFar) 
.RE
.PP

.SS "template<typename T > GLM_FUNC_DECL tmat4x4<T, defaultp> glm::perspective (T fovy, T aspect, T near, T far)"
Creates a matrix for a symetric perspective-view frustum based on the default handedness\&.
.PP
\fBParameters:\fP
.RS 4
\fIfovy\fP Specifies the field of view angle in the y direction\&. Expressed in radians\&. 
.br
\fIaspect\fP Specifies the aspect ratio that determines the field of view in the x direction\&. The aspect ratio is the ratio of x (width) to y (height)\&. 
.br
\fInear\fP Specifies the distance from the viewer to the near clipping plane (always positive)\&. 
.br
\fIfar\fP Specifies the distance from the viewer to the far clipping plane (always positive)\&. 
.RE
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP Value type used to build the matrix\&. Currently supported: half (not recommanded), float or double\&. 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_transform\fP 
.RE
.PP

.SS "template<typename T > GLM_FUNC_DECL tmat4x4<T, defaultp> glm::perspectiveFov (T fov, T width, T height, T near, T far)"
Builds a perspective projection matrix based on a field of view and the default handedness\&.
.PP
\fBParameters:\fP
.RS 4
\fIfov\fP Expressed in radians\&. 
.br
\fIwidth\fP 
.br
\fIheight\fP 
.br
\fInear\fP Specifies the distance from the viewer to the near clipping plane (always positive)\&. 
.br
\fIfar\fP Specifies the distance from the viewer to the far clipping plane (always positive)\&. 
.RE
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP Value type used to build the matrix\&. Currently supported: half (not recommanded), float or double\&. 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_transform\fP 
.RE
.PP

.SS "template<typename T > GLM_FUNC_DECL tmat4x4<T, defaultp> glm::perspectiveFovLH (T fov, T width, T height, T near, T far)"
Builds a left handed perspective projection matrix based on a field of view\&.
.PP
\fBParameters:\fP
.RS 4
\fIfov\fP Expressed in radians\&. 
.br
\fIwidth\fP 
.br
\fIheight\fP 
.br
\fInear\fP Specifies the distance from the viewer to the near clipping plane (always positive)\&. 
.br
\fIfar\fP Specifies the distance from the viewer to the far clipping plane (always positive)\&. 
.RE
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP Value type used to build the matrix\&. Currently supported: half (not recommanded), float or double\&. 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_transform\fP 
.RE
.PP
todo max(width , Height) / min(width , Height)? 
.SS "template<typename T > GLM_FUNC_DECL tmat4x4<T, defaultp> glm::perspectiveFovRH (T fov, T width, T height, T near, T far)"
Builds a right handed perspective projection matrix based on a field of view\&.
.PP
\fBParameters:\fP
.RS 4
\fIfov\fP Expressed in radians\&. 
.br
\fIwidth\fP 
.br
\fIheight\fP 
.br
\fInear\fP Specifies the distance from the viewer to the near clipping plane (always positive)\&. 
.br
\fIfar\fP Specifies the distance from the viewer to the far clipping plane (always positive)\&. 
.RE
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP Value type used to build the matrix\&. Currently supported: half (not recommanded), float or double\&. 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_transform\fP 
.RE
.PP
todo max(width , Height) / min(width , Height)? 
.SS "template<typename T > GLM_FUNC_DECL tmat4x4<T, defaultp> glm::perspectiveLH (T fovy, T aspect, T near, T far)"
Creates a matrix for a left handed, symetric perspective-view frustum\&.
.PP
\fBParameters:\fP
.RS 4
\fIfovy\fP Specifies the field of view angle, in degrees, in the y direction\&. Expressed in radians\&. 
.br
\fIaspect\fP Specifies the aspect ratio that determines the field of view in the x direction\&. The aspect ratio is the ratio of x (width) to y (height)\&. 
.br
\fInear\fP Specifies the distance from the viewer to the near clipping plane (always positive)\&. 
.br
\fIfar\fP Specifies the distance from the viewer to the far clipping plane (always positive)\&. 
.RE
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP Value type used to build the matrix\&. Currently supported: half (not recommanded), float or double\&. 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_transform\fP 
.RE
.PP

.SS "template<typename T > GLM_FUNC_DECL tmat4x4<T, defaultp> glm::perspectiveRH (T fovy, T aspect, T near, T far)"
Creates a matrix for a right handed, symetric perspective-view frustum\&.
.PP
\fBParameters:\fP
.RS 4
\fIfovy\fP Specifies the field of view angle, in degrees, in the y direction\&. Expressed in radians\&. 
.br
\fIaspect\fP Specifies the aspect ratio that determines the field of view in the x direction\&. The aspect ratio is the ratio of x (width) to y (height)\&. 
.br
\fInear\fP Specifies the distance from the viewer to the near clipping plane (always positive)\&. 
.br
\fIfar\fP Specifies the distance from the viewer to the far clipping plane (always positive)\&. 
.RE
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP Value type used to build the matrix\&. Currently supported: half (not recommanded), float or double\&. 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_transform\fP 
.RE
.PP

.SS "template<typename T , precision P, typename U > GLM_FUNC_DECL tmat4x4<T, P> glm::pickMatrix (tvec2< T, P > const & center, tvec2< T, P > const & delta, tvec4< U, P > const & viewport)"
Define a picking region
.PP
\fBParameters:\fP
.RS 4
\fIcenter\fP 
.br
\fIdelta\fP 
.br
\fIviewport\fP 
.RE
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP Native type used for the computation\&. Currently supported: half (not recommanded), float or double\&. 
.br
\fIU\fP Currently supported: Floating-point types and integer types\&. 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_transform\fP 
.RE
.PP

.SS "template<typename T , typename U , precision P> GLM_FUNC_DECL tvec3<T, P> glm::project (tvec3< T, P > const & obj, tmat4x4< T, P > const & model, tmat4x4< T, P > const & proj, tvec4< U, P > const & viewport)"
Map the specified object coordinates (obj\&.x, obj\&.y, obj\&.z) into window coordinates\&.
.PP
\fBParameters:\fP
.RS 4
\fIobj\fP Specify the object coordinates\&. 
.br
\fImodel\fP Specifies the current modelview matrix 
.br
\fIproj\fP Specifies the current projection matrix 
.br
\fIviewport\fP Specifies the current viewport 
.RE
.PP
\fBReturns:\fP
.RS 4
Return the computed window coordinates\&. 
.RE
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP Native type used for the computation\&. Currently supported: half (not recommanded), float or double\&. 
.br
\fIU\fP Currently supported: Floating-point types and integer types\&. 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_transform\fP 
.RE
.PP

.SS "template<typename T , precision P> GLM_FUNC_DECL tmat4x4<T, P> glm::rotate (tmat4x4< T, P > const & m, T angle, tvec3< T, P > const & axis)"
Builds a rotation 4 * 4 matrix created from an axis vector and an angle\&.
.PP
\fBParameters:\fP
.RS 4
\fIm\fP \fBInput\fP matrix multiplied by this rotation matrix\&. 
.br
\fIangle\fP Rotation angle expressed in radians\&. 
.br
\fIaxis\fP Rotation axis, recommended to be normalized\&. 
.RE
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP Value type used to build the matrix\&. Supported: half, float or double\&. 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_transform\fP 
.PP
- rotate(tmat4x4<T, P> const & m, T angle, T x, T y, T z) 
.PP
- \fBrotate(T angle, tvec3<T, P> const & v)\fP 
.RE
.PP

.SS "template<typename T , precision P> GLM_FUNC_DECL tmat4x4<T, P> glm::scale (tmat4x4< T, P > const & m, tvec3< T, P > const & v)"
Builds a scale 4 * 4 matrix created from 3 scalars\&.
.PP
\fBParameters:\fP
.RS 4
\fIm\fP \fBInput\fP matrix multiplied by this scale matrix\&. 
.br
\fIv\fP Ratio of scaling for each axis\&. 
.RE
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP Value type used to build the matrix\&. Currently supported: half (not recommanded), float or double\&. 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_transform\fP 
.PP
- scale(tmat4x4<T, P> const & m, T x, T y, T z) 
.PP
- \fBscale(tvec3<T, P> const & v)\fP 
.RE
.PP

.SS "template<typename T , precision P> GLM_FUNC_DECL tmat4x4<T, P> glm::translate (tmat4x4< T, P > const & m, tvec3< T, P > const & v)"
Builds a translation 4 * 4 matrix created from a vector of 3 components\&.
.PP
\fBParameters:\fP
.RS 4
\fIm\fP \fBInput\fP matrix multiplied by this translation matrix\&. 
.br
\fIv\fP Coordinates of a translation vector\&. 
.RE
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP Value type used to build the matrix\&. Currently supported: half (not recommanded), float or double\&. 
.PP
.nf
#include <glm/glm\&.hpp>
#include <glm/gtc/matrix_transform\&.hpp>
\&.\&.\&.
glm::mat4 m = glm::translate(glm::mat4(1\&.0f), glm::vec3(1\&.0f));
// m[0][0] == 1\&.0f, m[0][1] == 0\&.0f, m[0][2] == 0\&.0f, m[0][3] == 0\&.0f
// m[1][0] == 0\&.0f, m[1][1] == 1\&.0f, m[1][2] == 0\&.0f, m[1][3] == 0\&.0f
// m[2][0] == 0\&.0f, m[2][1] == 0\&.0f, m[2][2] == 1\&.0f, m[2][3] == 0\&.0f
// m[3][0] == 1\&.0f, m[3][1] == 1\&.0f, m[3][2] == 1\&.0f, m[3][3] == 1\&.0f

.fi
.PP
 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_transform\fP 
.PP
- translate(tmat4x4<T, P> const & m, T x, T y, T z) 
.PP
- \fBtranslate(tvec3<T, P> const & v)\fP 
.RE
.PP

.SS "template<typename T > GLM_FUNC_DECL tmat4x4<T, defaultp> glm::tweakedInfinitePerspective (T fovy, T aspect, T near)"
Creates a matrix for a symmetric perspective-view frustum with far plane at infinite for graphics hardware that doesn't support depth clamping\&.
.PP
\fBParameters:\fP
.RS 4
\fIfovy\fP Specifies the field of view angle, in degrees, in the y direction\&. Expressed in radians\&. 
.br
\fIaspect\fP Specifies the aspect ratio that determines the field of view in the x direction\&. The aspect ratio is the ratio of x (width) to y (height)\&. 
.br
\fInear\fP Specifies the distance from the viewer to the near clipping plane (always positive)\&. 
.RE
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP Value type used to build the matrix\&. Currently supported: half (not recommanded), float or double\&. 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_transform\fP 
.RE
.PP

.SS "template<typename T > GLM_FUNC_DECL tmat4x4<T, defaultp> glm::tweakedInfinitePerspective (T fovy, T aspect, T near, T ep)"
Creates a matrix for a symmetric perspective-view frustum with far plane at infinite for graphics hardware that doesn't support depth clamping\&.
.PP
\fBParameters:\fP
.RS 4
\fIfovy\fP Specifies the field of view angle, in degrees, in the y direction\&. Expressed in radians\&. 
.br
\fIaspect\fP Specifies the aspect ratio that determines the field of view in the x direction\&. The aspect ratio is the ratio of x (width) to y (height)\&. 
.br
\fInear\fP Specifies the distance from the viewer to the near clipping plane (always positive)\&. 
.br
\fIep\fP 
.RE
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP Value type used to build the matrix\&. Currently supported: half (not recommanded), float or double\&. 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_transform\fP 
.RE
.PP

.SS "template<typename T , typename U , precision P> GLM_FUNC_DECL tvec3<T, P> glm::unProject (tvec3< T, P > const & win, tmat4x4< T, P > const & model, tmat4x4< T, P > const & proj, tvec4< U, P > const & viewport)"
Map the specified window coordinates (win\&.x, win\&.y, win\&.z) into object coordinates\&.
.PP
\fBParameters:\fP
.RS 4
\fIwin\fP Specify the window coordinates to be mapped\&. 
.br
\fImodel\fP Specifies the modelview matrix 
.br
\fIproj\fP Specifies the projection matrix 
.br
\fIviewport\fP Specifies the viewport 
.RE
.PP
\fBReturns:\fP
.RS 4
Returns the computed object coordinates\&. 
.RE
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIT\fP Native type used for the computation\&. Currently supported: half (not recommanded), float or double\&. 
.br
\fIU\fP Currently supported: Floating-point types and integer types\&. 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_transform\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
