.TH "gtc_matrix_inverse" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtc_matrix_inverse \- GLM_GTC_matrix_inverse
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::affineInverse\fP (genType const &m)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::inverseTranspose\fP (genType const &m)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines additional matrix inverting functions\&. <\fBglm/gtc/matrix_inverse\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename genType > GLM_FUNC_DECL genType glm::affineInverse (genType const & m)"
Fast matrix inverse for affine matrix\&.
.PP
\fBParameters:\fP
.RS 4
\fIm\fP \fBInput\fP matrix to invert\&. 
.RE
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIgenType\fP Squared floating-point matrix: half, float or double\&. Inverse of matrix based of half-precision floating point value is highly innacurate\&. 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_inverse\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::inverseTranspose (genType const & m)"
Compute the inverse transpose of a matrix\&.
.PP
\fBParameters:\fP
.RS 4
\fIm\fP \fBInput\fP matrix to invert transpose\&. 
.RE
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIgenType\fP Squared floating-point matrix: half, float or double\&. Inverse of matrix based of half-precision floating point value is highly innacurate\&. 
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_matrix_inverse\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
