.TH "gtc_color_space" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtc_color_space \- GLM_GTC_color_space
.PP
Allow to perform bit operations on integer values\&.  

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType< T, P > \fBglm::convertLinearToSRGB\fP (vecType< T, P > const &ColorLinear)"
.br
.RI "\fIConvert a linear color to sRGB color using a standard gamma correction\&. \fP"
.ti -1c
.RI "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType< T, P > \fBglm::convertLinearToSRGB\fP (vecType< T, P > const &ColorLinear, T Gamma)"
.br
.RI "\fIConvert a linear color to sRGB color using a custom gamma correction\&. \fP"
.ti -1c
.RI "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType< T, P > \fBglm::convertSRGBToLinear\fP (vecType< T, P > const &ColorSRGB)"
.br
.RI "\fIConvert a sRGB color to linear color using a standard gamma correction\&. \fP"
.ti -1c
.RI "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType< T, P > \fBglm::convertSRGBToLinear\fP (vecType< T, P > const &ColorSRGB, T Gamma)"
.br
.RI "\fIConvert a sRGB color to linear color using a custom gamma correction\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Allow to perform bit operations on integer values\&. 

<glm/gtc/color\&.hpp> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType<T, P> glm::convertLinearToSRGB (vecType< T, P > const & ColorLinear)"

.PP
Convert a linear color to sRGB color using a standard gamma correction\&. 
.SS "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType<T, P> glm::convertLinearToSRGB (vecType< T, P > const & ColorLinear, T Gamma)"

.PP
Convert a linear color to sRGB color using a custom gamma correction\&. 
.SS "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType<T, P> glm::convertSRGBToLinear (vecType< T, P > const & ColorSRGB)"

.PP
Convert a sRGB color to linear color using a standard gamma correction\&. 
.SS "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType<T, P> glm::convertSRGBToLinear (vecType< T, P > const & ColorSRGB, T Gamma)"

.PP
Convert a sRGB color to linear color using a custom gamma correction\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
