.TH "gtc_ulp" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtc_ulp \- GLM_GTC_ulp
.PP
Allow the measurement of the accuracy of a function against a reference implementation\&. This extension works on floating-point data and provide results in ULP\&. <\fBglm/gtc/ulp\&.hpp\fP> need to be included to use these features\&.  

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::next_float\fP (genType const &x)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::prev_float\fP (genType const &x)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::next_float\fP (genType const &x, \fBuint\fP const &Distance)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::prev_float\fP (genType const &x, \fBuint\fP const &Distance)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL \fBuint\fP \fBglm::float_distance\fP (T const &x, T const &y)"
.br
.ti -1c
.RI "template<typename T , template< typename > class vecType> GLM_FUNC_DECL vecType< \fBuint\fP > \fBglm::float_distance\fP (vecType< T > const &x, vecType< T > const &y)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Allow the measurement of the accuracy of a function against a reference implementation\&. This extension works on floating-point data and provide results in ULP\&. <\fBglm/gtc/ulp\&.hpp\fP> need to be included to use these features\&. 


.SH "Function Documentation"
.PP 
.SS "template<typename T > GLM_FUNC_DECL \fBuint\fP glm::float_distance (T const & x, T const & y)"
Return the distance in the number of ULP between 2 scalars\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_ulp\fP 
.RE
.PP

.SS "template<typename T , template< typename > class vecType> GLM_FUNC_DECL vecType<\fBuint\fP> glm::float_distance (vecType< T > const & x, vecType< T > const & y)"
Return the distance in the number of ULP between 2 vectors\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_ulp\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::next_float (genType const & x)"
Return the next ULP value(s) after the input value(s)\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_ulp\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::next_float (genType const & x, \fBuint\fP const & Distance)"
Return the value(s) ULP distance after the input value(s)\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_ulp\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::prev_float (genType const & x)"
Return the previous ULP value(s) before the input value(s)\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_ulp\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::prev_float (genType const & x, \fBuint\fP const & Distance)"
Return the value(s) ULP distance before the input value(s)\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_ulp\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
