.TH "gtx_simd_quat" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_simd_quat \- GLM_GTX_simd_quat
.PP
SIMD implementation of quat type\&.  
SIMD implementation of quat type\&. 

<\fBglm/gtx/simd_quat\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
