.TH "gtx_extend" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_extend \- GLM_GTX_extend
.PP
Extend a position from a source to a position at a defined length\&.  

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::extend\fP (genType const &Origin, genType const &Source, typename genType::value_type const Length)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Extend a position from a source to a position at a defined length\&. 

<\fBglm/gtx/extend\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename genType > GLM_FUNC_DECL genType glm::extend (genType const & Origin, genType const & Source, typename genType::value_type const Length)"
Extends of Length the Origin position using the (Source - Origin) direction\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_extend\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
