.TH "gtx_matrix_cross_product" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_matrix_cross_product \- GLM_GTX_matrix_cross_product
.PP
Build cross product matrices\&.  

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL tmat3x3< T, P > \fBglm::matrixCross3\fP (tvec3< T, P > const &x)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL tmat4x4< T, P > \fBglm::matrixCross4\fP (tvec3< T, P > const &x)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Build cross product matrices\&. 

<\fBglm/gtx/matrix_cross_product\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename T , precision P> GLM_FUNC_DECL tmat3x3<T, P> glm::matrixCross3 (tvec3< T, P > const & x)"
Build a cross product matrix\&. From GLM_GTX_matrix_cross_product extension\&. 
.SS "template<typename T , precision P> GLM_FUNC_DECL tmat4x4<T, P> glm::matrixCross4 (tvec3< T, P > const & x)"
Build a cross product matrix\&. From GLM_GTX_matrix_cross_product extension\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
