.TH "gtx_extented_min_max" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_extented_min_max \- GLM_GTX_extented_min_max
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL T \fBglm::min\fP (T const &x, T const &y, T const &z)"
.br
.ti -1c
.RI "template<typename T , template< typename > class C> GLM_FUNC_DECL C< T > \fBglm::min\fP (C< T > const &x, typename C< T >::T const &y, typename C< T >::T const &z)"
.br
.ti -1c
.RI "template<typename T , template< typename > class C> GLM_FUNC_DECL C< T > \fBglm::min\fP (C< T > const &x, C< T > const &y, C< T > const &z)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL T \fBglm::min\fP (T const &x, T const &y, T const &z, T const &w)"
.br
.ti -1c
.RI "template<typename T , template< typename > class C> GLM_FUNC_DECL C< T > \fBglm::min\fP (C< T > const &x, typename C< T >::T const &y, typename C< T >::T const &z, typename C< T >::T const &w)"
.br
.ti -1c
.RI "template<typename T , template< typename > class C> GLM_FUNC_DECL C< T > \fBglm::min\fP (C< T > const &x, C< T > const &y, C< T > const &z, C< T > const &w)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL T \fBglm::max\fP (T const &x, T const &y, T const &z)"
.br
.ti -1c
.RI "template<typename T , template< typename > class C> GLM_FUNC_DECL C< T > \fBglm::max\fP (C< T > const &x, typename C< T >::T const &y, typename C< T >::T const &z)"
.br
.ti -1c
.RI "template<typename T , template< typename > class C> GLM_FUNC_DECL C< T > \fBglm::max\fP (C< T > const &x, C< T > const &y, C< T > const &z)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL T \fBglm::max\fP (T const &x, T const &y, T const &z, T const &w)"
.br
.ti -1c
.RI "template<typename T , template< typename > class C> GLM_FUNC_DECL C< T > \fBglm::max\fP (C< T > const &x, typename C< T >::T const &y, typename C< T >::T const &z, typename C< T >::T const &w)"
.br
.ti -1c
.RI "template<typename T , template< typename > class C> GLM_FUNC_DECL C< T > \fBglm::max\fP (C< T > const &x, C< T > const &y, C< T > const &z, C< T > const &w)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Min and max functions for 3 to 4 parameters\&.
.PP
<\fBglm/gtx/extented_min_max\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename T > GLM_FUNC_DECL T glm::max (T const & x, T const & y, T const & z)"
Return the maximum component-wise values of 3 inputs 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_extented_min_max\fP 
.RE
.PP

.SS "template<typename T , template< typename > class C> GLM_FUNC_DECL C<T> glm::max (C< T > const & x, typename C< T >::T const & y, typename C< T >::T const & z)"
Return the maximum component-wise values of 3 inputs 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_extented_min_max\fP 
.RE
.PP

.SS "template<typename T , template< typename > class C> GLM_FUNC_DECL C<T> glm::max (C< T > const & x, C< T > const & y, C< T > const & z)"
Return the maximum component-wise values of 3 inputs 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_extented_min_max\fP 
.RE
.PP

.SS "template<typename T > GLM_FUNC_DECL T glm::max (T const & x, T const & y, T const & z, T const & w)"
Return the maximum component-wise values of 4 inputs 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_extented_min_max\fP 
.RE
.PP

.SS "template<typename T , template< typename > class C> GLM_FUNC_DECL C<T> glm::max (C< T > const & x, typename C< T >::T const & y, typename C< T >::T const & z, typename C< T >::T const & w)"
Return the maximum component-wise values of 4 inputs 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_extented_min_max\fP 
.RE
.PP

.SS "template<typename T , template< typename > class C> GLM_FUNC_DECL C<T> glm::max (C< T > const & x, C< T > const & y, C< T > const & z, C< T > const & w)"
Return the maximum component-wise values of 4 inputs 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_extented_min_max\fP 
.RE
.PP

.SS "template<typename T > GLM_FUNC_DECL T glm::min (T const & x, T const & y, T const & z)"
Return the minimum component-wise values of 3 inputs 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_extented_min_max\fP 
.RE
.PP

.SS "template<typename T , template< typename > class C> GLM_FUNC_DECL C<T> glm::min (C< T > const & x, typename C< T >::T const & y, typename C< T >::T const & z)"
Return the minimum component-wise values of 3 inputs 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_extented_min_max\fP 
.RE
.PP

.SS "template<typename T , template< typename > class C> GLM_FUNC_DECL C<T> glm::min (C< T > const & x, C< T > const & y, C< T > const & z)"
Return the minimum component-wise values of 3 inputs 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_extented_min_max\fP 
.RE
.PP

.SS "template<typename T > GLM_FUNC_DECL T glm::min (T const & x, T const & y, T const & z, T const & w)"
Return the minimum component-wise values of 4 inputs 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_extented_min_max\fP 
.RE
.PP

.SS "template<typename T , template< typename > class C> GLM_FUNC_DECL C<T> glm::min (C< T > const & x, typename C< T >::T const & y, typename C< T >::T const & z, typename C< T >::T const & w)"
Return the minimum component-wise values of 4 inputs 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_extented_min_max\fP 
.RE
.PP

.SS "template<typename T , template< typename > class C> GLM_FUNC_DECL C<T> glm::min (C< T > const & x, C< T > const & y, C< T > const & z, C< T > const & w)"
Return the minimum component-wise values of 4 inputs 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_extented_min_max\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
