.TH "gtx_optimum_pow" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_optimum_pow \- GLM_GTX_optimum_pow
.PP
Integer exponentiation of power functions\&.  

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::gtx::pow2\fP (genType const &x)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::gtx::pow3\fP (genType const &x)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::gtx::pow4\fP (genType const &x)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Integer exponentiation of power functions\&. 

<\fBglm/gtx/optimum_pow\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename genType > GLM_FUNC_DECL genType glm::gtx::pow2 (genType const & x)"
Returns x raised to the power of 2\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_optimum_pow\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::gtx::pow3 (genType const & x)"
Returns x raised to the power of 3\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_optimum_pow\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::gtx::pow4 (genType const & x)"
Returns x raised to the power of 4\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_optimum_pow\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
