.TH "gtx_matrix_decompose" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_matrix_decompose \- GLM_GTX_matrix_decompose
.PP
Decomposes a model matrix to translations, rotation and scale components\&.  

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL bool \fBglm::decompose\fP (tmat4x4< T, P > const &modelMatrix, tvec3< T, P > &scale, tquat< T, P > &orientation, tvec3< T, P > &translation, tvec3< T, P > &skew, tvec4< T, P > &perspective)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Decomposes a model matrix to translations, rotation and scale components\&. 

<\fBglm/gtx/matrix_decompose\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename T , precision P> GLM_FUNC_DECL bool glm::decompose (tmat4x4< T, P > const & ModelMatrix, tvec3< T, P > & Scale, \fBtquat\fP< T, P > & Orientation, tvec3< T, P > & Translation, tvec3< T, P > & Skew, tvec4< T, P > & Perspective)"
Decomposes a model matrix to translations, rotation and scale components 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_matrix_decompose\fP
.RE
.PP
\fBMatrix\fP decompose http://www.opensource.apple.com/source/WebCore/WebCore-514/platform/graphics/transforms/TransformationMatrix.cpp Decomposes the mode matrix to translations,rotation scale components TODO: Fixme! 
.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
