.TH "gtx_projection" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_projection \- GLM_GTX_projection
.PP
Projection of a vector to other one\&.  

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename vecType > GLM_FUNC_DECL vecType \fBglm::proj\fP (vecType const &x, vecType const &Normal)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Projection of a vector to other one\&. 

<\fBglm/gtx/projection\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename vecType > GLM_FUNC_DECL vecType glm::proj (vecType const & x, vecType const & Normal)"
Projects x on Normal\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_projection\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
