.TH "gtx_std_based_type" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_std_based_type \- GLM_GTX_std_based_type
.PP
Adds vector types based on STL value types\&. <\fBglm/gtx/std_based_type\&.hpp\fP> need to be included to use these functionalities\&.  

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef tvec1< std::size_t, defaultp > \fBglm::size1\fP"
.br
.ti -1c
.RI "typedef tvec2< std::size_t, defaultp > \fBglm::size2\fP"
.br
.ti -1c
.RI "typedef tvec3< std::size_t, defaultp > \fBglm::size3\fP"
.br
.ti -1c
.RI "typedef tvec4< std::size_t, defaultp > \fBglm::size4\fP"
.br
.ti -1c
.RI "typedef tvec1< std::size_t, defaultp > \fBglm::size1_t\fP"
.br
.ti -1c
.RI "typedef tvec2< std::size_t, defaultp > \fBglm::size2_t\fP"
.br
.ti -1c
.RI "typedef tvec3< std::size_t, defaultp > \fBglm::size3_t\fP"
.br
.ti -1c
.RI "typedef tvec4< std::size_t, defaultp > \fBglm::size4_t\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Adds vector types based on STL value types\&. <\fBglm/gtx/std_based_type\&.hpp\fP> need to be included to use these functionalities\&. 


.SH "Typedef Documentation"
.PP 
.SS "typedef tvec1<std::size_t, defaultp> \fBglm::size1\fP"
\fBVector\fP type based of one std::size_t component\&. 
.PP
\fBSee also:\fP
.RS 4
GLM_GTX_std_based_type 
.RE
.PP

.SS "typedef tvec1<std::size_t, defaultp> \fBglm::size1_t\fP"
\fBVector\fP type based of one std::size_t component\&. 
.PP
\fBSee also:\fP
.RS 4
GLM_GTX_std_based_type 
.RE
.PP

.SS "typedef tvec2<std::size_t, defaultp> \fBglm::size2\fP"
\fBVector\fP type based of two std::size_t components\&. 
.PP
\fBSee also:\fP
.RS 4
GLM_GTX_std_based_type 
.RE
.PP

.SS "typedef tvec2<std::size_t, defaultp> \fBglm::size2_t\fP"
\fBVector\fP type based of two std::size_t components\&. 
.PP
\fBSee also:\fP
.RS 4
GLM_GTX_std_based_type 
.RE
.PP

.SS "typedef tvec3<std::size_t, defaultp> \fBglm::size3\fP"
\fBVector\fP type based of three std::size_t components\&. 
.PP
\fBSee also:\fP
.RS 4
GLM_GTX_std_based_type 
.RE
.PP

.SS "typedef tvec3<std::size_t, defaultp> \fBglm::size3_t\fP"
\fBVector\fP type based of three std::size_t components\&. 
.PP
\fBSee also:\fP
.RS 4
GLM_GTX_std_based_type 
.RE
.PP

.SS "typedef tvec4<std::size_t, defaultp> \fBglm::size4\fP"
\fBVector\fP type based of four std::size_t components\&. 
.PP
\fBSee also:\fP
.RS 4
GLM_GTX_std_based_type 
.RE
.PP

.SS "typedef tvec4<std::size_t, defaultp> \fBglm::size4_t\fP"
\fBVector\fP type based of four std::size_t components\&. 
.PP
\fBSee also:\fP
.RS 4
GLM_GTX_std_based_type 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
