.TH "gtx_fast_exponential" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_fast_exponential \- GLM_GTX_fast_exponential
.PP
Fast but less accurate implementations of exponential based functions\&.  

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::fastPow\fP (genType x, genType y)"
.br
.ti -1c
.RI "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType< T, P > \fBglm::fastPow\fP (vecType< T, P > const &x, vecType< T, P > const &y)"
.br
.ti -1c
.RI "template<typename genTypeT , typename genTypeU > GLM_FUNC_DECL genTypeT \fBglm::fastPow\fP (genTypeT x, genTypeU y)"
.br
.ti -1c
.RI "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType< T, P > \fBglm::fastPow\fP (vecType< T, P > const &x)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL T \fBglm::fastExp\fP (T x)"
.br
.ti -1c
.RI "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType< T, P > \fBglm::fastExp\fP (vecType< T, P > const &x)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL T \fBglm::fastLog\fP (T x)"
.br
.ti -1c
.RI "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType< T, P > \fBglm::fastLog\fP (vecType< T, P > const &x)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL T \fBglm::fastExp2\fP (T x)"
.br
.ti -1c
.RI "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType< T, P > \fBglm::fastExp2\fP (vecType< T, P > const &x)"
.br
.ti -1c
.RI "template<typename T > GLM_FUNC_DECL T \fBglm::fastLog2\fP (T x)"
.br
.ti -1c
.RI "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType< T, P > \fBglm::fastLog2\fP (vecType< T, P > const &x)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Fast but less accurate implementations of exponential based functions\&. 

<\fBglm/gtx/fast_exponential\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename T > GLM_FUNC_DECL T glm::fastExp (T x)"
Faster than the common exp function but less accurate\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_fast_exponential\fP 
.RE
.PP

.SS "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType<T, P> glm::fastExp (vecType< T, P > const & x)"
Faster than the common exp function but less accurate\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_fast_exponential\fP 
.RE
.PP

.SS "template<typename T > GLM_FUNC_DECL T glm::fastExp2 (T x)"
Faster than the common exp2 function but less accurate\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_fast_exponential\fP 
.RE
.PP

.SS "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType<T, P> glm::fastExp2 (vecType< T, P > const & x)"
Faster than the common exp2 function but less accurate\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_fast_exponential\fP 
.RE
.PP

.SS "template<typename T > GLM_FUNC_DECL T glm::fastLog (T x)"
Faster than the common log function but less accurate\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_fast_exponential\fP 
.RE
.PP

.SS "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType<T, P> glm::fastLog (vecType< T, P > const & x)"
Faster than the common exp2 function but less accurate\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_fast_exponential\fP 
.RE
.PP

.SS "template<typename T > GLM_FUNC_DECL T glm::fastLog2 (T x)"
Faster than the common log2 function but less accurate\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_fast_exponential\fP 
.RE
.PP

.SS "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType<T, P> glm::fastLog2 (vecType< T, P > const & x)"
Faster than the common log2 function but less accurate\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_fast_exponential\fP 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::fastPow (genType x, genType y)"
Faster than the common pow function but less accurate\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_fast_exponential\fP 
.RE
.PP

.SS "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType<T, P> glm::fastPow (vecType< T, P > const & x, vecType< T, P > const & y)"
Faster than the common pow function but less accurate\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_fast_exponential\fP 
.RE
.PP

.SS "template<typename genTypeT , typename genTypeU > GLM_FUNC_DECL genTypeT glm::fastPow (genTypeT x, genTypeU y)"
Faster than the common pow function but less accurate\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_fast_exponential\fP 
.RE
.PP

.SS "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType<T, P> glm::fastPow (vecType< T, P > const & x)"
Faster than the common pow function but less accurate\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_fast_exponential\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
