.TH "gtx_log_base" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_log_base \- GLM_GTX_log_base
.PP
Logarithm for any base\&. base can be a vector or a scalar\&.  

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::log\fP (genType x, genType base)"
.br
.ti -1c
.RI "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType< T, P > \fBglm::sign\fP (vecType< T, P > const &x, vecType< T, P > const &base)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Logarithm for any base\&. base can be a vector or a scalar\&. 

<\fBglm/gtx/log_base\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename genType > GLM_FUNC_DECL genType glm::log (genType x, genType base)"
Logarithm for any base\&. From GLM_GTX_log_base\&. 
.SS "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType<T, P> glm::sign (vecType< T, P > const & x, vecType< T, P > const & base)"
Logarithm for any base\&. From GLM_GTX_log_base\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
