.TH "gtx_fast_square_root" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_fast_square_root \- GLM_GTX_fast_square_root
.PP
Fast but less accurate implementations of square root based functions\&.  

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::fastSqrt\fP (genType x)"
.br
.ti -1c
.RI "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType< T, P > \fBglm::fastSqrt\fP (vecType< T, P > const &x)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::fastInverseSqrt\fP (genType x)"
.br
.ti -1c
.RI "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType< T, P > \fBglm::fastInverseSqrt\fP (vecType< T, P > const &x)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::fastLength\fP (genType x)"
.br
.ti -1c
.RI "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL T \fBglm::fastLength\fP (vecType< T, P > const &x)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::fastDistance\fP (genType x, genType y)"
.br
.ti -1c
.RI "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL T \fBglm::fastDistance\fP (vecType< T, P > const &x, vecType< T, P > const &y)"
.br
.ti -1c
.RI "template<typename genType > GLM_FUNC_DECL genType \fBglm::fastNormalize\fP (genType const &x)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Fast but less accurate implementations of square root based functions\&. 


.IP "\(bu" 2
Sqrt optimisation based on Newton's method, www\&.gamedev\&.net/community/forums/topic\&.asp?topic id=139956
.PP
.PP
<\fBglm/gtx/fast_square_root\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename genType > GLM_FUNC_DECL genType glm::fastDistance (genType x, genType y)"
Faster than the common distance function but less accurate\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_fast_square_root\fP extension\&. 
.RE
.PP

.SS "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL T glm::fastDistance (vecType< T, P > const & x, vecType< T, P > const & y)"
Faster than the common distance function but less accurate\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_fast_square_root\fP extension\&. 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::fastInverseSqrt (genType x)"
Faster than the common inversesqrt function but less accurate\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_fast_square_root\fP extension\&. 
.RE
.PP

.SS "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType<T, P> glm::fastInverseSqrt (vecType< T, P > const & x)"
Faster than the common inversesqrt function but less accurate\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_fast_square_root\fP extension\&. 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::fastLength (genType x)"
Faster than the common length function but less accurate\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_fast_square_root\fP extension\&. 
.RE
.PP

.SS "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL T glm::fastLength (vecType< T, P > const & x)"
Faster than the common length function but less accurate\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_fast_square_root\fP extension\&. 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::fastNormalize (genType const & x)"
Faster than the common normalize function but less accurate\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_fast_square_root\fP extension\&. 
.RE
.PP

.SS "template<typename genType > GLM_FUNC_DECL genType glm::fastSqrt (genType x)"
Faster than the common sqrt function but less accurate\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_fast_square_root\fP extension\&. 
.RE
.PP

.SS "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType<T, P> glm::fastSqrt (vecType< T, P > const & x)"
Faster than the common sqrt function but less accurate\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_fast_square_root\fP extension\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
