.TH "gtx_simd_mat4" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_simd_mat4 \- GLM_GTX_simd_mat4
.PP
SIMD implementation of mat4 type\&.  
SIMD implementation of mat4 type\&. 

<\fBglm/gtx/simd_mat4\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
