.TH "gtx_raw_data" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_raw_data \- GLM_GTX_raw_data
.PP
Projection of a vector to other one\&.  

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBdetail::uint8\fP \fBglm::byte\fP"
.br
.ti -1c
.RI "typedef \fBdetail::uint16\fP \fBglm::word\fP"
.br
.ti -1c
.RI "typedef \fBdetail::uint32\fP \fBglm::dword\fP"
.br
.ti -1c
.RI "typedef detail::uint64 \fBglm::qword\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Projection of a vector to other one\&. 

<\fBglm/gtx/raw_data\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBdetail::uint8\fP \fBglm::byte\fP"
Type for byte numbers\&. From GLM_GTX_raw_data extension\&. 
.SS "typedef \fBdetail::uint32\fP \fBglm::dword\fP"
Type for dword numbers\&. From GLM_GTX_raw_data extension\&. 
.SS "typedef detail::uint64 \fBglm::qword\fP"
Type for qword numbers\&. From GLM_GTX_raw_data extension\&. 
.SS "typedef \fBdetail::uint16\fP \fBglm::word\fP"
Type for word numbers\&. From GLM_GTX_raw_data extension\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
