.TH "gtx_matrix_interpolation" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_matrix_interpolation \- GLM_GTX_matrix_interpolation
.PP
Allows to directly interpolate two exiciting matrices\&.  

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL void \fBglm::axisAngle\fP (tmat4x4< T, P > const &mat, tvec3< T, P > &axis, T &angle)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL tmat4x4< T, P > \fBglm::axisAngleMatrix\fP (tvec3< T, P > const &axis, T const angle)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL tmat4x4< T, P > \fBglm::extractMatrixRotation\fP (tmat4x4< T, P > const &mat)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL tmat4x4< T, P > \fBglm::interpolate\fP (tmat4x4< T, P > const &m1, tmat4x4< T, P > const &m2, T const delta)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Allows to directly interpolate two exiciting matrices\&. 

<\fBglm/gtx/matrix_interpolation\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename T , precision P> GLM_FUNC_DECL void glm::axisAngle (tmat4x4< T, P > const & mat, tvec3< T, P > & axis, T & angle)"
Get the axis and angle of the rotation from a matrix\&. From GLM_GTX_matrix_interpolation extension\&. 
.SS "template<typename T , precision P> GLM_FUNC_DECL tmat4x4<T, P> glm::axisAngleMatrix (tvec3< T, P > const & axis, T const angle)"
Build a matrix from axis and angle\&. From GLM_GTX_matrix_interpolation extension\&. 
.SS "template<typename T , precision P> GLM_FUNC_DECL tmat4x4<T, P> glm::extractMatrixRotation (tmat4x4< T, P > const & mat)"
Extracts the rotation part of a matrix\&. From GLM_GTX_matrix_interpolation extension\&. 
.SS "template<typename T , precision P> GLM_FUNC_DECL tmat4x4<T, P> glm::interpolate (tmat4x4< T, P > const & m1, tmat4x4< T, P > const & m2, T const delta)"
Build a interpolation of 4 * 4 matrixes\&. From GLM_GTX_matrix_interpolation extension\&. Warning! works only with rotation and/or translation matrixes, scale will generate unexpected results\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
