.TH "gtx_number_precision" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_number_precision \- GLM_GTX_number_precision
.PP
Defined size types\&.  

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef u8 \fBglm::gtx::u8vec1\fP"
.br
.RI "\fI8bit unsigned integer scalar\&. (from GLM_GTX_number_precision extension) \fP"
.ti -1c
.RI "typedef u16 \fBglm::gtx::u16vec1\fP"
.br
.RI "\fI16bit unsigned integer scalar\&. (from GLM_GTX_number_precision extension) \fP"
.ti -1c
.RI "typedef u32 \fBglm::gtx::u32vec1\fP"
.br
.RI "\fI32bit unsigned integer scalar\&. (from GLM_GTX_number_precision extension) \fP"
.ti -1c
.RI "typedef u64 \fBglm::gtx::u64vec1\fP"
.br
.RI "\fI64bit unsigned integer scalar\&. (from GLM_GTX_number_precision extension) \fP"
.ti -1c
.RI "typedef f32 \fBglm::gtx::f32vec1\fP"
.br
.RI "\fISingle-precision floating-point scalar\&. (from GLM_GTX_number_precision extension) \fP"
.ti -1c
.RI "typedef f64 \fBglm::gtx::f64vec1\fP"
.br
.RI "\fISingle-precision floating-point scalar\&. (from GLM_GTX_number_precision extension) \fP"
.ti -1c
.RI "typedef f32 \fBglm::gtx::f32mat1\fP"
.br
.RI "\fISingle-precision floating-point scalar\&. (from GLM_GTX_number_precision extension) \fP"
.ti -1c
.RI "typedef f32 \fBglm::gtx::f32mat1x1\fP"
.br
.RI "\fISingle-precision floating-point scalar\&. (from GLM_GTX_number_precision extension) \fP"
.ti -1c
.RI "typedef f64 \fBglm::gtx::f64mat1\fP"
.br
.RI "\fIDouble-precision floating-point scalar\&. (from GLM_GTX_number_precision extension) \fP"
.ti -1c
.RI "typedef f64 \fBglm::gtx::f64mat1x1\fP"
.br
.RI "\fIDouble-precision floating-point scalar\&. (from GLM_GTX_number_precision extension) \fP"
.in -1c
.SH "Detailed Description"
.PP 
Defined size types\&. 

<\fBglm/gtx/number_precision\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Typedef Documentation"
.PP 
.SS "typedef f32 \fBglm::gtx::f32mat1\fP"

.PP
Single-precision floating-point scalar\&. (from GLM_GTX_number_precision extension) 
.SS "typedef f32 \fBglm::gtx::f32mat1x1\fP"

.PP
Single-precision floating-point scalar\&. (from GLM_GTX_number_precision extension) 
.SS "typedef f32 \fBglm::gtx::f32vec1\fP"

.PP
Single-precision floating-point scalar\&. (from GLM_GTX_number_precision extension) 
.SS "typedef f64 \fBglm::gtx::f64mat1\fP"

.PP
Double-precision floating-point scalar\&. (from GLM_GTX_number_precision extension) 
.SS "typedef f64 \fBglm::gtx::f64mat1x1\fP"

.PP
Double-precision floating-point scalar\&. (from GLM_GTX_number_precision extension) 
.SS "typedef f64 \fBglm::gtx::f64vec1\fP"

.PP
Single-precision floating-point scalar\&. (from GLM_GTX_number_precision extension) 
.SS "typedef u16 \fBglm::gtx::u16vec1\fP"

.PP
16bit unsigned integer scalar\&. (from GLM_GTX_number_precision extension) 
.SS "typedef u32 \fBglm::gtx::u32vec1\fP"

.PP
32bit unsigned integer scalar\&. (from GLM_GTX_number_precision extension) 
.SS "typedef u64 \fBglm::gtx::u64vec1\fP"

.PP
64bit unsigned integer scalar\&. (from GLM_GTX_number_precision extension) 
.SS "typedef u8 \fBglm::gtx::u8vec1\fP"

.PP
8bit unsigned integer scalar\&. (from GLM_GTX_number_precision extension) 
.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
