.TH "gtx_mixed_product" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_mixed_product \- GLM_GTX_mixed_producte
.PP
Mixed product of 3 vectors\&.  

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL T \fBglm::mixedProduct\fP (tvec3< T, P > const &v1, tvec3< T, P > const &v2, tvec3< T, P > const &v3)"
.br
.RI "\fIMixed product of 3 vectors (from GLM_GTX_mixed_product extension) \fP"
.in -1c
.SH "Detailed Description"
.PP 
Mixed product of 3 vectors\&. 

<\fBglm/gtx/mixed_product\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename T , precision P> GLM_FUNC_DECL T glm::mixedProduct (tvec3< T, P > const & v1, tvec3< T, P > const & v2, tvec3< T, P > const & v3)"

.PP
Mixed product of 3 vectors (from GLM_GTX_mixed_product extension) 
.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
