.TH "gtx_closest_point" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_closest_point \- GLM_GTX_closest_point
.PP
Find the point on a straight line which is the closet of a point\&.  

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL tvec3< T, P > \fBglm::closestPointOnLine\fP (tvec3< T, P > const &point, tvec3< T, P > const &a, tvec3< T, P > const &b)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL tvec2< T, P > \fBglm::closestPointOnLine\fP (tvec2< T, P > const &point, tvec2< T, P > const &a, tvec2< T, P > const &b)"
.br
.RI "\fI2d lines work as well \fP"
.in -1c
.SH "Detailed Description"
.PP 
Find the point on a straight line which is the closet of a point\&. 

<\fBglm/gtx/closest_point\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename T , precision P> GLM_FUNC_DECL tvec3<T, P> glm::closestPointOnLine (tvec3< T, P > const & point, tvec3< T, P > const & a, tvec3< T, P > const & b)"
Find the point on a straight line which is the closet of a point\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_closest_point\fP 
.RE
.PP

.SS "template<typename T , precision P> GLM_FUNC_DECL tvec2<T, P> glm::closestPointOnLine (tvec2< T, P > const & point, tvec2< T, P > const & a, tvec2< T, P > const & b)"

.PP
2d lines work as well 
.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
