.TH "gtx_io" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_io \- GLM_GTX_io
.PP
std::[w]ostream support for glm types  

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm::io\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBglm::io::format_punct< CTy >\fP"
.br
.ti -1c
.RI "class \fBglm::io::basic_state_saver< CTy, CTr >\fP"
.br
.ti -1c
.RI "class \fBglm::io::basic_format_saver< CTy, CTr >\fP"
.br
.ti -1c
.RI "struct \fBglm::io::precision\fP"
.br
.ti -1c
.RI "struct \fBglm::io::width\fP"
.br
.ti -1c
.RI "struct \fBglm::io::delimeter< CTy >\fP"
.br
.ti -1c
.RI "struct \fBglm::io::order\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, tquat< T, P > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, tvec1< T, P > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, tvec2< T, P > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, tvec3< T, P > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, tvec4< T, P > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, tmat2x2< T, P > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, tmat2x3< T, P > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, tmat2x4< T, P > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, tmat3x2< T, P > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, tmat3x3< T, P > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, tmat3x4< T, P > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, tmat4x2< T, P > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, tmat4x3< T, P > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, tmat4x4< T, P > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, std::pair< tmat4x4< T, P > const, tmat4x4< T, P > const  > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, std::pair< tmat4x4< T, P >, tmat4x4< T, P > > const &)"
.br
.in -1c
.SH "Detailed Description"
.PP 
std::[w]ostream support for glm types 

std::[w]ostream support for glm types + precision/width/etc\&. manipulators based on howard hinnant's std::chrono io proposal [http://home.roadrunner.com/~hinnant/bloomington/chrono_io.html]
.PP
<\fBglm/gtx/io\&.hpp\fP> needs to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream<CTy,CTr>& glm::operator<< (std::basic_ostream< CTy, CTr > &, \fBtquat\fP< T, P > const &)"

.SS "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream<CTy,CTr>& glm::operator<< (std::basic_ostream< CTy, CTr > &, tvec1< T, P > const &)"

.SS "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream<CTy,CTr>& glm::operator<< (std::basic_ostream< CTy, CTr > &, tvec2< T, P > const &)"

.SS "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream<CTy,CTr>& glm::operator<< (std::basic_ostream< CTy, CTr > &, tvec3< T, P > const &)"

.SS "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream<CTy,CTr>& glm::operator<< (std::basic_ostream< CTy, CTr > &, tvec4< T, P > const &)"

.SS "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream<CTy,CTr>& glm::operator<< (std::basic_ostream< CTy, CTr > &, tmat2x2< T, P > const &)"

.SS "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream<CTy,CTr>& glm::operator<< (std::basic_ostream< CTy, CTr > &, tmat2x3< T, P > const &)"

.SS "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream<CTy,CTr>& glm::operator<< (std::basic_ostream< CTy, CTr > &, tmat2x4< T, P > const &)"

.SS "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream<CTy,CTr>& glm::operator<< (std::basic_ostream< CTy, CTr > &, tmat3x2< T, P > const &)"

.SS "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream<CTy,CTr>& glm::operator<< (std::basic_ostream< CTy, CTr > &, tmat3x3< T, P > const &)"

.SS "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream<CTy,CTr>& glm::operator<< (std::basic_ostream< CTy, CTr > &, tmat3x4< T, P > const &)"

.SS "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream<CTy,CTr>& glm::operator<< (std::basic_ostream< CTy, CTr > &, tmat4x2< T, P > const &)"

.SS "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream<CTy,CTr>& glm::operator<< (std::basic_ostream< CTy, CTr > &, tmat4x3< T, P > const &)"

.SS "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream<CTy,CTr>& glm::operator<< (std::basic_ostream< CTy, CTr > &, tmat4x4< T, P > const &)"

.SS "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream<CTy,CTr>& glm::operator<< (std::basic_ostream< CTy, CTr > &, std::pair< tmat4x4< T, P > const, tmat4x4< T, P > const  > const &)"

.SS "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream<CTy,CTr>& glm::operator<< (std::basic_ostream< CTy, CTr > &, std::pair< tmat4x4< T, P >, tmat4x4< T, P > > const &)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
