.TH "gtx_perpendicular" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_perpendicular \- GLM_GTX_perpendicular
.PP
Perpendicular of a vector from other one\&.  

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename vecType > GLM_FUNC_DECL vecType \fBglm::perp\fP (vecType const &x, vecType const &Normal)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Perpendicular of a vector from other one\&. 

<\fBglm/gtx/perpendicular\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename vecType > GLM_FUNC_DECL vecType glm::perp (vecType const & x, vecType const & Normal)"
Projects x a perpendicular axis of Normal\&. From GLM_GTX_perpendicular extension\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
