.TH "gtx_string_cast" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_string_cast \- GLM_GTX_string_cast
.PP
Setup strings for GLM type values\&.  

.SS "Functions"

.in +1c
.ti -1c
.RI "template<template< typename, precision > class matType, typename T , precision P> GLM_FUNC_DECL std::string \fBglm::to_string\fP (matType< T, P > const &x)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Setup strings for GLM type values\&. 

<\fBglm/gtx/string_cast\&.hpp\fP> need to be included to use these functionalities\&. This extension is not supported with CUDA 
.SH "Function Documentation"
.PP 
.SS "template<template< typename, precision > class matType, typename T , precision P> GLM_FUNC_DECL std::string glm::to_string (matType< T, P > const & x)"
Create a string from a GLM vector or matrix typed variable\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_string_cast\fP extension\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
