.TH "gtx_transform2" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_transform2 \- GLM_GTX_transform2
.PP
Add extra transformation matrices\&.  

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL tmat3x3< T, P > \fBglm::shearX2D\fP (tmat3x3< T, P > const &m, T y)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL tmat3x3< T, P > \fBglm::shearY2D\fP (tmat3x3< T, P > const &m, T x)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL tmat4x4< T, P > \fBglm::shearX3D\fP (const tmat4x4< T, P > &m, T y, T z)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL tmat4x4< T, P > \fBglm::shearY3D\fP (const tmat4x4< T, P > &m, T x, T z)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL tmat4x4< T, P > \fBglm::shearZ3D\fP (const tmat4x4< T, P > &m, T x, T y)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL tmat3x3< T, P > \fBglm::proj2D\fP (const tmat3x3< T, P > &m, const tvec3< T, P > &normal)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL tmat4x4< T, P > \fBglm::proj3D\fP (const tmat4x4< T, P > &m, const tvec3< T, P > &normal)"
.br
.ti -1c
.RI "template<typename valType , precision P> GLM_FUNC_DECL tmat4x4< valType, P > \fBglm::scaleBias\fP (valType scale, valType bias)"
.br
.ti -1c
.RI "template<typename valType , precision P> GLM_FUNC_DECL tmat4x4< valType, P > \fBglm::scaleBias\fP (tmat4x4< valType, P > const &m, valType scale, valType bias)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Add extra transformation matrices\&. 

<\fBglm/gtx/transform2\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename T , precision P> GLM_FUNC_DECL tmat3x3<T, P> glm::proj2D (const tmat3x3< T, P > & m, const tvec3< T, P > & normal)"
Build planar projection matrix along normal axis\&. From GLM_GTX_transform2 extension\&. 
.SS "template<typename T , precision P> GLM_FUNC_DECL tmat4x4<T, P> glm::proj3D (const tmat4x4< T, P > & m, const tvec3< T, P > & normal)"
Build planar projection matrix along normal axis\&. From GLM_GTX_transform2 extension\&. 
.SS "template<typename valType , precision P> GLM_FUNC_DECL tmat4x4<valType, P> glm::scaleBias (valType scale, valType bias)"
Build a scale bias matrix\&. From GLM_GTX_transform2 extension\&. 
.SS "template<typename valType , precision P> GLM_FUNC_DECL tmat4x4<valType, P> glm::scaleBias (tmat4x4< valType, P > const & m, valType scale, valType bias)"
Build a scale bias matrix\&. From GLM_GTX_transform2 extension\&. 
.SS "template<typename T , precision P> GLM_FUNC_DECL tmat3x3<T, P> glm::shearX2D (tmat3x3< T, P > const & m, T y)"
Transforms a matrix with a shearing on X axis\&. From GLM_GTX_transform2 extension\&. 
.SS "template<typename T , precision P> GLM_FUNC_DECL tmat4x4<T, P> glm::shearX3D (const tmat4x4< T, P > & m, T y, T z)"
Transforms a matrix with a shearing on X axis From GLM_GTX_transform2 extension\&. 
.SS "template<typename T , precision P> GLM_FUNC_DECL tmat3x3<T, P> glm::shearY2D (tmat3x3< T, P > const & m, T x)"
Transforms a matrix with a shearing on Y axis\&. From GLM_GTX_transform2 extension\&. 
.SS "template<typename T , precision P> GLM_FUNC_DECL tmat4x4<T, P> glm::shearY3D (const tmat4x4< T, P > & m, T x, T z)"
Transforms a matrix with a shearing on Y axis\&. From GLM_GTX_transform2 extension\&. 
.SS "template<typename T , precision P> GLM_FUNC_DECL tmat4x4<T, P> glm::shearZ3D (const tmat4x4< T, P > & m, T x, T y)"
Transforms a matrix with a shearing on Z axis\&. From GLM_GTX_transform2 extension\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
