.TH "gtx_bit" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_bit \- GLM_GTX_bit
.PP
Allow to perform bit operations on integer values\&.  

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename genIUType > GLM_FUNC_DECL genIUType \fBglm::highestBitValue\fP (genIUType Value)"
.br
.ti -1c
.RI "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType< T, P > \fBglm::highestBitValue\fP (vecType< T, P > const &value)"
.br
.ti -1c
.RI "template<typename genIUType > GLM_DEPRECATED GLM_FUNC_DECL genIUType \fBglm::powerOfTwoAbove\fP (genIUType Value)"
.br
.ti -1c
.RI "template<typename T , precision P, template< typename, precision > class vecType> GLM_DEPRECATED GLM_FUNC_DECL vecType< T, P > \fBglm::powerOfTwoAbove\fP (vecType< T, P > const &value)"
.br
.ti -1c
.RI "template<typename genIUType > GLM_DEPRECATED GLM_FUNC_DECL genIUType \fBglm::powerOfTwoBelow\fP (genIUType Value)"
.br
.ti -1c
.RI "template<typename T , precision P, template< typename, precision > class vecType> GLM_DEPRECATED GLM_FUNC_DECL vecType< T, P > \fBglm::powerOfTwoBelow\fP (vecType< T, P > const &value)"
.br
.ti -1c
.RI "template<typename genIUType > GLM_DEPRECATED GLM_FUNC_DECL genIUType \fBglm::powerOfTwoNearest\fP (genIUType Value)"
.br
.ti -1c
.RI "template<typename T , precision P, template< typename, precision > class vecType> GLM_DEPRECATED GLM_FUNC_DECL vecType< T, P > \fBglm::powerOfTwoNearest\fP (vecType< T, P > const &value)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Allow to perform bit operations on integer values\&. 

<\fBglm/gtx/bit\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename genIUType > GLM_FUNC_DECL genIUType glm::highestBitValue (genIUType Value)"

.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_bit\fP 
.RE
.PP

.SS "template<typename T , precision P, template< typename, precision > class vecType> GLM_FUNC_DECL vecType<T, P> glm::highestBitValue (vecType< T, P > const & value)"
Find the highest bit set to 1 in a integer variable and return its value\&.
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_bit\fP 
.RE
.PP

.SS "template<typename genIUType > GLM_DEPRECATED GLM_FUNC_DECL genIUType glm::powerOfTwoAbove (genIUType Value)"
Return the power of two number which value is just higher the input value\&. Deprecated, use ceilPowerOfTwo from GTC_round instead
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_round\fP 
.PP
\fBGLM_GTX_bit\fP 
.RE
.PP

.SS "template<typename T , precision P, template< typename, precision > class vecType> GLM_DEPRECATED GLM_FUNC_DECL vecType<T, P> glm::powerOfTwoAbove (vecType< T, P > const & value)"
Return the power of two number which value is just higher the input value\&. Deprecated, use ceilPowerOfTwo from GTC_round instead
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_round\fP 
.PP
\fBGLM_GTX_bit\fP 
.RE
.PP

.SS "template<typename genIUType > GLM_DEPRECATED GLM_FUNC_DECL genIUType glm::powerOfTwoBelow (genIUType Value)"
Return the power of two number which value is just lower the input value\&. Deprecated, use floorPowerOfTwo from GTC_round instead
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_round\fP 
.PP
\fBGLM_GTX_bit\fP 
.RE
.PP

.SS "template<typename T , precision P, template< typename, precision > class vecType> GLM_DEPRECATED GLM_FUNC_DECL vecType<T, P> glm::powerOfTwoBelow (vecType< T, P > const & value)"
Return the power of two number which value is just lower the input value\&. Deprecated, use floorPowerOfTwo from GTC_round instead
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_round\fP 
.PP
\fBGLM_GTX_bit\fP 
.RE
.PP

.SS "template<typename genIUType > GLM_DEPRECATED GLM_FUNC_DECL genIUType glm::powerOfTwoNearest (genIUType Value)"
Return the power of two number which value is the closet to the input value\&. Deprecated, use roundPowerOfTwo from GTC_round instead
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_round\fP 
.PP
\fBGLM_GTX_bit\fP 
.RE
.PP

.SS "template<typename T , precision P, template< typename, precision > class vecType> GLM_DEPRECATED GLM_FUNC_DECL vecType<T, P> glm::powerOfTwoNearest (vecType< T, P > const & value)"
Return the power of two number which value is the closet to the input value\&. Deprecated, use roundPowerOfTwo from GTC_round instead
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTC_round\fP 
.PP
\fBGLM_GTX_bit\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
