.TH "gtx_simd_vec4" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_simd_vec4 \- GLM_GTX_simd_vec4
.PP
SIMD implementation of vec4 type\&.  
SIMD implementation of vec4 type\&. 

<\fBglm/gtx/simd_vec4\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
