.TH "gtx_color_space_YCoCg" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_color_space_YCoCg \- GLM_GTX_color_space_YCoCg
.PP
RGB to YCoCg conversions and operations\&.  

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL tvec3< T, P > \fBglm::rgb2YCoCg\fP (tvec3< T, P > const &rgbColor)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL tvec3< T, P > \fBglm::YCoCg2rgb\fP (tvec3< T, P > const &YCoCgColor)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL tvec3< T, P > \fBglm::rgb2YCoCgR\fP (tvec3< T, P > const &rgbColor)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL tvec3< T, P > \fBglm::YCoCgR2rgb\fP (tvec3< T, P > const &YCoCgColor)"
.br
.in -1c
.SH "Detailed Description"
.PP 
RGB to YCoCg conversions and operations\&. 

<\fBglm/gtx/color_space_YCoCg\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename T , precision P> GLM_FUNC_DECL tvec3<T, P> glm::rgb2YCoCg (tvec3< T, P > const & rgbColor)"
Convert a color from RGB color space to YCoCg color space\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_color_space_YCoCg\fP 
.RE
.PP

.SS "template<typename T , precision P> GLM_FUNC_DECL tvec3<T, P> glm::rgb2YCoCgR (tvec3< T, P > const & rgbColor)"
Convert a color from RGB color space to YCoCgR color space\&. 
.PP
\fBSee also:\fP
.RS 4
'YCoCg-R: A Color Space with RGB Reversibility and Low Dynamic Range' 
.PP
\fBGLM_GTX_color_space_YCoCg\fP 
.RE
.PP

.SS "template<typename T , precision P> GLM_FUNC_DECL tvec3<T, P> glm::YCoCg2rgb (tvec3< T, P > const & YCoCgColor)"
Convert a color from YCoCg color space to RGB color space\&. 
.PP
\fBSee also:\fP
.RS 4
\fBGLM_GTX_color_space_YCoCg\fP 
.RE
.PP

.SS "template<typename T , precision P> GLM_FUNC_DECL tvec3<T, P> glm::YCoCgR2rgb (tvec3< T, P > const & YCoCgColor)"
Convert a color from YCoCgR color space to RGB color space\&. 
.PP
\fBSee also:\fP
.RS 4
'YCoCg-R: A Color Space with RGB Reversibility and Low Dynamic Range' 
.PP
\fBGLM_GTX_color_space_YCoCg\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
