.TH "gtx_scalar_relational" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_scalar_relational \- GLM_GTX_scalar_relational
.PP
Extend a position from a source to a position at a defined length\&.  
Extend a position from a source to a position at a defined length\&. 

<\fBglm/gtx/scalar_relational\&.hpp\fP> need to be included to use these functionalities\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
