.TH "gtx_handed_coordinate_space" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gtx_handed_coordinate_space \- GLM_GTX_handed_coordinate_space
.PP
To know if a set of three basis vectors defines a right or left-handed coordinate system\&.  

.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL bool \fBglm::rightHanded\fP (tvec3< T, P > const &tangent, tvec3< T, P > const &binormal, tvec3< T, P > const &normal)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_DECL bool \fBglm::leftHanded\fP (tvec3< T, P > const &tangent, tvec3< T, P > const &binormal, tvec3< T, P > const &normal)"
.br
.in -1c
.SH "Detailed Description"
.PP 
To know if a set of three basis vectors defines a right or left-handed coordinate system\&. 

<glm/gtx/handed_coordinate_system\&.hpp> need to be included to use these functionalities\&. 
.SH "Function Documentation"
.PP 
.SS "template<typename T , precision P> GLM_FUNC_DECL bool glm::leftHanded (tvec3< T, P > const & tangent, tvec3< T, P > const & binormal, tvec3< T, P > const & normal)"
Return if a trihedron left handed or not\&. From GLM_GTX_handed_coordinate_space extension\&. 
.SS "template<typename T , precision P> GLM_FUNC_DECL bool glm::rightHanded (tvec3< T, P > const & tangent, tvec3< T, P > const & binormal, tvec3< T, P > const & normal)"
Return if a trihedron right handed or not\&. From GLM_GTX_handed_coordinate_space extension\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
