.TH "huffman" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
huffman \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBuint8\fP \fBfast\fP [1<< \fBFAST_BITS\fP]"
.br
.ti -1c
.RI "\fBuint16\fP \fBcode\fP [256]"
.br
.ti -1c
.RI "\fBuint8\fP \fBvalues\fP [256]"
.br
.ti -1c
.RI "\fBuint8\fP \fBsize\fP [257]"
.br
.ti -1c
.RI "unsigned int \fBmaxcode\fP [18]"
.br
.ti -1c
.RI "int \fBdelta\fP [17]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBuint16\fP huffman::code[256]"

.SS "int huffman::delta[17]"

.SS "\fBuint8\fP huffman::fast[1<< \fBFAST_BITS\fP]"

.SS "unsigned int huffman::maxcode[18]"

.SS "\fBuint8\fP huffman::size[257]"

.SS "\fBuint8\fP huffman::values[256]"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
