.TH "ieee_double_shape_type" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ieee_double_shape_type \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBvalue\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fBglm::detail::int32\fP \fBlsw\fP"
.br
.ti -1c
.RI "   \fBglm::detail::int32\fP \fBmsw\fP"
.br
.ti -1c
.RI "} \fBparts\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBglm::detail::int32\fP ieee_double_shape_type::lsw"

.SS "\fBglm::detail::int32\fP ieee_double_shape_type::msw"

.SS "struct { \&.\&.\&. }   ieee_double_shape_type::parts"

.SS "double ieee_double_shape_type::value"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
