.TH "IntersectData" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IntersectData \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <intersectData\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIntersectData\fP (const bool doesIntersect, const \fBVector3f\fP &direction)"
.br
.ti -1c
.RI "bool \fBGetDoesIntersect\fP () const "
.br
.ti -1c
.RI "float \fBGetDistance\fP () const "
.br
.ti -1c
.RI "const \fBVector3f\fP & \fBGetDirection\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBIntersectData\fP class stores information about two intersecting objects\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IntersectData::IntersectData (const bool doesIntersect, const \fBVector3f\fP & direction)\fC [inline]\fP"
Creates Intersect Data in a usable state\&.
.PP
\fBParameters:\fP
.RS 4
\fIdoesIntersect\fP Whether or not the objects are intersecting\&. 
.br
\fIdirection\fP The collision normal, with length set to distance\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "const \fBVector3f\fP& IntersectData::GetDirection () const\fC [inline]\fP"
Basic getter 
.SS "float IntersectData::GetDistance () const\fC [inline]\fP"
Basic getter for m_distance 
.SS "bool IntersectData::GetDoesIntersect () const\fC [inline]\fP"
Basic getter for m_doesIntersect 

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
