.TH "F:/Fusion3D_work/src/staticLibs/glm/gtx/io.hpp" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/Fusion3D_work/src/staticLibs/glm/gtx/io.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./glm\&.hpp'\fP
.br
\fC#include '\&.\&./gtx/quaternion\&.hpp'\fP
.br
\fC#include <iosfwd>\fP
.br
\fC#include <locale>\fP
.br
\fC#include <utility>\fP
.br
\fC#include 'io\&.inl'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBglm::io::format_punct< CTy >\fP"
.br
.ti -1c
.RI "class \fBglm::io::basic_state_saver< CTy, CTr >\fP"
.br
.ti -1c
.RI "class \fBglm::io::basic_format_saver< CTy, CTr >\fP"
.br
.ti -1c
.RI "struct \fBglm::io::precision\fP"
.br
.ti -1c
.RI "struct \fBglm::io::width\fP"
.br
.ti -1c
.RI "struct \fBglm::io::delimeter< CTy >\fP"
.br
.ti -1c
.RI "struct \fBglm::io::order\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.ti -1c
.RI " \fBglm::io\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef basic_state_saver< char > \fBglm::io::state_saver\fP"
.br
.ti -1c
.RI "typedef basic_state_saver< wchar_t > \fBglm::io::wstate_saver\fP"
.br
.ti -1c
.RI "typedef basic_format_saver< char > \fBglm::io::format_saver\fP"
.br
.ti -1c
.RI "typedef basic_format_saver< wchar_t > \fBglm::io::wformat_saver\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBglm::io::order_type\fP { \fBglm::io::column_major\fP, \fBglm::io::row_major\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename FTy , typename CTy , typename CTr > FTy const & \fBglm::io::get_facet\fP (std::basic_ios< CTy, CTr > &)"
.br
.ti -1c
.RI "template<typename FTy , typename CTy , typename CTr > std::basic_ios< CTy, CTr > & \fBglm::io::formatted\fP (std::basic_ios< CTy, CTr > &)"
.br
.ti -1c
.RI "template<typename FTy , typename CTy , typename CTr > std::basic_ios< CTy, CTr > & \fBglm::io::unformattet\fP (std::basic_ios< CTy, CTr > &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr > std::basic_ostream< CTy, CTr > & \fBglm::io::operator<<\fP (std::basic_ostream< CTy, CTr > &, precision const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr > std::basic_ostream< CTy, CTr > & \fBglm::io::operator<<\fP (std::basic_ostream< CTy, CTr > &, width const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr > std::basic_ostream< CTy, CTr > & \fBglm::io::operator<<\fP (std::basic_ostream< CTy, CTr > &, delimeter< CTy > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr > std::basic_ostream< CTy, CTr > & \fBglm::io::operator<<\fP (std::basic_ostream< CTy, CTr > &, order const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, tquat< T, P > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, tvec1< T, P > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, tvec2< T, P > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, tvec3< T, P > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, tvec4< T, P > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, tmat2x2< T, P > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, tmat2x3< T, P > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, tmat2x4< T, P > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, tmat3x2< T, P > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, tmat3x3< T, P > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, tmat3x4< T, P > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, tmat4x2< T, P > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, tmat4x3< T, P > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, tmat4x4< T, P > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, std::pair< tmat4x4< T, P > const, tmat4x4< T, P > const  > const &)"
.br
.ti -1c
.RI "template<typename CTy , typename CTr , typename T , precision P> GLM_FUNC_DECL std::basic_ostream< CTy, CTr > & \fBglm::operator<<\fP (std::basic_ostream< CTy, CTr > &, std::pair< tmat4x4< T, P >, tmat4x4< T, P > > const &)"
.br
.in -1c
.SH "Detailed Description"
.PP 
OpenGL Mathematics (glm\&.g-truc\&.net)
.PP
Copyright (c) 2005 - 2013 G-Truc Creation (www\&.g-truc\&.net) Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the 'Software'), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
.PP
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software\&.
.PP
Restrictions: By making use of the Software for military purposes, you choose to make a Bunny unhappy\&.
.PP
THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT\&. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE\&.
.PP
\fBGLM_GTX_io\fP
.PP
\fBDate:\fP
.RS 4
2013-11-22 / 2014-11-25 
.RE
.PP
\fBAuthor:\fP
.RS 4
Jan P Springer (regnirpsj@gmail.com)
.RE
.PP
\fBSee also:\fP
.RS 4
\fBGLM Core\fP (dependence) 
.PP
\fBGLM_GTC_quaternion\fP (dependence) 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
