.TH "jpeg" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jpeg \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstbi\fP * \fBs\fP"
.br
.ti -1c
.RI "\fBhuffman\fP \fBhuff_dc\fP [4]"
.br
.ti -1c
.RI "\fBhuffman\fP \fBhuff_ac\fP [4]"
.br
.ti -1c
.RI "\fBuint8\fP \fBdequant\fP [4][64]"
.br
.ti -1c
.RI "int \fBimg_h_max\fP"
.br
.ti -1c
.RI "int \fBimg_v_max\fP"
.br
.ti -1c
.RI "int \fBimg_mcu_x\fP"
.br
.ti -1c
.RI "int \fBimg_mcu_y\fP"
.br
.ti -1c
.RI "int \fBimg_mcu_w\fP"
.br
.ti -1c
.RI "int \fBimg_mcu_h\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   int \fBid\fP"
.br
.ti -1c
.RI "   int \fBh\fP"
.br
.ti -1c
.RI "   int \fBv\fP"
.br
.ti -1c
.RI "   int \fBtq\fP"
.br
.ti -1c
.RI "   int \fBhd\fP"
.br
.ti -1c
.RI "   int \fBha\fP"
.br
.ti -1c
.RI "   int \fBdc_pred\fP"
.br
.ti -1c
.RI "   int \fBx\fP"
.br
.ti -1c
.RI "   int \fBy\fP"
.br
.ti -1c
.RI "   int \fBw2\fP"
.br
.ti -1c
.RI "   int \fBh2\fP"
.br
.ti -1c
.RI "   \fBuint8\fP * \fBdata\fP"
.br
.ti -1c
.RI "   void * \fBraw_data\fP"
.br
.ti -1c
.RI "   \fBuint8\fP * \fBlinebuf\fP"
.br
.ti -1c
.RI "} \fBimg_comp\fP [4]"
.br
.ti -1c
.RI "\fBuint32\fP \fBcode_buffer\fP"
.br
.ti -1c
.RI "int \fBcode_bits\fP"
.br
.ti -1c
.RI "unsigned char \fBmarker\fP"
.br
.ti -1c
.RI "int \fBnomore\fP"
.br
.ti -1c
.RI "int \fBscan_n\fP"
.br
.ti -1c
.RI "int \fBorder\fP [4]"
.br
.ti -1c
.RI "int \fBrestart_interval\fP"
.br
.ti -1c
.RI "int \fBtodo\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int jpeg::code_bits"

.SS "\fBuint32\fP jpeg::code_buffer"

.SS "\fBuint8\fP* jpeg::data"

.SS "int jpeg::dc_pred"

.SS "\fBuint8\fP jpeg::dequant[4][64]"

.SS "int jpeg::h"

.SS "int jpeg::h2"

.SS "int jpeg::ha"

.SS "int jpeg::hd"

.SS "\fBhuffman\fP jpeg::huff_ac[4]"

.SS "\fBhuffman\fP jpeg::huff_dc[4]"

.SS "int jpeg::id"

.SS "struct { \&.\&.\&. }   jpeg::img_comp[4]"

.SS "int jpeg::img_h_max"

.SS "int jpeg::img_mcu_h"

.SS "int jpeg::img_mcu_w"

.SS "int jpeg::img_mcu_x"

.SS "int jpeg::img_mcu_y"

.SS "int jpeg::img_v_max"

.SS "\fBuint8\fP* jpeg::linebuf"

.SS "unsigned char jpeg::marker"

.SS "int jpeg::nomore"

.SS "int jpeg::order[4]"

.SS "void* jpeg::raw_data"

.SS "int jpeg::restart_interval"

.SS "\fBstbi\fP* jpeg::s"

.SS "int jpeg::scan_n"

.SS "int jpeg::todo"

.SS "int jpeg::tq"

.SS "int jpeg::v"

.SS "int jpeg::w2"

.SS "int jpeg::x"

.SS "int jpeg::y"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
