.TH "MaterialData" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaterialData \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <material\&.h>\fP
.PP
Inherits \fBReferenceCounter\fP, and \fBMappedValues\fP\&.
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
