.TH "F:/Fusion3D_work/src/core/math3d.h" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/Fusion3D_work/src/core/math3d.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'btBulletDynamicsCommon\&.h'\fP
.br
\fC#include <math\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBVector< T, D >\fP"
.br
.ti -1c
.RI "class \fBVector2< T >\fP"
.br
.ti -1c
.RI "class \fBVector3< T >\fP"
.br
.ti -1c
.RI "class \fBVector4< T >\fP"
.br
.ti -1c
.RI "class \fBMatrix< T, D >\fP"
.br
.ti -1c
.RI "class \fBMatrix4< T >\fP"
.br
.ti -1c
.RI "class \fBMatrix3< T >\fP"
.br
.ti -1c
.RI "class \fBVector3f\fP"
.br
.ti -1c
.RI "class \fBQuaternion\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMATH_PI\fP   3\&.1415926535897932384626433832795"
.br
.ti -1c
.RI "#define \fBToRadians\fP(x)   (float)(((x) * \fBMATH_PI\fP / 180\&.0f))"
.br
.ti -1c
.RI "#define \fBToDegrees\fP(x)   (float)(((x) * 180\&.0f / MATH_PI))"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBVector2\fP< int > \fBVector2i\fP"
.br
.ti -1c
.RI "typedef \fBVector3\fP< int > \fBVector3i\fP"
.br
.ti -1c
.RI "typedef \fBVector4\fP< int > \fBVector4i\fP"
.br
.ti -1c
.RI "typedef \fBVector2\fP< float > \fBVector2f\fP"
.br
.ti -1c
.RI "typedef \fBVector4\fP< float > \fBVector4f\fP"
.br
.ti -1c
.RI "typedef \fBVector2\fP< double > \fBVector2d\fP"
.br
.ti -1c
.RI "typedef \fBVector3\fP< double > \fBVector3d\fP"
.br
.ti -1c
.RI "typedef \fBVector4\fP< double > \fBVector4d\fP"
.br
.ti -1c
.RI "typedef \fBMatrix\fP< int, 2 > \fBMatrix2i\fP"
.br
.ti -1c
.RI "typedef \fBMatrix3\fP< int > \fBMatrix3i\fP"
.br
.ti -1c
.RI "typedef \fBMatrix4\fP< int > \fBMatrix4i\fP"
.br
.ti -1c
.RI "typedef \fBMatrix\fP< float, 2 > \fBMatrix2f\fP"
.br
.ti -1c
.RI "typedef \fBMatrix3\fP< float > \fBMatrix3f\fP"
.br
.ti -1c
.RI "typedef \fBMatrix4\fP< float > \fBMatrix4f\fP"
.br
.ti -1c
.RI "typedef \fBMatrix\fP< double, 2 > \fBMatrix2d\fP"
.br
.ti -1c
.RI "typedef \fBMatrix3\fP< double > \fBMatrix3d\fP"
.br
.ti -1c
.RI "typedef \fBMatrix4\fP< double > \fBMatrix4d\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T > T \fBClamp\fP (const T &a, const T &min, const T &max)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MATH_PI   3\&.1415926535897932384626433832795"

.SS "#define ToDegrees(x)   (float)(((x) * 180\&.0f / MATH_PI))"

.SS "#define ToRadians(x)   (float)(((x) * \fBMATH_PI\fP / 180\&.0f))"

.SH "Typedef Documentation"
.PP 
.SS "typedef \fBMatrix\fP<double, 2> \fBMatrix2d\fP"

.SS "typedef \fBMatrix\fP<float, 2> \fBMatrix2f\fP"

.SS "typedef \fBMatrix\fP<int, 2> \fBMatrix2i\fP"

.SS "typedef \fBMatrix3\fP<double> \fBMatrix3d\fP"

.SS "typedef \fBMatrix3\fP<float> \fBMatrix3f\fP"

.SS "typedef \fBMatrix3\fP<int> \fBMatrix3i\fP"

.SS "typedef \fBMatrix4\fP<double> \fBMatrix4d\fP"

.SS "typedef \fBMatrix4\fP<float> \fBMatrix4f\fP"

.SS "typedef \fBMatrix4\fP<int> \fBMatrix4i\fP"

.SS "typedef \fBVector2\fP<double> \fBVector2d\fP"

.SS "typedef \fBVector2\fP<float> \fBVector2f\fP"

.SS "typedef \fBVector2\fP<int> \fBVector2i\fP"

.SS "typedef \fBVector3\fP<double> \fBVector3d\fP"

.SS "typedef \fBVector3\fP<int> \fBVector3i\fP"

.SS "typedef \fBVector4\fP<double> \fBVector4d\fP"

.SS "typedef \fBVector4\fP<float> \fBVector4f\fP"

.SS "typedef \fBVector4\fP<int> \fBVector4i\fP"

.SH "Function Documentation"
.PP 
.SS "template<typename T > T Clamp (const T & a, const T & min, const T & max)\fC [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
