.TH "F:/Fusion3D_work/src/staticLibs/glm/gtx/matrix_major_storage.inl" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/Fusion3D_work/src/staticLibs/glm/gtx/matrix_major_storage.inl \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_QUALIFIER tmat2x2< T, P > \fBglm::rowMajor2\fP (tvec2< T, P > const &v1, tvec2< T, P > const &v2)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_QUALIFIER tmat2x2< T, P > \fBglm::rowMajor2\fP (const tmat2x2< T, P > &m)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_QUALIFIER tmat3x3< T, P > \fBglm::rowMajor3\fP (const tvec3< T, P > &v1, const tvec3< T, P > &v2, const tvec3< T, P > &v3)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_QUALIFIER tmat3x3< T, P > \fBglm::rowMajor3\fP (const tmat3x3< T, P > &m)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_QUALIFIER tmat4x4< T, P > \fBglm::rowMajor4\fP (const tvec4< T, P > &v1, const tvec4< T, P > &v2, const tvec4< T, P > &v3, const tvec4< T, P > &v4)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_QUALIFIER tmat4x4< T, P > \fBglm::rowMajor4\fP (const tmat4x4< T, P > &m)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_QUALIFIER tmat2x2< T, P > \fBglm::colMajor2\fP (const tvec2< T, P > &v1, const tvec2< T, P > &v2)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_QUALIFIER tmat2x2< T, P > \fBglm::colMajor2\fP (const tmat2x2< T, P > &m)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_QUALIFIER tmat3x3< T, P > \fBglm::colMajor3\fP (const tvec3< T, P > &v1, const tvec3< T, P > &v2, const tvec3< T, P > &v3)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_QUALIFIER tmat3x3< T, P > \fBglm::colMajor3\fP (const tmat3x3< T, P > &m)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_QUALIFIER tmat4x4< T, P > \fBglm::colMajor4\fP (const tvec4< T, P > &v1, const tvec4< T, P > &v2, const tvec4< T, P > &v3, const tvec4< T, P > &v4)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_QUALIFIER tmat4x4< T, P > \fBglm::colMajor4\fP (const tmat4x4< T, P > &m)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
