.TH "Matrix3< T >" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Matrix3< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <math3d\&.h>\fP
.PP
Inherits \fBMatrix< T, 3 >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMatrix3\fP ()"
.br
.ti -1c
.RI "template<unsigned int D> \fBMatrix3\fP (const \fBMatrix\fP< T, D > &r)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T > \fBMatrix3\fP< T >::\fBMatrix3\fP ()\fC [inline]\fP"

.SS "template<typename T > template<unsigned int D> \fBMatrix3\fP< T >::\fBMatrix3\fP (const \fBMatrix\fP< T, D > & r)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
