.TH "Matrix4< T >" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Matrix4< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <math3d\&.h>\fP
.PP
Inherits \fBMatrix< T, 4 >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMatrix4\fP ()"
.br
.ti -1c
.RI "template<unsigned int D> \fBMatrix4\fP (const \fBMatrix\fP< T, D > &r)"
.br
.ti -1c
.RI "\fBMatrix4\fP< T > \fBInitRotationEuler\fP (T rotateX, T rotateY, T rotateZ)"
.br
.ti -1c
.RI "\fBMatrix4\fP< T > \fBInitRotationFromVectors\fP (const \fBVector3\fP< T > &n, const \fBVector3\fP< T > &v, const \fBVector3\fP< T > &u)"
.br
.ti -1c
.RI "\fBMatrix4\fP< T > \fBInitRotationFromDirection\fP (const \fBVector3\fP< T > &forward, const \fBVector3\fP< T > &up)"
.br
.ti -1c
.RI "\fBMatrix4\fP< T > \fBInitPerspective\fP (T fov, T aspectRatio, T zNear, T zFar)"
.br
.ti -1c
.RI "\fBMatrix4\fP< T > \fBInitOrthographic\fP (T left, T right, T bottom, T top, T near, T far)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T> \fBMatrix4\fP< T >::\fBMatrix4\fP ()\fC [inline]\fP"

.SS "template<typename T> template<unsigned int D> \fBMatrix4\fP< T >::\fBMatrix4\fP (const \fBMatrix\fP< T, D > & r)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename T> \fBMatrix4\fP<T> \fBMatrix4\fP< T >::InitOrthographic (T left, T right, T bottom, T top, T near, T far)\fC [inline]\fP"

.SS "template<typename T> \fBMatrix4\fP<T> \fBMatrix4\fP< T >::InitPerspective (T fov, T aspectRatio, T zNear, T zFar)\fC [inline]\fP"

.SS "template<typename T> \fBMatrix4\fP<T> \fBMatrix4\fP< T >::InitRotationEuler (T rotateX, T rotateY, T rotateZ)\fC [inline]\fP"

.SS "template<typename T> \fBMatrix4\fP<T> \fBMatrix4\fP< T >::InitRotationFromDirection (const \fBVector3\fP< T > & forward, const \fBVector3\fP< T > & up)\fC [inline]\fP"

.SS "template<typename T> \fBMatrix4\fP<T> \fBMatrix4\fP< T >::InitRotationFromVectors (const \fBVector3\fP< T > & n, const \fBVector3\fP< T > & v, const \fBVector3\fP< T > & u)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
