.TH "F:/Fusion3D_work/src/staticLibs/glm/gtx/matrix_transform_2d.inl" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/Fusion3D_work/src/staticLibs/glm/gtx/matrix_transform_2d.inl \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./trigonometric\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_QUALIFIER tmat3x3< T, P > \fBglm::translate\fP (tmat3x3< T, P > const &m, tvec2< T, P > const &v)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_QUALIFIER tmat3x3< T, P > \fBglm::rotate\fP (tmat3x3< T, P > const &m, T angle)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_QUALIFIER tmat3x3< T, P > \fBglm::scale\fP (tmat3x3< T, P > const &m, tvec2< T, P > const &v)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_QUALIFIER tmat3x3< T, P > \fBglm::shearX\fP (tmat3x3< T, P > const &m, T y)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_QUALIFIER tmat3x3< T, P > \fBglm::shearY\fP (tmat3x3< T, P > const &m, T x)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
