.TH "MeshData" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MeshData \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mesh\&.h>\fP
.PP
Inherits \fBReferenceCounter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMeshData\fP (const \fBIndexedModel\fP &model, int materialIndex)"
.br
.ti -1c
.RI "virtual \fB~MeshData\fP ()"
.br
.ti -1c
.RI "void \fBDraw\fP () const "
.br
.ti -1c
.RI "int \fBGetMaterialIndex\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MeshData::MeshData (const \fBIndexedModel\fP & model, int materialIndex)"

.SS "MeshData::~MeshData ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void MeshData::Draw () const"

.SS "int MeshData::GetMaterialIndex ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
