.TH "Mesh" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Mesh \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mesh\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMesh\fP (const std::string &fileName='cube\&.obj')"
.br
.ti -1c
.RI "\fBMesh\fP (const std::string &fileName, \fBMeshData\fP *data)"
.br
.ti -1c
.RI "\fBMesh\fP (const std::string &meshName, const \fBIndexedModel\fP &model)"
.br
.ti -1c
.RI "\fBMesh\fP (const \fBMesh\fP &mesh)"
.br
.ti -1c
.RI "virtual \fB~Mesh\fP ()"
.br
.ti -1c
.RI "void \fBDraw\fP () const "
.br
.ti -1c
.RI "\fBMeshData\fP * \fBGetMeshData\fP () const "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::vector< \fBMeshData\fP * > \fBImportMeshData\fP (const std::string &fileName, int mode=\-1)"
.br
.ti -1c
.RI "static btTriangleMesh * \fBImportColData\fP (const std::string &fileName)"
.br
.ti -1c
.RI "static std::vector< \fBMaterial\fP * > \fBImportMeshMaterial\fP (const std::string &fileName)"
.br
.ti -1c
.RI "static std::vector< \fBMesh\fP * > \fBImportMesh\fP (const std::string &fileName)"
.br
.ti -1c
.RI "static btTriangleMesh * \fBImportCollision\fP (const std::string &fileName)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Mesh::Mesh (const std::string & fileName = \fC'cube\&.obj'\fP)"

.SS "Mesh::Mesh (const std::string & fileName, \fBMeshData\fP * data)"

.SS "Mesh::Mesh (const std::string & meshName, const \fBIndexedModel\fP & model)"

.SS "Mesh::Mesh (const \fBMesh\fP & mesh)"

.SS "Mesh::~Mesh ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Mesh::Draw () const"

.SS "\fBMeshData\fP* Mesh::GetMeshData () const\fC [inline]\fP"

.SS "btTriangleMesh * Mesh::ImportColData (const std::string & fileName)\fC [static]\fP"

.SS "btTriangleMesh * Mesh::ImportCollision (const std::string & fileName)\fC [static]\fP"

.SS "std::vector< \fBMesh\fP * > Mesh::ImportMesh (const std::string & fileName)\fC [static]\fP"

.SS "std::vector< \fBMeshData\fP * > Mesh::ImportMeshData (const std::string & fileName, int mode = \fC\-1\fP)\fC [static]\fP"

.SS "std::vector< \fBMaterial\fP * > Mesh::ImportMeshMaterial (const std::string & fileName)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
