.TH "mpc_pdata_and_t" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mpc_pdata_and_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBn\fP"
.br
.ti -1c
.RI "\fBmpc_fold_t\fP \fBf\fP"
.br
.ti -1c
.RI "\fBmpc_parser_t\fP ** \fBxs\fP"
.br
.ti -1c
.RI "\fBmpc_dtor_t\fP * \fBdxs\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBmpc_dtor_t\fP* mpc_pdata_and_t::dxs"

.SS "\fBmpc_fold_t\fP mpc_pdata_and_t::f"

.SS "int mpc_pdata_and_t::n"

.SS "\fBmpc_parser_t\fP** mpc_pdata_and_t::xs"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
