.TH "mpc_err_t" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mpc_err_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mpc\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmpc_state_t\fP \fBstate\fP"
.br
.ti -1c
.RI "int \fBexpected_num\fP"
.br
.ti -1c
.RI "char * \fBfilename\fP"
.br
.ti -1c
.RI "char * \fBfailure\fP"
.br
.ti -1c
.RI "char ** \fBexpected\fP"
.br
.ti -1c
.RI "char \fBrecieved\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "char** mpc_err_t::expected"

.SS "int mpc_err_t::expected_num"

.SS "char* mpc_err_t::failure"

.SS "char* mpc_err_t::filename"

.SS "char mpc_err_t::recieved"

.SS "\fBmpc_state_t\fP mpc_err_t::state"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
