.TH "mpc_ast_t" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mpc_ast_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mpc\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char * \fBtag\fP"
.br
.ti -1c
.RI "char * \fBcontents\fP"
.br
.ti -1c
.RI "\fBmpc_state_t\fP \fBstate\fP"
.br
.ti -1c
.RI "int \fBchildren_num\fP"
.br
.ti -1c
.RI "struct \fBmpc_ast_t\fP ** \fBchildren\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct \fBmpc_ast_t\fP** mpc_ast_t::children"

.SS "int mpc_ast_t::children_num"

.SS "char* mpc_ast_t::contents"

.SS "\fBmpc_state_t\fP mpc_ast_t::state"

.SS "char* mpc_ast_t::tag"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
