.TH "mpc_input_t" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mpc_input_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "char * \fBfilename\fP"
.br
.ti -1c
.RI "\fBmpc_state_t\fP \fBstate\fP"
.br
.ti -1c
.RI "char * \fBstring\fP"
.br
.ti -1c
.RI "char * \fBbuffer\fP"
.br
.ti -1c
.RI "FILE * \fBfile\fP"
.br
.ti -1c
.RI "int \fBbacktrack\fP"
.br
.ti -1c
.RI "int \fBmarks_num\fP"
.br
.ti -1c
.RI "\fBmpc_state_t\fP * \fBmarks\fP"
.br
.ti -1c
.RI "char * \fBlasts\fP"
.br
.ti -1c
.RI "char \fBlast\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int mpc_input_t::backtrack"

.SS "char* mpc_input_t::buffer"

.SS "FILE* mpc_input_t::file"

.SS "char* mpc_input_t::filename"

.SS "char mpc_input_t::last"

.SS "char* mpc_input_t::lasts"

.SS "\fBmpc_state_t\fP* mpc_input_t::marks"

.SS "int mpc_input_t::marks_num"

.SS "\fBmpc_state_t\fP mpc_input_t::state"

.SS "char* mpc_input_t::string"

.SS "int mpc_input_t::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
