.TH "mpc_parser_t" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mpc_parser_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBretained\fP"
.br
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "char \fBtype\fP"
.br
.ti -1c
.RI "\fBmpc_pdata_t\fP \fBdata\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBmpc_pdata_t\fP mpc_parser_t::data"

.SS "char* mpc_parser_t::name"

.SS "char mpc_parser_t::retained"

.SS "char mpc_parser_t::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
