.TH "mpc_stack_t" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mpc_stack_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBparsers_num\fP"
.br
.ti -1c
.RI "int \fBparsers_slots\fP"
.br
.ti -1c
.RI "\fBmpc_parser_t\fP ** \fBparsers\fP"
.br
.ti -1c
.RI "int * \fBstates\fP"
.br
.ti -1c
.RI "int \fBresults_num\fP"
.br
.ti -1c
.RI "int \fBresults_slots\fP"
.br
.ti -1c
.RI "\fBmpc_result_t\fP * \fBresults\fP"
.br
.ti -1c
.RI "int * \fBreturns\fP"
.br
.ti -1c
.RI "\fBmpc_err_t\fP * \fBerr\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBmpc_err_t\fP* mpc_stack_t::err"

.SS "\fBmpc_parser_t\fP** mpc_stack_t::parsers"

.SS "int mpc_stack_t::parsers_num"

.SS "int mpc_stack_t::parsers_slots"

.SS "\fBmpc_result_t\fP* mpc_stack_t::results"

.SS "int mpc_stack_t::results_num"

.SS "int mpc_stack_t::results_slots"

.SS "int* mpc_stack_t::returns"

.SS "int* mpc_stack_t::states"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
