.TH "mpc_state_t" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mpc_state_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mpc\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBpos\fP"
.br
.ti -1c
.RI "long \fBrow\fP"
.br
.ti -1c
.RI "long \fBcol\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "long mpc_state_t::col"

.SS "long mpc_state_t::pos"

.SS "long mpc_state_t::row"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
