.TH "F:/Fusion3D_work/src/staticLibs/glm/gtc/packing.inl" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/Fusion3D_work/src/staticLibs/glm/gtc/packing.inl \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./common\&.hpp'\fP
.br
\fC#include '\&.\&./vec2\&.hpp'\fP
.br
\fC#include '\&.\&./vec3\&.hpp'\fP
.br
\fC#include '\&.\&./vec4\&.hpp'\fP
.br
\fC#include '\&.\&./detail/type_half\&.hpp'\fP
.br
\fC#include <cstring>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "union \fBglm::detail::u10u10u10u2\fP"
.br
.ti -1c
.RI "union \fBglm::detail::i10i10i10i2\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.ti -1c
.RI " \fBglm::detail\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "GLM_FUNC_QUALIFIER \fBglm::uint16\fP \fBglm::detail::float2half\fP (\fBglm::uint32\fP f)"
.br
.ti -1c
.RI "GLM_FUNC_QUALIFIER \fBglm::uint32\fP \fBglm::detail::float2packed11\fP (\fBglm::uint32\fP f)"
.br
.ti -1c
.RI "GLM_FUNC_QUALIFIER \fBglm::uint32\fP \fBglm::detail::packed11ToFloat\fP (\fBglm::uint32\fP p)"
.br
.ti -1c
.RI "GLM_FUNC_QUALIFIER \fBglm::uint32\fP \fBglm::detail::float2packed10\fP (\fBglm::uint32\fP f)"
.br
.ti -1c
.RI "GLM_FUNC_QUALIFIER \fBglm::uint32\fP \fBglm::detail::packed10ToFloat\fP (\fBglm::uint32\fP p)"
.br
.ti -1c
.RI "GLM_FUNC_QUALIFIER \fBglm::uint\fP \fBglm::detail::half2float\fP (\fBglm::uint\fP h)"
.br
.ti -1c
.RI "GLM_FUNC_QUALIFIER \fBglm::uint\fP \fBglm::detail::floatTo11bit\fP (float x)"
.br
.ti -1c
.RI "GLM_FUNC_QUALIFIER float \fBglm::detail::packed11bitToFloat\fP (\fBglm::uint\fP x)"
.br
.ti -1c
.RI "GLM_FUNC_QUALIFIER \fBglm::uint\fP \fBglm::detail::floatTo10bit\fP (float x)"
.br
.ti -1c
.RI "GLM_FUNC_QUALIFIER float \fBglm::detail::packed10bitToFloat\fP (\fBglm::uint\fP x)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBuint8\fP \fBglm::packUnorm1x8\fP (float v)"
.br
.ti -1c
.RI "GLM_FUNC_DECL float \fBglm::unpackUnorm1x8\fP (\fBuint8\fP p)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBuint16\fP \fBglm::packUnorm2x8\fP (vec2 const &v)"
.br
.ti -1c
.RI "GLM_FUNC_DECL vec2 \fBglm::unpackUnorm2x8\fP (\fBuint16\fP p)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBuint8\fP \fBglm::packSnorm1x8\fP (float s)"
.br
.ti -1c
.RI "GLM_FUNC_DECL float \fBglm::unpackSnorm1x8\fP (\fBuint8\fP p)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBuint16\fP \fBglm::packSnorm2x8\fP (vec2 const &v)"
.br
.ti -1c
.RI "GLM_FUNC_DECL vec2 \fBglm::unpackSnorm2x8\fP (\fBuint16\fP p)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBuint16\fP \fBglm::packUnorm1x16\fP (float v)"
.br
.ti -1c
.RI "GLM_FUNC_DECL float \fBglm::unpackUnorm1x16\fP (\fBuint16\fP p)"
.br
.ti -1c
.RI "GLM_FUNC_DECL uint64 \fBglm::packUnorm4x16\fP (vec4 const &v)"
.br
.ti -1c
.RI "GLM_FUNC_DECL vec4 \fBglm::unpackUnorm4x16\fP (uint64 p)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBuint16\fP \fBglm::packSnorm1x16\fP (float v)"
.br
.ti -1c
.RI "GLM_FUNC_DECL float \fBglm::unpackSnorm1x16\fP (\fBuint16\fP p)"
.br
.ti -1c
.RI "GLM_FUNC_DECL uint64 \fBglm::packSnorm4x16\fP (vec4 const &v)"
.br
.ti -1c
.RI "GLM_FUNC_DECL vec4 \fBglm::unpackSnorm4x16\fP (uint64 p)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBuint16\fP \fBglm::packHalf1x16\fP (float v)"
.br
.ti -1c
.RI "GLM_FUNC_DECL float \fBglm::unpackHalf1x16\fP (\fBuint16\fP v)"
.br
.ti -1c
.RI "GLM_FUNC_QUALIFIER uint64 \fBglm::packHalf4x16\fP (glm::vec4 const &v)"
.br
.ti -1c
.RI "GLM_FUNC_DECL vec4 \fBglm::unpackHalf4x16\fP (uint64 p)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBuint32\fP \fBglm::packI3x10_1x2\fP (ivec4 const &v)"
.br
.ti -1c
.RI "GLM_FUNC_DECL ivec4 \fBglm::unpackI3x10_1x2\fP (\fBuint32\fP p)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBuint32\fP \fBglm::packU3x10_1x2\fP (uvec4 const &v)"
.br
.ti -1c
.RI "GLM_FUNC_DECL uvec4 \fBglm::unpackU3x10_1x2\fP (\fBuint32\fP p)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBuint32\fP \fBglm::packSnorm3x10_1x2\fP (vec4 const &v)"
.br
.ti -1c
.RI "GLM_FUNC_DECL vec4 \fBglm::unpackSnorm3x10_1x2\fP (\fBuint32\fP p)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBuint32\fP \fBglm::packUnorm3x10_1x2\fP (vec4 const &v)"
.br
.ti -1c
.RI "GLM_FUNC_DECL vec4 \fBglm::unpackUnorm3x10_1x2\fP (\fBuint32\fP p)"
.br
.ti -1c
.RI "GLM_FUNC_DECL \fBuint32\fP \fBglm::packF2x11_1x10\fP (vec3 const &v)"
.br
.ti -1c
.RI "GLM_FUNC_DECL vec3 \fBglm::unpackF2x11_1x10\fP (\fBuint32\fP p)"
.br
.in -1c
.SH "Detailed Description"
.PP 
OpenGL Mathematics (glm\&.g-truc\&.net)
.PP
Copyright (c) 2005 - 2015 G-Truc Creation (www\&.g-truc\&.net) Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the 'Software'), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
.PP
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software\&.
.PP
Restrictions: By making use of the Software for military purposes, you choose to make a Bunny unhappy\&.
.PP
THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT\&. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE\&.
.PP
\fBGLM_GTC_packing\fP
.PP
\fBDate:\fP
.RS 4
2013-08-08 / 2013-08-08 
.RE
.PP
\fBAuthor:\fP
.RS 4
Christophe Riccio 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
