.TH "PhysicsObject" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PhysicsObject \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <physicsObject\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPhysicsObject\fP (\fBCollider\fP *collider, const \fBVector3f\fP &velocity)"
.br
.ti -1c
.RI "\fBPhysicsObject\fP (const \fBPhysicsObject\fP &other)"
.br
.ti -1c
.RI "void \fBoperator=\fP (\fBPhysicsObject\fP other)"
.br
.ti -1c
.RI "virtual \fB~PhysicsObject\fP ()"
.br
.ti -1c
.RI "void \fBIntegrate\fP (float delta)"
.br
.ti -1c
.RI "const \fBVector3f\fP & \fBGetPosition\fP () const "
.br
.ti -1c
.RI "const \fBVector3f\fP & \fBGetVelocity\fP () const "
.br
.ti -1c
.RI "const \fBCollider\fP & \fBGetCollider\fP ()"
.br
.ti -1c
.RI "void \fBSetVelocity\fP (const \fBVector3f\fP &velocity)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBTest\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBPhysicsObject\fP class represents an object that can be used in a physics engine\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PhysicsObject::PhysicsObject (\fBCollider\fP * collider, const \fBVector3f\fP & velocity)\fC [inline]\fP"
Creates a \fBPhysicsObject\fP in a usable state\&.
.PP
\fBParameters:\fP
.RS 4
\fIcollider\fP A collider representing the shape and position of the object\&. Should be in allocated memory\&. 
.br
\fIvelocity\fP How fast this object is moving and in what direction\&. 
.RE
.PP

.SS "PhysicsObject::PhysicsObject (const \fBPhysicsObject\fP & other)"

.SS "PhysicsObject::~PhysicsObject ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "const \fBCollider\fP& PhysicsObject::GetCollider ()\fC [inline]\fP"
Returns a collider in the position of this object, updating the collider's position if necessary\&. 
.SS "const \fBVector3f\fP& PhysicsObject::GetPosition () const\fC [inline]\fP"
Basic getter 
.SS "const \fBVector3f\fP& PhysicsObject::GetVelocity () const\fC [inline]\fP"
Basic getter 
.SS "void PhysicsObject::Integrate (float delta)"
Calculate this object's new location and properties after delta seconds
.PP
\fBParameters:\fP
.RS 4
\fIdelta\fP How much time to simulate\&. 
.RE
.PP

.SS "void PhysicsObject::operator= (\fBPhysicsObject\fP other)"

.SS "void PhysicsObject::SetVelocity (const \fBVector3f\fP & velocity)\fC [inline]\fP"
Basic setter 
.SS "void PhysicsObject::Test ()\fC [static]\fP"
Performs a Unit Test of this class 

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
