.TH "F:/Fusion3D_work/src/components/physicsEngineComponent.h" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/Fusion3D_work/src/components/physicsEngineComponent.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./core/entityComponent\&.h'\fP
.br
\fC#include '\&.\&./physics/physicsEngine\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBPhysicsEngineComponent\fP (\fBPhysicsEngine\fP *engine)"
.br
.ti -1c
.RI "virtual void \fBUpdate\fP (float delta)"
.br
.ti -1c
.RI "\fBPhysicsEngine\fP * \fBGetPhysicsEngine\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBPhysicsEngine\fP * \fBm_physicsEngine\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBPhysicsEngine\fP* GetPhysicsEngine ()\fC [inline]\fP"

.SS "PhysicsEngineComponent (\fBPhysicsEngine\fP * engine)"

.SS "virtual void Update (float delta)\fC [virtual]\fP"

.SH "Variable Documentation"
.PP 
.SS "\fBPhysicsEngine\fP* m_physicsEngine"

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
