.TH "pic_packet_t" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pic_packet_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstbi_uc\fP \fBsize\fP"
.br
.ti -1c
.RI "\fBstbi_uc\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBstbi_uc\fP \fBchannel\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBstbi_uc\fP pic_packet_t::channel"

.SS "\fBstbi_uc\fP pic_packet_t::size"

.SS "\fBstbi_uc\fP pic_packet_t::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
