.TH "Plane" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Plane \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <plane\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlane\fP (const \fBVector3f\fP &normal, float distance)"
.br
.ti -1c
.RI "\fBPlane\fP \fBNormalized\fP () const "
.br
.ti -1c
.RI "\fBIntersectData\fP \fBIntersectSphere\fP (const \fBBoundingSphere\fP &other) const "
.br
.ti -1c
.RI "const \fBVector3f\fP & \fBGetNormal\fP () const "
.br
.ti -1c
.RI "float \fBGetDistance\fP () const "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBTest\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBPlane\fP class represents an infinitely large plane that can be used as a collider in a physics engine\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Plane::Plane (const \fBVector3f\fP & normal, float distance)\fC [inline]\fP"
Creates a \fBPlane\fP in a usable state\&.
.PP
\fBParameters:\fP
.RS 4
\fInormal\fP The 'up' direction from the plane's surface\&. 
.br
\fIdistance\fP The distance to the plane from the world origin along the normal 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "float Plane::GetDistance () const\fC [inline]\fP"

.SS "const \fBVector3f\fP& Plane::GetNormal () const\fC [inline]\fP"

.SS "\fBIntersectData\fP Plane::IntersectSphere (const \fBBoundingSphere\fP & other) const"
Computes information about if this \fBPlane\fP intersects a Sphere\&.
.PP
\fBParameters:\fP
.RS 4
\fIother\fP The Sphere that's being tested for intersection with this \fBPlane\fP\&. 
.RE
.PP

.SS "\fBPlane\fP Plane::Normalized () const"
Creates an equivalent plane with a normal at unit length and distance adjusted accordingly\&. 
.SS "void Plane::Test ()\fC [static]\fP"
Performs a Unit Test of this class 

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
