.TH "F:/Fusion3D_work/src/core/profiling.h" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/Fusion3D_work/src/core/profiling.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBProfileTimer\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPROFILING_DISABLE_MESH_DRAWING\fP   0"
.br
.ti -1c
.RI "#define \fBPROFILING_DISABLE_SHADING\fP   0"
.br
.ti -1c
.RI "#define \fBPROFILING_SET_1x1_VIEWPORT\fP   0"
.br
.ti -1c
.RI "#define \fBPROFILING_SET_2x2_TEXTURE\fP   0"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PROFILING_DISABLE_MESH_DRAWING   0"

.SS "#define PROFILING_DISABLE_SHADING   0"

.SS "#define PROFILING_SET_1x1_VIEWPORT   0"

.SS "#define PROFILING_SET_2x2_TEXTURE   0"

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
