.TH "Program" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Program \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <programComponent\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProgram\fP ()"
.br
.ti -1c
.RI "virtual \fB~Program\fP ()"
.br
.ti -1c
.RI "virtual int \fBInit\fP ()"
.br
.ti -1c
.RI "virtual int \fBProcessInput\fP (const \fBInput\fP &input, float delta)"
.br
.ti -1c
.RI "virtual int \fBUpdate\fP (float delta)"
.br
.ti -1c
.RI "virtual int \fBRender\fP (const \fBShader\fP &shader, const \fBRenderingEngine\fP &renderingEngine, const \fBCamera\fP &camera) const "
.br
.ti -1c
.RI "virtual int \fBRender\fP (const \fBShader\fP &shader, const \fBRenderingEngine\fP &renderingEngine, const \fBCamera\fP &camera)"
.br
.ti -1c
.RI "virtual std::string \fBGetProgramName\fP ()"
.br
.ti -1c
.RI "virtual std::string \fBGetLatestError\fP ()"
.br
.ti -1c
.RI "void \fBSetParent\fP (\fBEntity\fP *parent)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBPushError\fP (std::string err)"
.br
.ti -1c
.RI "\fBEntity\fP * \fBGetParent\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::set< std::string > \fBm_error\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Program::Program ()\fC [inline]\fP"

.SS "virtual Program::~Program ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual std::string Program::GetLatestError ()\fC [inline]\fP, \fC [virtual]\fP"

.SS "\fBEntity\fP* Program::GetParent ()\fC [inline]\fP, \fC [protected]\fP"

.SS "virtual std::string Program::GetProgramName ()\fC [inline]\fP, \fC [virtual]\fP"

.SS "virtual int Program::Init ()\fC [inline]\fP, \fC [virtual]\fP"

.SS "virtual int Program::ProcessInput (const \fBInput\fP & input, float delta)\fC [inline]\fP, \fC [virtual]\fP"

.SS "virtual void Program::PushError (std::string err)\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.SS "virtual int Program::Render (const \fBShader\fP & shader, const \fBRenderingEngine\fP & renderingEngine, const \fBCamera\fP & camera) const\fC [inline]\fP, \fC [virtual]\fP"

.SS "virtual int Program::Render (const \fBShader\fP & shader, const \fBRenderingEngine\fP & renderingEngine, const \fBCamera\fP & camera)\fC [inline]\fP, \fC [virtual]\fP"

.SS "void Program::SetParent (\fBEntity\fP * parent)\fC [inline]\fP"

.SS "virtual int Program::Update (float delta)\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::set<std::string> Program::m_error\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
