.TH "F:/Fusion3D_work/src/staticLibs/glm/gtx/quaternion.inl" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/Fusion3D_work/src/staticLibs/glm/gtx/quaternion.inl \- 
.SH SYNOPSIS
.br
.PP
\fC#include <limits>\fP
.br
\fC#include '\&.\&./gtc/constants\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBglm\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_QUALIFIER tvec3< T, P > \fBglm::cross\fP (tvec3< T, P > const &v, tquat< T, P > const &q)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_QUALIFIER tvec3< T, P > \fBglm::cross\fP (tquat< T, P > const &q, tvec3< T, P > const &v)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_QUALIFIER tquat< T, P > \fBglm::squad\fP (tquat< T, P > const &q1, tquat< T, P > const &q2, tquat< T, P > const &s1, tquat< T, P > const &s2, T const &h)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_QUALIFIER tquat< T, P > \fBglm::intermediate\fP (tquat< T, P > const &prev, tquat< T, P > const &curr, tquat< T, P > const &next)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_QUALIFIER tquat< T, P > \fBglm::exp\fP (tquat< T, P > const &q)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_QUALIFIER tquat< T, P > \fBglm::log\fP (tquat< T, P > const &q)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_QUALIFIER tquat< T, P > \fBglm::pow\fP (tquat< T, P > const &x, T const &y)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_QUALIFIER tvec3< T, P > \fBglm::rotate\fP (tquat< T, P > const &q, tvec3< T, P > const &v)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_QUALIFIER tvec4< T, P > \fBglm::rotate\fP (tquat< T, P > const &q, tvec4< T, P > const &v)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_QUALIFIER T \fBglm::extractRealComponent\fP (tquat< T, P > const &q)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_QUALIFIER T \fBglm::length2\fP (tquat< T, P > const &q)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_QUALIFIER tquat< T, P > \fBglm::shortMix\fP (tquat< T, P > const &x, tquat< T, P > const &y, T const &a)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_QUALIFIER tquat< T, P > \fBglm::fastMix\fP (tquat< T, P > const &x, tquat< T, P > const &y, T const &a)"
.br
.ti -1c
.RI "template<typename T , precision P> GLM_FUNC_QUALIFIER tquat< T, P > \fBglm::rotation\fP (tvec3< T, P > const &orig, tvec3< T, P > const &dest)"
.br
.in -1c
.SH "Detailed Description"
.PP 
OpenGL Mathematics (glm\&.g-truc\&.net)
.PP
Copyright (c) 2005 - 2015 G-Truc Creation (www\&.g-truc\&.net) Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the 'Software'), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
.PP
The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software\&.
.PP
Restrictions: By making use of the Software for military purposes, you choose to make a Bunny unhappy\&.
.PP
THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT\&. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE\&.
.PP
\fBGLM_GTX_quaternion\fP
.PP
\fBDate:\fP
.RS 4
2005-12-21 / 2011-06-07 
.RE
.PP
\fBAuthor:\fP
.RS 4
Christophe Riccio 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
