.TH "ReferenceCounter" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ReferenceCounter \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <referenceCounter\&.h>\fP
.PP
Inherited by \fBCollider\fP, \fBMaterialData\fP, \fBMeshData\fP, \fBShaderData\fP, and \fBTextureData\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBReferenceCounter\fP ()"
.br
.ti -1c
.RI "int \fBGetReferenceCount\fP ()"
.br
.ti -1c
.RI "void \fBAddReference\fP ()"
.br
.ti -1c
.RI "bool \fBRemoveReference\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ReferenceCounter::ReferenceCounter ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void ReferenceCounter::AddReference ()\fC [inline]\fP"

.SS "int ReferenceCounter::GetReferenceCount ()\fC [inline]\fP"

.SS "bool ReferenceCounter::RemoveReference ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
