.TH "ShaderData" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ShaderData \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <shader\&.h>\fP
.PP
Inherits \fBReferenceCounter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBShaderData\fP (const std::string &fileName)"
.br
.ti -1c
.RI "virtual \fB~ShaderData\fP ()"
.br
.ti -1c
.RI "int \fBGetProgram\fP () const "
.br
.ti -1c
.RI "const std::vector< int > & \fBGetShaders\fP () const "
.br
.ti -1c
.RI "const std::vector< std::string > & \fBGetUniformNames\fP () const "
.br
.ti -1c
.RI "const std::vector< std::string > & \fBGetUniformTypes\fP () const "
.br
.ti -1c
.RI "const std::map< std::string, unsigned int > & \fBGetUniformMap\fP () const "
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ShaderData::ShaderData (const std::string & fileName)"

.SS "ShaderData::~ShaderData ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "int ShaderData::GetProgram () const\fC [inline]\fP"

.SS "const std::vector<int>& ShaderData::GetShaders () const\fC [inline]\fP"

.SS "const std::map<std::string, unsigned int>& ShaderData::GetUniformMap () const\fC [inline]\fP"

.SS "const std::vector<std::string>& ShaderData::GetUniformNames () const\fC [inline]\fP"

.SS "const std::vector<std::string>& ShaderData::GetUniformTypes () const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
