.TH "Shader" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shader \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <shader\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBShader\fP (const std::string &fileName='basicShader')"
.br
.ti -1c
.RI "\fBShader\fP (const \fBShader\fP &other)"
.br
.ti -1c
.RI "virtual \fB~Shader\fP ()"
.br
.ti -1c
.RI "void \fBBind\fP () const "
.br
.ti -1c
.RI "virtual void \fBUpdateUniforms\fP (const \fBTransform\fP &transform, const \fBMaterial\fP &material, const \fBRenderingEngine\fP &renderingEngine, const \fBCamera\fP &camera) const "
.br
.ti -1c
.RI "void \fBSetUniformi\fP (const std::string &uniformName, int value) const "
.br
.ti -1c
.RI "void \fBSetUniformf\fP (const std::string &uniformName, float value) const "
.br
.ti -1c
.RI "void \fBSetUniformMatrix4f\fP (const std::string &uniformName, const \fBMatrix4f\fP &value) const "
.br
.ti -1c
.RI "void \fBSetUniformVector3f\fP (const std::string &uniformName, const \fBVector3f\fP &value) const "
.br
.ti -1c
.RI "const std::string & \fBGetName\fP () const "
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Shader::Shader (const std::string & fileName = \fC'basicShader'\fP)"

.SS "Shader::Shader (const \fBShader\fP & other)"

.SS "Shader::~Shader ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Shader::Bind () const"

.SS "const std::string& Shader::GetName () const\fC [inline]\fP"

.SS "void Shader::SetUniformf (const std::string & uniformName, float value) const"

.SS "void Shader::SetUniformi (const std::string & uniformName, int value) const"

.SS "void Shader::SetUniformMatrix4f (const std::string & uniformName, const \fBMatrix4f\fP & value) const"

.SS "void Shader::SetUniformVector3f (const std::string & uniformName, const \fBVector3f\fP & value) const"

.SS "void Shader::UpdateUniforms (const \fBTransform\fP & transform, const \fBMaterial\fP & material, const \fBRenderingEngine\fP & renderingEngine, const \fBCamera\fP & camera) const\fC [virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
