.TH "ShadowInfo" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ShadowInfo \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lighting\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBShadowInfo\fP (const \fBMatrix4f\fP &projection=\fBMatrix4f\fP()\&.InitIdentity(), bool flipFaces=false, int shadowMapSizeAsPowerOf2=0, float shadowSoftness=1\&.0f, float lightBleedReductionAmount=0\&.2f, float minVariance=0\&.00002f)"
.br
.ti -1c
.RI "const \fBMatrix4f\fP & \fBGetProjection\fP () const "
.br
.ti -1c
.RI "bool \fBGetFlipFaces\fP () const "
.br
.ti -1c
.RI "int \fBGetShadowMapSizeAsPowerOf2\fP () const "
.br
.ti -1c
.RI "float \fBGetShadowSoftness\fP () const "
.br
.ti -1c
.RI "float \fBGetMinVariance\fP () const "
.br
.ti -1c
.RI "float \fBGetLightBleedReductionAmount\fP () const "
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ShadowInfo::ShadowInfo (const \fBMatrix4f\fP & projection = \fC\fBMatrix4f\fP()\&.InitIdentity()\fP, bool flipFaces = \fCfalse\fP, int shadowMapSizeAsPowerOf2 = \fC0\fP, float shadowSoftness = \fC1\&.0f\fP, float lightBleedReductionAmount = \fC0\&.2f\fP, float minVariance = \fC0\&.00002f\fP)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "bool ShadowInfo::GetFlipFaces () const\fC [inline]\fP"

.SS "float ShadowInfo::GetLightBleedReductionAmount () const\fC [inline]\fP"

.SS "float ShadowInfo::GetMinVariance () const\fC [inline]\fP"

.SS "const \fBMatrix4f\fP& ShadowInfo::GetProjection () const\fC [inline]\fP"

.SS "int ShadowInfo::GetShadowMapSizeAsPowerOf2 () const\fC [inline]\fP"

.SS "float ShadowInfo::GetShadowSoftness () const\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
