.TH "F:/Fusion3D_work/src/staticLibs/simddefines.h" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/Fusion3D_work/src/staticLibs/simddefines.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <emmintrin\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSIMD_CPU_ARCH_OTHER\fP   0"
.br
.ti -1c
.RI "#define \fBSIMD_CPU_ARCH_x86\fP   1"
.br
.ti -1c
.RI "#define \fBSIMD_CPU_ARCH_x86_64\fP   2"
.br
.ti -1c
.RI "#define \fBSIMD_LEVEL_NONE\fP   0"
.br
.ti -1c
.RI "#define \fBSIMD_LEVEL_x86_SSE\fP   1"
.br
.ti -1c
.RI "#define \fBSIMD_LEVEL_x86_SSE2\fP   2"
.br
.ti -1c
.RI "#define \fBSIMD_LEVEL_x86_SSE3\fP   3"
.br
.ti -1c
.RI "#define \fBSIMD_LEVEL_x86_SSSE3\fP   4"
.br
.ti -1c
.RI "#define \fBSIMD_LEVEL_x86_SSE4_1\fP   5"
.br
.ti -1c
.RI "#define \fBSIMD_LEVEL_x86_SSE4_2\fP   6"
.br
.ti -1c
.RI "#define \fBSIMD_LEVEL_x86_AVX\fP   7"
.br
.ti -1c
.RI "#define \fBSIMD_LEVEL_x86_AVX2\fP   8"
.br
.ti -1c
.RI "#define \fBSIMD_CPU_ARCH\fP   \fBSIMD_CPU_ARCH_OTHER\fP"
.br
.ti -1c
.RI "#define \fBSIMD_SUPPORTED_LEVEL\fP   \fBSIMD_LEVEL_x86_SSE2\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef signed char \fBint8_t\fP"
.br
.ti -1c
.RI "typedef unsigned char \fBuint8_t\fP"
.br
.ti -1c
.RI "typedef signed short int \fBint16_t\fP"
.br
.ti -1c
.RI "typedef unsigned short int \fBuint16_t\fP"
.br
.ti -1c
.RI "typedef signed int \fBint32_t\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBuint32_t\fP"
.br
.ti -1c
.RI "typedef long long \fBint64_t\fP"
.br
.ti -1c
.RI "typedef unsigned long long \fBuint64_t\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SIMD_CPU_ARCH   \fBSIMD_CPU_ARCH_OTHER\fP"

.SS "#define SIMD_CPU_ARCH_OTHER   0"

.SS "#define SIMD_CPU_ARCH_x86   1"

.SS "#define SIMD_CPU_ARCH_x86_64   2"

.SS "#define SIMD_LEVEL_NONE   0"

.SS "#define SIMD_LEVEL_x86_AVX   7"

.SS "#define SIMD_LEVEL_x86_AVX2   8"

.SS "#define SIMD_LEVEL_x86_SSE   1"

.SS "#define SIMD_LEVEL_x86_SSE2   2"

.SS "#define SIMD_LEVEL_x86_SSE3   3"

.SS "#define SIMD_LEVEL_x86_SSE4_1   5"

.SS "#define SIMD_LEVEL_x86_SSE4_2   6"

.SS "#define SIMD_LEVEL_x86_SSSE3   4"

.SS "#define SIMD_SUPPORTED_LEVEL   \fBSIMD_LEVEL_x86_SSE2\fP"

.SH "Typedef Documentation"
.PP 
.SS "typedef signed short int \fBint16_t\fP"

.SS "typedef signed int \fBint32_t\fP"

.SS "typedef long long \fBint64_t\fP"

.SS "typedef signed char \fBint8_t\fP"

.SS "typedef unsigned short int \fBuint16_t\fP"

.SS "typedef unsigned int \fBuint32_t\fP"

.SS "typedef unsigned long long \fBuint64_t\fP"

.SS "typedef unsigned char \fBuint8_t\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
