.TH "F:/Fusion3D_work/src/staticLibs/stb_image.h" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/Fusion3D_work/src/staticLibs/stb_image.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBstbi_io_callbacks\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSTBI_VERSION\fP   1"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned char \fBstbi_uc\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBSTBI_default\fP = 0, \fBSTBI_grey\fP = 1, \fBSTBI_grey_alpha\fP = 2, \fBSTBI_rgb\fP = 3, \fBSTBI_rgb_alpha\fP = 4 }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBstbi_uc\fP * \fBstbi_load_from_memory\fP (\fBstbi_uc\fP const *buffer, int len, int *x, int *y, int *comp, int req_comp)"
.br
.RI "\fISTBI_NO_STDIO\&. \fP"
.ti -1c
.RI "\fBstbi_uc\fP * \fBstbi_load\fP (char const *filename, int *x, int *y, int *comp, int req_comp)"
.br
.ti -1c
.RI "\fBstbi_uc\fP * \fBstbi_load_from_file\fP (FILE *f, int *x, int *y, int *comp, int req_comp)"
.br
.ti -1c
.RI "\fBstbi_uc\fP * \fBstbi_load_from_callbacks\fP (\fBstbi_io_callbacks\fP const *clbk, void *user, int *x, int *y, int *comp, int req_comp)"
.br
.ti -1c
.RI "float * \fBstbi_loadf_from_memory\fP (\fBstbi_uc\fP const *buffer, int len, int *x, int *y, int *comp, int req_comp)"
.br
.ti -1c
.RI "float * \fBstbi_loadf\fP (char const *filename, int *x, int *y, int *comp, int req_comp)"
.br
.ti -1c
.RI "float * \fBstbi_loadf_from_file\fP (FILE *f, int *x, int *y, int *comp, int req_comp)"
.br
.ti -1c
.RI "float * \fBstbi_loadf_from_callbacks\fP (\fBstbi_io_callbacks\fP const *clbk, void *user, int *x, int *y, int *comp, int req_comp)"
.br
.ti -1c
.RI "void \fBstbi_hdr_to_ldr_gamma\fP (float gamma)"
.br
.ti -1c
.RI "void \fBstbi_hdr_to_ldr_scale\fP (float scale)"
.br
.ti -1c
.RI "void \fBstbi_ldr_to_hdr_gamma\fP (float gamma)"
.br
.ti -1c
.RI "void \fBstbi_ldr_to_hdr_scale\fP (float scale)"
.br
.ti -1c
.RI "int \fBstbi_is_hdr_from_callbacks\fP (\fBstbi_io_callbacks\fP const *clbk, void *user)"
.br
.ti -1c
.RI "int \fBstbi_is_hdr_from_memory\fP (\fBstbi_uc\fP const *buffer, int len)"
.br
.ti -1c
.RI "int \fBstbi_is_hdr\fP (char const *filename)"
.br
.ti -1c
.RI "int \fBstbi_is_hdr_from_file\fP (FILE *f)"
.br
.ti -1c
.RI "const char * \fBstbi_failure_reason\fP (void)"
.br
.ti -1c
.RI "void \fBstbi_image_free\fP (void *retval_from_stbi_load)"
.br
.ti -1c
.RI "int \fBstbi_info_from_memory\fP (\fBstbi_uc\fP const *buffer, int len, int *x, int *y, int *comp)"
.br
.ti -1c
.RI "int \fBstbi_info_from_callbacks\fP (\fBstbi_io_callbacks\fP const *clbk, void *user, int *x, int *y, int *comp)"
.br
.ti -1c
.RI "int \fBstbi_info\fP (char const *filename, int *x, int *y, int *comp)"
.br
.ti -1c
.RI "int \fBstbi_info_from_file\fP (FILE *f, int *x, int *y, int *comp)"
.br
.ti -1c
.RI "void \fBstbi_set_unpremultiply_on_load\fP (int flag_true_if_should_unpremultiply)"
.br
.ti -1c
.RI "void \fBstbi_convert_iphone_png_to_rgb\fP (int flag_true_if_should_convert)"
.br
.ti -1c
.RI "char * \fBstbi_zlib_decode_malloc_guesssize\fP (const char *buffer, int len, int initial_size, int *outlen)"
.br
.ti -1c
.RI "char * \fBstbi_zlib_decode_malloc\fP (const char *buffer, int len, int *outlen)"
.br
.ti -1c
.RI "int \fBstbi_zlib_decode_buffer\fP (char *obuffer, int olen, const char *ibuffer, int ilen)"
.br
.ti -1c
.RI "char * \fBstbi_zlib_decode_noheader_malloc\fP (const char *buffer, int len, int *outlen)"
.br
.ti -1c
.RI "int \fBstbi_zlib_decode_noheader_buffer\fP (char *obuffer, int olen, const char *ibuffer, int ilen)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define STBI_VERSION   1"

.SH "Typedef Documentation"
.PP 
.SS "typedef unsigned char \fBstbi_uc\fP"

.SH "Enumeration Type Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISTBI_default \fP\fP
.TP
\fB\fISTBI_grey \fP\fP
.TP
\fB\fISTBI_grey_alpha \fP\fP
.TP
\fB\fISTBI_rgb \fP\fP
.TP
\fB\fISTBI_rgb_alpha \fP\fP
.SH "Function Documentation"
.PP 
.SS "void stbi_convert_iphone_png_to_rgb (int flag_true_if_should_convert)"

.SS "const char* stbi_failure_reason (void)"

.SS "void stbi_hdr_to_ldr_gamma (float gamma)"

.SS "void stbi_hdr_to_ldr_scale (float scale)"

.SS "void stbi_image_free (void * retval_from_stbi_load)"

.SS "int stbi_info (char const * filename, int * x, int * y, int * comp)"

.SS "int stbi_info_from_callbacks (\fBstbi_io_callbacks\fP const * clbk, void * user, int * x, int * y, int * comp)"

.SS "int stbi_info_from_file (FILE * f, int * x, int * y, int * comp)"

.SS "int stbi_info_from_memory (\fBstbi_uc\fP const * buffer, int len, int * x, int * y, int * comp)"

.SS "int stbi_is_hdr (char const * filename)"

.SS "int stbi_is_hdr_from_callbacks (\fBstbi_io_callbacks\fP const * clbk, void * user)"

.SS "int stbi_is_hdr_from_file (FILE * f)"

.SS "int stbi_is_hdr_from_memory (\fBstbi_uc\fP const * buffer, int len)"

.SS "void stbi_ldr_to_hdr_gamma (float gamma)"

.SS "void stbi_ldr_to_hdr_scale (float scale)"

.SS "\fBstbi_uc\fP* stbi_load (char const * filename, int * x, int * y, int * comp, int req_comp)"

.SS "\fBstbi_uc\fP* stbi_load_from_callbacks (\fBstbi_io_callbacks\fP const * clbk, void * user, int * x, int * y, int * comp, int req_comp)"

.SS "\fBstbi_uc\fP* stbi_load_from_file (FILE * f, int * x, int * y, int * comp, int req_comp)"

.SS "\fBstbi_uc\fP* stbi_load_from_memory (\fBstbi_uc\fP const * buffer, int len, int * x, int * y, int * comp, int req_comp)"

.PP
STBI_NO_STDIO\&. 
.SS "float* stbi_loadf (char const * filename, int * x, int * y, int * comp, int req_comp)"

.SS "float* stbi_loadf_from_callbacks (\fBstbi_io_callbacks\fP const * clbk, void * user, int * x, int * y, int * comp, int req_comp)"

.SS "float* stbi_loadf_from_file (FILE * f, int * x, int * y, int * comp, int req_comp)"

.SS "float* stbi_loadf_from_memory (\fBstbi_uc\fP const * buffer, int len, int * x, int * y, int * comp, int req_comp)"

.SS "void stbi_set_unpremultiply_on_load (int flag_true_if_should_unpremultiply)"

.SS "int stbi_zlib_decode_buffer (char * obuffer, int olen, const char * ibuffer, int ilen)"

.SS "char* stbi_zlib_decode_malloc (const char * buffer, int len, int * outlen)"

.SS "char* stbi_zlib_decode_malloc_guesssize (const char * buffer, int len, int initial_size, int * outlen)"

.SS "int stbi_zlib_decode_noheader_buffer (char * obuffer, int olen, const char * ibuffer, int ilen)"

.SS "char* stbi_zlib_decode_noheader_malloc (const char * buffer, int len, int * outlen)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
