.TH "stbi_gif_lzw_struct" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stbi_gif_lzw_struct \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint16\fP \fBprefix\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBfirst\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBsuffix\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBuint8\fP stbi_gif_lzw_struct::first"

.SS "\fBint16\fP stbi_gif_lzw_struct::prefix"

.SS "\fBuint8\fP stbi_gif_lzw_struct::suffix"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
