.TH "stbi_resample" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stbi_resample \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBresample_row_func\fP \fBresample\fP"
.br
.ti -1c
.RI "\fBuint8\fP * \fBline0\fP"
.br
.ti -1c
.RI "\fBuint8\fP * \fBline1\fP"
.br
.ti -1c
.RI "int \fBhs\fP"
.br
.ti -1c
.RI "int \fBvs\fP"
.br
.ti -1c
.RI "int \fBw_lores\fP"
.br
.ti -1c
.RI "int \fBystep\fP"
.br
.ti -1c
.RI "int \fBypos\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int stbi_resample::hs"

.SS "\fBuint8\fP* stbi_resample::line0"

.SS "\fBuint8\fP * stbi_resample::line1"

.SS "\fBresample_row_func\fP stbi_resample::resample"

.SS "int stbi_resample::vs"

.SS "int stbi_resample::w_lores"

.SS "int stbi_resample::ypos"

.SS "int stbi_resample::ystep"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
