.TH "stbi" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stbi \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBuint32\fP \fBimg_x\fP"
.br
.ti -1c
.RI "\fBuint32\fP \fBimg_y\fP"
.br
.ti -1c
.RI "int \fBimg_n\fP"
.br
.ti -1c
.RI "int \fBimg_out_n\fP"
.br
.ti -1c
.RI "\fBstbi_io_callbacks\fP \fBio\fP"
.br
.ti -1c
.RI "void * \fBio_user_data\fP"
.br
.ti -1c
.RI "int \fBread_from_callbacks\fP"
.br
.ti -1c
.RI "int \fBbuflen\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBbuffer_start\fP [128]"
.br
.ti -1c
.RI "\fBuint8\fP * \fBimg_buffer\fP"
.br
.ti -1c
.RI "\fBuint8\fP * \fBimg_buffer_end\fP"
.br
.ti -1c
.RI "\fBuint8\fP * \fBimg_buffer_original\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBuint8\fP stbi::buffer_start[128]"

.SS "int stbi::buflen"

.SS "\fBuint8\fP* stbi::img_buffer"

.SS "\fBuint8\fP * stbi::img_buffer_end"

.SS "\fBuint8\fP* stbi::img_buffer_original"

.SS "int stbi::img_n"

.SS "int stbi::img_out_n"

.SS "\fBuint32\fP stbi::img_x"

.SS "\fBuint32\fP stbi::img_y"

.SS "\fBstbi_io_callbacks\fP stbi::io"

.SS "void* stbi::io_user_data"

.SS "int stbi::read_from_callbacks"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
