.TH "stbi_gif_struct" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stbi_gif_struct \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBw\fP"
.br
.ti -1c
.RI "int \fBh\fP"
.br
.ti -1c
.RI "\fBstbi_uc\fP * \fBout\fP"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.ti -1c
.RI "int \fBbgindex\fP"
.br
.ti -1c
.RI "int \fBratio\fP"
.br
.ti -1c
.RI "int \fBtransparent\fP"
.br
.ti -1c
.RI "int \fBeflags\fP"
.br
.ti -1c
.RI "\fBuint8\fP \fBpal\fP [256][4]"
.br
.ti -1c
.RI "\fBuint8\fP \fBlpal\fP [256][4]"
.br
.ti -1c
.RI "\fBstbi_gif_lzw\fP \fBcodes\fP [4096]"
.br
.ti -1c
.RI "\fBuint8\fP * \fBcolor_table\fP"
.br
.ti -1c
.RI "int \fBparse\fP"
.br
.ti -1c
.RI "int \fBstep\fP"
.br
.ti -1c
.RI "int \fBlflags\fP"
.br
.ti -1c
.RI "int \fBstart_x\fP"
.br
.ti -1c
.RI "int \fBstart_y\fP"
.br
.ti -1c
.RI "int \fBmax_x\fP"
.br
.ti -1c
.RI "int \fBmax_y\fP"
.br
.ti -1c
.RI "int \fBcur_x\fP"
.br
.ti -1c
.RI "int \fBcur_y\fP"
.br
.ti -1c
.RI "int \fBline_size\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "int stbi_gif_struct::bgindex"

.SS "\fBstbi_gif_lzw\fP stbi_gif_struct::codes[4096]"

.SS "\fBuint8\fP* stbi_gif_struct::color_table"

.SS "int stbi_gif_struct::cur_x"

.SS "int stbi_gif_struct::cur_y"

.SS "int stbi_gif_struct::eflags"

.SS "int stbi_gif_struct::flags"

.SS "int stbi_gif_struct::h"

.SS "int stbi_gif_struct::lflags"

.SS "int stbi_gif_struct::line_size"

.SS "\fBuint8\fP stbi_gif_struct::lpal[256][4]"

.SS "int stbi_gif_struct::max_x"

.SS "int stbi_gif_struct::max_y"

.SS "\fBstbi_uc\fP* stbi_gif_struct::out"

.SS "\fBuint8\fP stbi_gif_struct::pal[256][4]"

.SS "int stbi_gif_struct::parse"

.SS "int stbi_gif_struct::ratio"

.SS "int stbi_gif_struct::start_x"

.SS "int stbi_gif_struct::start_y"

.SS "int stbi_gif_struct::step"

.SS "int stbi_gif_struct::transparent"

.SS "int stbi_gif_struct::w"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
