.TH "TestRenderer" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestRenderer \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRenderingEngine\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestRenderer\fP (\fBWindow\fP *window)"
.br
.ti -1c
.RI "void \fBRender\fP (const \fBEntity\fP &object) override"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TestRenderer::TestRenderer (\fBWindow\fP * window)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void TestRenderer::Render (const \fBEntity\fP & object)\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBRenderingEngine\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
