.TH "TestGame" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestGame \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBGame\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestGame\fP ()"
.br
.ti -1c
.RI "virtual \fB~TestGame\fP ()"
.br
.ti -1c
.RI "virtual void \fBInit\fP (const \fBWindow\fP &window)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TestGame::TestGame ()\fC [inline]\fP"

.SS "virtual TestGame::~TestGame ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void TestGame::Init (const \fBWindow\fP & window)\fC [virtual]\fP"

.PP
Reimplemented from \fBGame\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
