.TH "Time" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Time \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBGetTime\fP ()"
.br
.ti -1c
.RI "int \fBHasElapsed\fP (int x)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double Time::GetTime ()"

.SS "int Time::HasElapsed (int x)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
