.TH "F:/Fusion3D_work/src/core/timing.h" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/Fusion3D_work/src/core/timing.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDelayTimer\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBTime\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBTime::GetTime\fP ()"
.br
.ti -1c
.RI "int \fBTime::HasElapsed\fP (int x)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
