.TH "Util" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Util \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBSleep\fP (int milliseconds)"
.br
.ti -1c
.RI "std::vector< std::string > \fBSplit\fP (const std::string &s, char delim)"
.br
.ti -1c
.RI "template<typename T > std::string \fBto_string\fP (const T &n)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Util::Sleep (int milliseconds)"

.SS "std::vector< std::string > Util::Split (const std::string & s, char delim)"

.SS "template<typename T > std::string Util::to_string (const T & n)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
