.TH "Vector2< T >" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vector2< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <math3d\&.h>\fP
.PP
Inherits \fBVector< T, 2 >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVector2\fP ()"
.br
.ti -1c
.RI "\fBVector2\fP (const \fBVector\fP< T, 2 > &r)"
.br
.ti -1c
.RI "\fBVector2\fP (T x, T y)"
.br
.ti -1c
.RI "T \fBCross\fP (const \fBVector2\fP< T > &r) const "
.br
.ti -1c
.RI "T \fBGetX\fP () const "
.br
.ti -1c
.RI "T \fBGetY\fP () const "
.br
.ti -1c
.RI "void \fBSetX\fP (const T &x)"
.br
.ti -1c
.RI "void \fBSetY\fP (const T &y)"
.br
.ti -1c
.RI "void \fBSet\fP (const T &x, const T &y)"
.br
.ti -1c
.RI "btVector3 \fBGetBT\fP () const "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBVector2\fP< T > \fBGetFT\fP (const btVector3 &bt)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T> \fBVector2\fP< T >::\fBVector2\fP ()\fC [inline]\fP"

.SS "template<typename T> \fBVector2\fP< T >::\fBVector2\fP (const \fBVector\fP< T, 2 > & r)\fC [inline]\fP"

.SS "template<typename T> \fBVector2\fP< T >::\fBVector2\fP (T x, T y)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename T> T \fBVector2\fP< T >::Cross (const \fBVector2\fP< T > & r) const\fC [inline]\fP"

.SS "template<typename T> btVector3 \fBVector2\fP< T >::GetBT () const\fC [inline]\fP"

.SS "template<typename T> static \fBVector2\fP<T> \fBVector2\fP< T >::GetFT (const btVector3 & bt)\fC [inline]\fP, \fC [static]\fP"

.SS "template<typename T> T \fBVector2\fP< T >::GetX () const\fC [inline]\fP"

.SS "template<typename T> T \fBVector2\fP< T >::GetY () const\fC [inline]\fP"

.SS "template<typename T> void \fBVector2\fP< T >::Set (const T & x, const T & y)\fC [inline]\fP"

.SS "template<typename T> void \fBVector2\fP< T >::SetX (const T & x)\fC [inline]\fP"

.SS "template<typename T> void \fBVector2\fP< T >::SetY (const T & y)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
