.TH "Vector4< T >" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vector4< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <math3d\&.h>\fP
.PP
Inherits \fBVector< T, 4 >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVector4\fP ()"
.br
.ti -1c
.RI "\fBVector4\fP (const \fBVector\fP< T, 4 > &r)"
.br
.ti -1c
.RI "\fBVector4\fP (T x, T y, T z, T w)"
.br
.ti -1c
.RI "T \fBGetX\fP () const "
.br
.ti -1c
.RI "T \fBGetY\fP () const "
.br
.ti -1c
.RI "T \fBGetZ\fP () const "
.br
.ti -1c
.RI "T \fBGetW\fP () const "
.br
.ti -1c
.RI "void \fBSetX\fP (const T &x)"
.br
.ti -1c
.RI "void \fBSetY\fP (const T &y)"
.br
.ti -1c
.RI "void \fBSetZ\fP (const T &z)"
.br
.ti -1c
.RI "void \fBSetW\fP (const T &w)"
.br
.ti -1c
.RI "void \fBSet\fP (const T &x, const T &y, const T &z, const T &w)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename T> \fBVector4\fP< T >::\fBVector4\fP ()\fC [inline]\fP"

.SS "template<typename T> \fBVector4\fP< T >::\fBVector4\fP (const \fBVector\fP< T, 4 > & r)\fC [inline]\fP"

.SS "template<typename T> \fBVector4\fP< T >::\fBVector4\fP (T x, T y, T z, T w)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<typename T> T \fBVector4\fP< T >::GetW () const\fC [inline]\fP"

.SS "template<typename T> T \fBVector4\fP< T >::GetX () const\fC [inline]\fP"

.SS "template<typename T> T \fBVector4\fP< T >::GetY () const\fC [inline]\fP"

.SS "template<typename T> T \fBVector4\fP< T >::GetZ () const\fC [inline]\fP"

.SS "template<typename T> void \fBVector4\fP< T >::Set (const T & x, const T & y, const T & z, const T & w)\fC [inline]\fP"

.SS "template<typename T> void \fBVector4\fP< T >::SetW (const T & w)\fC [inline]\fP"

.SS "template<typename T> void \fBVector4\fP< T >::SetX (const T & x)\fC [inline]\fP"

.SS "template<typename T> void \fBVector4\fP< T >::SetY (const T & y)\fC [inline]\fP"

.SS "template<typename T> void \fBVector4\fP< T >::SetZ (const T & z)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
