.TH "Window" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Window \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <window\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWindow\fP (int width, int height, const std::string &title)"
.br
.ti -1c
.RI "virtual \fB~Window\fP ()"
.br
.ti -1c
.RI "void \fBUpdate\fP ()"
.br
.ti -1c
.RI "void \fBSwapBuffers\fP ()"
.br
.ti -1c
.RI "void \fBBindAsRenderTarget\fP () const "
.br
.ti -1c
.RI "bool \fBIsCloseRequested\fP () const "
.br
.ti -1c
.RI "int \fBGetWidth\fP () const "
.br
.ti -1c
.RI "int \fBGetHeight\fP () const "
.br
.ti -1c
.RI "float \fBGetAspect\fP () const "
.br
.ti -1c
.RI "const std::string & \fBGetTitle\fP () const "
.br
.ti -1c
.RI "\fBVector2f\fP \fBGetCenter\fP () const "
.br
.ti -1c
.RI "SDL_Window * \fBGetSDLWindow\fP ()"
.br
.ti -1c
.RI "const \fBInput\fP & \fBGetInput\fP () const "
.br
.ti -1c
.RI "void \fBSetFullScreen\fP (bool value)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Window::Window (int width, int height, const std::string & title)"

.SS "Window::~Window ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Window::BindAsRenderTarget () const"

.SS "float Window::GetAspect () const\fC [inline]\fP"

.SS "\fBVector2f\fP Window::GetCenter () const\fC [inline]\fP"

.SS "int Window::GetHeight () const\fC [inline]\fP"

.SS "const \fBInput\fP& Window::GetInput () const\fC [inline]\fP"

.SS "SDL_Window* Window::GetSDLWindow ()\fC [inline]\fP"

.SS "const std::string& Window::GetTitle () const\fC [inline]\fP"

.SS "int Window::GetWidth () const\fC [inline]\fP"

.SS "bool Window::IsCloseRequested () const\fC [inline]\fP"

.SS "void Window::SetFullScreen (bool value)"

.SS "void Window::SwapBuffers ()"

.SS "void Window::Update ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
