.TH "F:/Fusion3D_work/src/components/worldComponent.h" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
F:/Fusion3D_work/src/components/worldComponent.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include 'meshRenderer\&.h'\fP
.br
\fC#include '\&.\&./rendering/lighting\&.h'\fP
.br
\fC#include 'programComponent\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBWORLDCOMPONENT_H_INCLUDED\fP   'WorldComponent'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBWorldComponent\fP ()"
.br
.ti -1c
.RI "virtual void \fBInit\fP ()"
.br
.ti -1c
.RI "virtual void \fBProcessInput\fP (const \fBInput\fP &input, float delta)"
.br
.ti -1c
.RI "virtual void \fBUpdate\fP (float delta)"
.br
.ti -1c
.RI "virtual void \fBRender\fP (const \fBShader\fP &shader, const \fBRenderingEngine\fP &renderingEngine, const \fBCamera\fP &camera) const "
.br
.ti -1c
.RI "\fBWorldComponent\fP * \fBSetUpModel\fP (\fBMeshRenderer\fP *model)"
.br
.ti -1c
.RI "\fBWorldComponent\fP * \fBSetUpLights\fP (\fBEntity\fP *lights)"
.br
.ti -1c
.RI "\fBWorldComponent\fP * \fBAddProgram\fP (\fBProgramComponent\fP *prog)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBMeshRenderer\fP * \fBm_model\fP"
.br
.ti -1c
.RI "\fBEntity\fP * \fBm_lights\fP"
.br
.ti -1c
.RI "std::vector< \fBProgramComponent\fP * > \fBm_progs\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define WORLDCOMPONENT_H_INCLUDED   'WorldComponent'"

.SH "Function Documentation"
.PP 
.SS "\fBWorldComponent\fP* AddProgram (\fBProgramComponent\fP * prog)"

.SS "virtual void Init ()\fC [virtual]\fP"

.SS "virtual void ProcessInput (const \fBInput\fP & input, float delta)\fC [virtual]\fP"

.SS "virtual void Render (const \fBShader\fP & shader, const \fBRenderingEngine\fP & renderingEngine, const \fBCamera\fP & camera) const\fC [virtual]\fP"

.SS "\fBWorldComponent\fP* SetUpLights (\fBEntity\fP * lights)"

.SS "\fBWorldComponent\fP* SetUpModel (\fBMeshRenderer\fP * model)"

.SS "virtual void Update (float delta)\fC [virtual]\fP"

.SS "WorldComponent ()"

.SH "Variable Documentation"
.PP 
.SS "\fBEntity\fP* m_lights"

.SS "\fBMeshRenderer\fP* m_model"

.SS "std::vector<\fBProgramComponent\fP*> m_progs"

.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
