.TH "zbuf" 3 "Tue Nov 24 2015" "Version 0.0.0.1" "Fusion3D" \" -*- nroff -*-
.ad l
.nh
.SH NAME
zbuf \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBuint8\fP * \fBzbuffer\fP"
.br
.ti -1c
.RI "\fBuint8\fP * \fBzbuffer_end\fP"
.br
.ti -1c
.RI "int \fBnum_bits\fP"
.br
.ti -1c
.RI "\fBuint32\fP \fBcode_buffer\fP"
.br
.ti -1c
.RI "char * \fBzout\fP"
.br
.ti -1c
.RI "char * \fBzout_start\fP"
.br
.ti -1c
.RI "char * \fBzout_end\fP"
.br
.ti -1c
.RI "int \fBz_expandable\fP"
.br
.ti -1c
.RI "\fBzhuffman\fP \fBz_length\fP"
.br
.ti -1c
.RI "\fBzhuffman\fP \fBz_distance\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBuint32\fP zbuf::code_buffer"

.SS "int zbuf::num_bits"

.SS "\fBzhuffman\fP zbuf::z_distance"

.SS "int zbuf::z_expandable"

.SS "\fBzhuffman\fP zbuf::z_length"

.SS "\fBuint8\fP* zbuf::zbuffer"

.SS "\fBuint8\fP * zbuf::zbuffer_end"

.SS "char* zbuf::zout"

.SS "char* zbuf::zout_end"

.SS "char* zbuf::zout_start"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fusion3D from the source code\&.
